### ISSUE TITLE
Nextcloud client crashed

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/desktop#1422]
Hello,

my PC is online often for 1-2 Weeks. This means, is Restart my PC not often. After a pair of days, maybe 1 week, the Nextcloud Client crashed without any message. When i restart the client, it works for a pair of hours and then crashed again without any message. At this point I need to restart my PC for the client to work properly.

I use:
Windows 10 Pro 1809
Nextcloud 16.04
Nextcloud Windows Client 2.5.2git Biuld 20190319

**Comment by camilasan** [comment]
Hi, we have released a new version 2.5.3: https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.5.3-setup.exe and we have a release candidate for 2.6: https://download.nextcloud.com/desktop/prereleases/Windows/nextcloud-2.6.0.5818-rc1-20190907.exe
Could you try those newer versions?

**Comment by XBrainBug** [comment]
Hi, i test now 2.6 and will give you Response.

**Comment by ConstantMown** [comment]
Hi, the 2.5.3 has behavior that looks like a memory leak at least on Linux and MacOS platforms, please see #124 for more details.
Unfortunately I cannot desktop client check memory usage on Windows, but I have verified that memory usage does grow on both Linux and MacOS platforms, using the Nextcloud built desktop binaries.

**Comment by XBrainBug** [comment]
Hi, now it works for about 1 week, i think it is fixed!

**Comment by XBrainBug** [comment]
Hi, now i use the client Version 2.6.2stable and have the same problem again!

**Comment by observative** [comment]
Same here, 2.6.2git crashes after login, on linux mint 19.2.

**Comment by castaf** [comment]
Same here (Version 2.6.3stable (build 20200217)): Nextcloud macOS client crash silently after a variable period of time.

**Comment by castaf** [comment]
> Same here (Version 2.6.3stable (build 20200217)): Nextcloud macOS client crash silently after a variable period of time. I will try with the last version (Version 2.6.4stable (build 20200303))...

Same result with version 2.6.4 : the client still crash. Here joined the logs.
[nextcloud_2020-03-07-151238_iMac-de-Fabien.crash.txt](https://github.com/nextcloud/desktop/files/4306002/nextcloud_2020-03-07-151238_iMac-de-Fabien.crash.txt)
