### ISSUE TITLE
High memory consumption on macOS Mojave

### ISSUE THREAD

**Issue by scgf** [nextcloud/desktop#1464]
Since version 2.3.3 the Nextcloud Mac client starts off using around 55MB RAM. After doing nothing for a couple of hours I see memory consumption increasing gradually. After a day or so it has reached over 1GB and shows no sign of slowing up. If I run any Owncloud desktop client there is no issue, it works perfectly with my Nextcloud install and memory consumption remains pretty constant. After one week the Owncloud desktop client I am running (2.6.0beta1) is showing 34MB.

**Comment by scgf** [comment]
I am running macOS 10.14.6 on an iMac 4K 2017 21". I have 8GB RAM and an Apple SSD 250GB drive. My Nextcloud installation is on a Synology DS218+ NAS with 6GB RAM. I am running Nextcloud v. 17.0.0 but the client issue has been apparent over the last few versions of Nextcloud.

**Comment by gcoretech** [comment]
This gets worse the longer it runs. We've seen 34GB memory usage which slowed the whole system down, it was heavily swapping.

**Comment by JohnWalkerx** [comment]
I can confirm this. Today I wondered why my mac is so slow and nearly unusable and then I see the nextcloud client uses 7,9 GB RAM. 
For me, the client have to keep in sync 216 GB of data.

If more information or tests are needed, let me know. 

<details>
<summary>Client Configuration</summary>

```
macOS 10.14.6 on MacBook Pro 15" Mid-2012 8GB RAM
Nextcloud Client 2.6.0stable (build 20190927)
Nextcloud Server 16.0.5
```
</details>

**Comment by scgf** [comment]
A solution for now is to install the latest OwnCloud client - it works fine with NextCloud and does not eat memory.

**Comment by nicokaiser** [comment]
I can confirm that the current version of the ownCloud Client works with much better memory usage (steady 30-40 MB instead of constant growing). What’s the difference? Maybe the new OAuth login dialog?

**Comment by misch7** [comment]
Please try our 2.6.2 RC1 build:
https://github.com/nextcloud/desktop/releases/tag/v2.6.2-rc1

We've targeted some related issues and this might solve the problem, please let me know :)

**Comment by nicokaiser** [comment]
Thanks @misch7, I'll try the RC1 version. 
After installing the initial memory footprint is already (much) larger than with ownCloud 2.6.0 (~55-80 MB vs. ~30-40 MB for a ~300 MB synced folder), but this seems to normalize over time. I'll check if it is still growing.

**Comment by nicokaiser** [comment]
After some days of normal use, memory usage in 2.6.2-rc1 seems to be much better than with 2.6.1.

**Comment by JohnWalkerx** [comment]
After 7 days of running 2.6.2-rc1, the client uses 658 MB of memory (still growing). (4 accounts, ~240 GB to keep in sync).
My feeling is that it grows much slower than before. But I have no idea who long my client runs before.

**Comment by misch7** [comment]
🎅 

We released 2.6.2 just yesterday and I did some optimizations in the Activity List code. Could you try the new release?

https://github.com/nextcloud/desktop/releases/tag/v2.6.2

Curious if this helps for this issue too :)

**Comment by jknockaert** [comment]
I am using 2.6.2 on macOS High Sierra. I am not sure when I last rebooted, but the Nextcloud client is now using 1.4 GB of RAM for 314 parallel threads. There must be something going not quite right.

**Comment by nicokaiser** [comment]
Is there a way to debug a process when this happens?

For my production machine I switched back to the ownCloud client, which runs with stable memory consumption and without QtWebEngine bloatware... but I‘d love to help finding the problem.

**Comment by jknockaert** [comment]
@nicokaiser It's been suggested before that QtWebEngine takes much of the blame for performance issues with the Nextcloud client. It has also been suggested in #932 to remove it. Is it correct that the whole QtWebEngine is needed only for the initial login process? If so, wouldn't there be a more efficient client-side implementation possible for this specific procedure?

**Comment by joshtrichards** [comment]
This thread hasn't seen any traffic in >4 years. Are any of you still experiencing this?

**Comment by claucambra** [comment]
Since this thread hasn't seen an update in a while I will close -- if anyone experiences this on the latest client versions and is able to provide a spindump please repopen

**Comment by Cubytus** [comment]
Hello there, 

slightly different configuration with Mac OS X Catalina and client 2.6.5. Many accounts are being synchronized.
Exact same issue as described by OP.
**Symptoms:**
Client starts using up a somewhat reasonable amount of RAM, and gradually increases to multi-gigabytes numbers slowing the whole system when it starts swapping.

spindump attached.

[NC RAM hog 4GiB spindump.txt](https://github.com/user-attachments/files/18456505/NC.RAM.hog.4GiB.spindump.txt)
