### ISSUE TITLE
White background in recipient list

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#1483]
See white background in recipient list

![image](https://user-images.githubusercontent.com/5836855/66291160-6ddd0e00-e8e1-11e9-88a2-1dd137c343df.png)

**Comment by jancborchardt** [comment]
This is fixed in the pull request at https://github.com/nextcloud/desktop/pull/1429 :)

**Comment by tobiasKaminsky** [comment]
Not sure how you do this in other repos, but in Android we keep issues open until PR is merged (and in PR we use "fix #123123123" so that Github auto closes this).
This ensures that other reporters can more easily find the issue (as it is technically not yet solved).

**Comment by jancborchardt** [comment]
Yep, we normally do that too, but since https://github.com/nextcloud/desktop/pull/1429 does not have a reference to this here, I closed it so we don’t have to clean up afterwards. I should have mentioned that, sorry. :)

@DominiqueFuchs you probably know if you include "…, fix #1429" in a commit it closes the issue automatically on merge? :)

**Comment by tobiasKaminsky** [comment]
It does not necessarily have to be in a commit, you can just put in the PR description (it just has to be the first line(s))

**Comment by DominiqueFuchs** [comment]
@jancborchardt yeah I know about this, generally I list relating issues like that in the PR, then they are automatically resolved when merging - just didn‘t know about this one.
I‘ll fix the conflict blocking the PR merge within this week

**Comment by DominiqueFuchs** [comment]
FTR: Merged #1429 🎃
