### ISSUE TITLE
v2.7.0-beta1 loses part of the folder configuration

### ISSUE THREAD

**Issue by Babene03** [nextcloud/desktop#1742]
Hi, I have the beta running on a Windows Server 2016, 2 accounts with 4 folders each are registered. After restarting the client, parts of the folders are gone. In the Nextcloud-1.log I have add the Folder "N:\UNTERNEHMENS Server1" but after restart I must add the folder new, see Nextcloud-2.log.

The client should keep the folders in the configuration.

• After restarting the client (probably when exiting) the configuration is not loaded / written correctly because there are no folders.

Client version:
v2.7.0-beta1

Operating system: 
Windows Server 2016

OS language: 
German

Qt version used by client package (Linux only, see also Settings dialog): 
5.12.5

Installation path of client: 
C:\Program Files\Nextcloud

### Server configuration
Nextcloud version:
18.0.0

Storage backend (external storage):
internal storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[Nextcloud-1.log](https://github.com/nextcloud/desktop/files/4089780/Nextcloud-1.log)

2. Client logfile after restart Client:
[Nextcloud-2.log](https://github.com/nextcloud/desktop/files/4089779/Nextcloud-2.log)

**Comment by Babene03** [comment]
What about the BUG?
Is this fixed now?
Or do I have to set up the folders after every restart or crash when I restart the APP? Surely this cannot be wanted?

**Comment by Babene03** [comment]
@misch7

**Comment by Babene03** [comment]
With today's daily release "2.7.0daily-Win64 (build 20200219) git-Revision 7bb364 Feb 19 2020, 03:07:06, Qt 5.12.5, OpenSSL 1.1.1d 10 Sep 2019" there is no improvement, the problem remains.

**Comment by Babene03** [comment]
Is still current in the daily version 2.7.0.15235-daily-20200323 release.

In Release v2.6 and v2.6.4 everything is correct. This actually puts the v2.7.0 beta back in pre alpha status. Since this error has existed for more than 3 months.

**Comment by DominiqueFuchs** [comment]
From a first glimpse I do not spot anything suspicious in the log files. However, the state till March was very transient and early in the 2.7-development. 

I can not reproduce this at least with Windows 10 or macOS (tested with beta 3, also two accounts, 6 folders added on first run). Does the problem still persist for you @Babene03 ?

**Comment by er-vin** [comment]
I agree with @DominiqueFuchs this sounds like something fairly transient that one might not be able to hit anymore.

**Comment by er-vin** [comment]
Closing it for the reasons above, will reopen if it shows up again with a clean setup.
