### ISSUE TITLE
Missing header buttons in tray window with Ubuntu package

### ISSUE THREAD

**Issue by ShevT** [nextcloud/desktop#1746]
nextcloud-client 2.7.0-20200121.032623~eoan1

![qt_version](https://user-images.githubusercontent.com/4339059/72803565-77f00600-3c5f-11ea-8c32-0cf7a11f4543.png)

![nexcloud](https://user-images.githubusercontent.com/4339059/72803648-a5d54a80-3c5f-11ea-94f6-3b1222e39523.png)

**Comment by DominiqueFuchs** [comment]
Thanks for reporting, @ShevT !

I'm not fully understanding this issue though:

1. Why is the window so transparent? Hard to see anything
2. You mean the trayheader buttons lice local folder, apps, right?
3. Could you retry with the latest version? 2.7.0-20200121.162920~eoan1
4. Are the buttons functional or completely missing? (E.g. only missing icons but working on click or completely nonexistent)

**Comment by ShevT** [comment]
1) While taking a screenshot, the window closes. Therefore, I caught a transparent. In the original, it is not transparent.
2) Yes
![Screenshot_20200122_111745](https://user-images.githubusercontent.com/4339059/72877100-2d2ac880-3d09-11ea-9387-db850c88ca65.png)
3) Same (see screenshot)
4) All buttons work. Only missing icons.

**Comment by DominiqueFuchs** [comment]
Thanks again for clarifying! As I can't reproduce this with the app being built directly from source (or the AppImage), I'm assuming this is some problem with the ubuntu beta packages - maybe with the QT::Svg module or asset paths. I'll look into this (and maybe ask @ivaradi for some more info) as soon as we approach a more stable master state, which is not yet the case right now because there are first some other issues that have to be finished (including our package build-chain itself).

Until then, if you want to play around with the current state and test it, you may want to try the current AppImages (see #1744 for more info on that) :-)

**Comment by ShevT** [comment]
> Until then, if you want to play around with the current state and test it, you may want to try the current AppImages (see #1744 for more info on that) :-)

Icons are displayed with this version
![Screenshot_20200122_151047](https://user-images.githubusercontent.com/4339059/72894022-74c24c00-3d2b-11ea-8d42-946c8a0c56e0.png)

**Comment by ShevT** [comment]
Fixed in #1744

**Comment by ShevT** [comment]
After merge # 1744 the problem remained

**Comment by nicolasfella** [comment]
I can reproduce this with current master. The icons are only missing when the org.kde.desktop QQC2 style is used, forcing it to e.g. Material with `QT_QUICK_CONTROLS_STYLE=Material nextcloud` makes them appear

**Comment by nicolasfella** [comment]
There seem to be a few things broken. 

First the org.kde.desktop QQC2 style needs patching to support loading icons from qrc (https://phabricator.kde.org/D28194)

Then the icons are still not visible because the background seems to "cover" it. When I comment out the background assignment I see the icons. Not sure yet whether that's an issue in the KDE QQC2 style or Nextcloud

**Comment by er-vin** [comment]
So it turns out I've hunting that one today and indeed as @nicolasfella several things are in the way. First there the patching needed to support loading icons from qrc URLs in the org.kde.desktop QQC2 style. But it's only half of the story...

The QQC2 style is done in a way that everything is rendered via a private StyleItem (which delegates to QStyle) set on the background property of the control... Yes, that means that overriding that property basically throws out all the rendering from the org.kde.desktop style...

Honestly, this makes for a very fragile style IMO. I wonder if it should be modified to not use background like that. I wonder if using the contentItem wouldn't make more sense. Anyway, I think this should be fixed on the style side.

In the meantime, my PR #1962 should work around that issue.
