### ISSUE TITLE
Time Out when Nextcloud App is downloading big files or a lot of files. 

### ISSUE THREAD

**Issue by marcosms** [nextcloud/desktop#1778]
**Expected behaviour**

I have a nextcloud account in my server. I don't have too many archives, but some of my collegues are sharing with me some folders with lots of files. The total size of my account is 60 GB (my folder and the folders sared with me). I want to sync this folder in another computer (with windows 10). I want that all the contents were downloaded in this computer by the sync app. 

**Tell us what should happen**

The sync shows me a timeout error. It takes a lot of time checking the folder structure, and when the program begin the sync, when it synchronized between 200-400 MB it stops the synchronization due a timeout error. All of the users of our server are affected (Is not a problem of a single user). Same in my personal server in a raspberry pi. 

**Steps to reproduce**

1) Find a windows 10 user with lots of big files synchronized with your owncloud server. 
2) Delete the user in the nextcloud desktop application. 
3) Delete the nextcloud folder in the client computer
4) Configure again the nextcloud desktop application in a new empty folder
5) wait for the sync. The synchronization will show an error. 
6) uninstall the Nextcloud desktop application and delete again the synchronization folder. 
6) Install the OWNCLOUD desktop app. Configure it in a new folder and start the synchronization with the Nextcloud server
6) you will notice that the sync will end without errors and the initial check for the folder structure will do faster than whith the nextcloud client app. 

**Client configuration**

We made the connections over https. User, password... nothing special. 

**Client version:**

We try with the 2.6.2 desktop app and the beta app (nextcloud-2.7.0.15123-daily-20200211-Release)

**Operating system:**

Windows 10

**OS language:**

Spanish

**Qt version used by client package (Linux only, see also Settings dialog):**

--

**Client package (From Nextcloud or distro) (Linux only):**

--

**Installation path of client:**

C:\Program Files (x86)\Nextcloud

**Server configuration**

  'default_language' => 'es',
  'default_locale' => 'es_ES',
  'logtimezone' => 'Europe/Madrid',
  'auth.bruteforce.protection.enabled' => false,
  'asset-pipeline.enabled' => false,
  'instanceid' => 'xxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxx',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
    'password' => 'xxxxxxxxxxxxx',
  ),
  'trusted_domains' =>
  array (
    0 => '192.168.0.8',
    1 => '178.60.208.14',
    2 => 'tabigal.dyndns.org',
    3 => 'montesqueiro.linkpc.net',
    4 => 'www.tabigal.dyndns.org',
    5 => 'www.montesqueiro.linkpc.net',
    6 => '79.148.250.215',
    7 => 'nube.tabigal.com',
    8 => 'nube.montesqueiro.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://nube.tabigal.com',
  'dbtype' => 'mysql',
  'version' => '17.0.3.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'noresponder',
  'mail_domain' => 'tabigal.com',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxxxxxxxxxxx',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'xxxx@tabigal.com',
  'mail_smtppassword' => 'xxxxxxxxxxxx',
  'mail_smtpsecure' => 'tls',
  'theme' => '',
  'maintenance' => false,
  'app.mail.server-side-cache.enabled' => true,
  'appstore.experimental.enabled' => true,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto, 60',
  'updater.release.channel' => 'stable',
  'mysql.utf8mb4' => true,
  'app_install_overwrite' =>
  array (
    0 => 'announcementcenter',
    1 => 'admin_notifications',
  ),
  'mail_sendmailmode' => 'smtp',

**Nextcloud version:**
17.0.3.1 - Installed in a Ubuntu 16.04, PHP 7.3, Apache, Redis, installed in a Virtual Machine over VMWare. 

Same in a personal installation in my Raspberry Pi (17.0.3.1, Raspbian lite, PHP7.2, Apache, Redis). 

**Storage backend (external storage):**
NO

I don't have nothing in the logs when the error appears. Nothing in the server side, and in the client side i have a timeout error. Logs are very big (54 Mb on server side and a lot of lines on client side) but i only see the "timeout" error on client side.

**Comment by mburnicki** [comment]
This may be the same problem as #1059, so changing the `OWNCLOUD_CHUNK_SIZE` setting as explained in [this comment](https://github.com/nextcloud/desktop/issues/1059#issuecomment-578922790) may help. I'm not a maintainer, but another user who had a similar problem which was fixed by this change.

**Comment by marcosms** [comment]
No. I had tried the solution posted in that thread (i tried a lot of diferent solutions with no results), but it didn't solve the problem. Note that my problem is downloading the files, and the thread that you put is a problem uploading files (Changing the metadata of some files). 

As the problem is solved when i use the Owncloud client, i'm convinced that there is a serious bug in the Nextcloud client that must be reviewed.

**Comment by mburnicki** [comment]
OK, it was just an idea. BTW, for me the problem **_did_** occur when I downloaded files from a server to a client, e.g. initial sync after a new server/account had been added. But I agree, this is a serious problem.

**Comment by hjohanns** [comment]
I subscribed to the issue. My users have a lot of files to sync, and the synchronisation is frequently unstable, including a scenario which is the same as described here.

**Comment by Volker-K** [comment]
At our company we had such cases, too.
Searching for the reasons we found that those timeouts were buffer overflows on the windows machine. Something seemed to make processing of the data slow, especially with bigger archives. Windows Defender already was disabled, so we desabled our malware protection on a test machine, too. Still timeouts with buffer overflows on the client.
After adding our NC URL to the **trusted sites** in the old fashioned, Win95-like Internet Settings (I could only access them via MSIE, even at Windows 10 they look like Win95) the problem disappeared.
The problem appeared in 2019 for the first time, possibly any Windows "Fix"pack accidentally enabled Defender for such WebDAV-Access?

**Comment by wagnbeu0** [comment]
I have the same problem. For testing purpose I created a new user "testuser" in my NC instance and let them sync the userfiles to my local Win10 VM. No problem. Then I shared a folder "Videos" to this testuser. It was synced without any problem, about 100 Files with total 44 GB. Next I shared my "Photos" folder to this user with 280 GB and ~64.000 Files. It starts reading the content of the folder on the server, searched through subdirectories, and then I get "Connection aborted" messages back, everytime with different folders.

It must have something to do when a huge amount of files in lots of subfolders must be synced. Can anyone confirm that?

**Comment by wagnbeu0** [comment]
I now also checked with Client 3.2.1, but no success. When triying to sync huge folders It will never complete, but will get several timeouts. It will only work with smaller amount of files.

**Comment by dimm0** [comment]
Not stale

**Comment by mgallien** [comment]
> Not stale

Please provide the desktop client logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)
Thanks!

**Comment by wagnbeu0** [comment]
Here are the log files:
[Nextcloud_archiv.zip](https://github.com/nextcloud/desktop/files/6662702/Nextcloud_archiv.zip)

**Comment by Reaver1202** [comment]
I have the same issue with nextcloud-pi on an Raspberry Pi 4 using docker.

First I had it on that setup with Windows Clients at our small company:
  - Uploading a folder with 700+ subfolders containing images on one machine, while others are shutdown.
  - Then downloading this through the nextcloud client on another PC that was shutdown during the upload. So it needs to download the whole folder and sub folders.
  - Error: Timeout during the download of the folder list by the client.
  - I was able to fix it by syncing it in parts or by reducing the number of subfolders and syncing in parts. All of that was during a time of introducing Nextcloud to the company - so a lot of stuff was uploaded as initial start and we ran into this problem with quite often.
  - I also tried some Network tweaks and so on. I did not unstood why this happens, because on my private setup using the same technolgies I never had such problems.

Then I found this bug report here some months ago, undstood that Nextcloud must have an issue here and had some hope that it will be fixed in future releases.

Today I had this issue on my private setup. Also nextcloud-pi on Raspberry Pi 4 running in docker and Mac and Windows Client.
  - yesterday I found a nice tool **Eagle App** for organizing images and PDFs.
  - First I loaded some files into it on my Mac with about 270 MB of data, then trying the sync via Nextcloud to my Windows PC to see what happens with the Eagle Library. All fine. Finally I added about 2000 files with 1,8 GB of data on that Windows PC to have some fun with the app, while my Mac was offline.
  - Today I wanted to work on my Mac and I ran into the exact same Nextcloud problem.
  - Eagle stored each imported file into an own folder with an unique ID to store the file itself and additional meta information like comments, tags, rating, notes edited in the Egale App  in a JSON file. So i finally hat about 2000 folders containing 4000 files.
  - The Sync to my Mac had the same Timeout issues like months before in the company.

But THEN I activated the **Debug Log with F12 like mentioned here above** and it started to sync and finally synced the whole 2000 folders without an issue.
I will try that in the future when this problem occurs again. **Maybe it is a workaround** until this gets fixed.
Hope this helps the developers as well as some guys with the same problem.

**Comment by wagnbeu0** [comment]
I am very happy that I am not the only one. As said I wrote a script which will create thousands of files and subfolders - and here you see that the limiteation is not the filesize itself - it is the summary of files and folder which Nextcloud cannot sync. I hope the developers are aware of it and how to fix it - I do not want to image what happened if ypopu introduce a new storage system in a company and need to tell uses: Don´t upload everything in one step, split it in junks - the new too cannot handle it.
