### ISSUE TITLE
Clien will not stay running.

### ISSUE THREAD

**Issue by curtis-bob** [nextcloud/desktop#2266]
Application opens then closes right away either by start up or Manually opening.

windows Version - winodws 10 pro - version 2004

-----------------Event Viewer Info-----------------
General  ---

_Faulting application name: nextcloud.exe, version: 2.6.5.15622, time stamp: 0x5f07b735
Faulting module name: ocsync.dll, version: 0.0.0.0, time stamp: 0x5f07b5c8
Exception code: 0xc0000005
Fault offset: 0x0000000000017230
Faulting process id: 0x1d18
Faulting application start time: 0x01d670abc4e1e703
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\Program Files\Nextcloud\ocsync.dll
Report Id: 05c8a91b-1abf-42cb-b982-a645aa72f50c
Faulting package full name: 
Faulting package-relative application ID:_ 

Details ---

_Log Name:      Application
Source:        Application Error
Date:          8/12/2020 8:23:30 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Curtis-Yoga2.NETCOMTECHS.local
Description:
Faulting application name: nextcloud.exe, version: 2.6.5.15622, time stamp: 0x5f07b735
Faulting module name: ocsync.dll, version: 0.0.0.0, time stamp: 0x5f07b5c8
Exception code: 0xc0000005
Fault offset: 0x0000000000017230
Faulting process id: 0x1d18
Faulting application start time: 0x01d670abc4e1e703
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\Program Files\Nextcloud\ocsync.dll
Report Id: 05c8a91b-1abf-42cb-b982-a645aa72f50c
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-12T13:23:30.8537249Z" />
    <EventRecordID>21242</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Curtis-Yoga2.NETCOMTECHS.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>nextcloud.exe</Data>
    <Data>2.6.5.15622</Data>
    <Data>5f07b735</Data>
    <Data>ocsync.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>5f07b5c8</Data>
    <Data>c0000005</Data>
    <Data>0000000000017230</Data>
    <Data>1d18</Data>
    <Data>01d670abc4e1e703</Data>
    <Data>C:\Program Files\Nextcloud\nextcloud.exe</Data>
    <Data>C:\Program Files\Nextcloud\ocsync.dll</Data>
    <Data>05c8a91b-1abf-42cb-b982-a645aa72f50c</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>_

If you need any more information Let me know.

**Comment by biva** [comment]
Same issue on my side, any news @er-vin ? How did you solve it @curtis-bob ?

**Comment by biva** [comment]
Solved with https://help.nextcloud.com/t/netxtcloud-client-crashes-at-startup-on-windows-10/91434/9

deleted this folders:

    C:\Users\yourname\AppData\Local\Nextcloud
    C:\Users\yourname\AppData\Roaming\Nextcloud

@er-vin I see this problem is probably critical for a lot of users. Shouldn't it be in the documentation somewhere?

**Comment by er-vin** [comment]
Well, shouldn't crash in the first place I'd say. Now that you removed the folders it's maybe a bit late but I would have been interested in debug logs before the crash occurs.

**Comment by curtis-bob** [comment]
honestly I haven't.. and I forgot i posted this.. i have still been having this problem on my laptop.. so I will try your solution biva.

"er-vin" no I didn't remove the files. even if the files were removed I would assume that the nextcloud shouldn't close otherwise how would you fix the missing folder.. and since i have forgotten about this issue I would have to work at getting those logs for ya. when I get the chance I defiantly will..


sorry had a lot of other issues that were higher priorities than my nextcloud inconvenience.. everything els dealing with nextcloud works great. no complaints. I tend to use SyncThing to Sync between systems anyway. so this hasn't been a huge issue.

**Comment by curtis-bob** [comment]
thank you all for the responses..

**Comment by ggallup** [comment]
I've tried uninstalling and re-installing and have deleted C:\Users\yourname\AppData\Local\Nextcloud (C:\Users\yourname\AppData\Roaming\Nextcloud did not exist) and I am still unable to open nextcloud. For me this was a new install of 3.0.2 that worked fine for about a week, then suddenly stopped opening at all.

**Comment by MrToast99** [comment]
I'm currently having this issue. What logs does everyone wanna see?

**Comment by er-vin** [comment]
Alright, keep in mind this is a crash so it will be a bit involved.

All the steps below need to be done with the client not started.

We would need the debug logs of the client when it starts, this can be achieved by adding the following in the nextcloud.cfg General group:
logDebug=true
logExpire=24
logDir=C:/nextcloud-logs

Also make sure C:\nextcloud-logs exists before launching the client.

Since it is a crash, it would also be really nice if we could have a backtrace of it. Apparently you can install procdump to do this: https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

And then running the following on the command line: procdump -ma -i C:\dumps

After launching, log files and crash dumps should appear in the corresponding folders these are the files we're interested in.

**Comment by PetrusVermaak** [comment]
@er-vin I have the same problem. I followed your steps bu nextcloud-logs stays empty.
procdump produced the following: https://www113.zippyshare.com/v/qffD3s14/file.html
