### ISSUE TITLE
Menu Bar Icon Looks Wonky on macOS Big Sur

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/desktop#2584]
This is a fairly minor thing, but the menu bar icon for Nextcloud is oversized and kind of pixelated on macOS Big Sur. It may or may not be oversized and pixelated on older versions of macOS, as well, but I've only ever used Nextcloud on Big Sur. I am attaching a screenshot of the Nextcloud menu bar icon next to the Time Machine menu bar icon, for comparison. It would be nice if they matched.

<img alt="Nextcloud Menu Bar Icon Next To Time Machine Menu Bar Icon" src="https://user-images.githubusercontent.com/9206310/96986882-422ec500-14f0-11eb-9673-40c1587d9414.png">

(Yes, I know Big Sur is still in beta. I'm using Nextcloud Desktop 3.0.2 on the macOS Big Sur Beta build 20A5395g.)

**Comment by kersten-lohmeyer** [comment]
Same here. "Problem" didn't exist in prior macOS versions.

**Comment by elsiehupp** [comment]
I dug into the code, and it seems like this is a bug with Qt, so [I filed a bug report with them](https://bugreports.qt.io/browse/QTBUG-90370).

**Comment by er-vin** [comment]
Note that #2829 has more information, looks like it could be fixed by upgrading our Qt to 5.12.11

**Comment by elsiehupp** [comment]
I just built Nextcloud Desktop using Qt 5.15.2, and the problem is not resolved:

<img alt="Screen Shot 2021-01-22 at 9 21 30 AM" src="https://user-images.githubusercontent.com/9206310/105502951-01cc1800-5c94-11eb-807a-cfc788236180.png">

I also [updated the bug report](https://bugreports.qt.io/browse/QTBUG-90370?focusedCommentId=550139&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-550139) over on the Qt JIRA.

**Comment by elsiehupp** [comment]
As a debug hack, I rebuilt Nextcloud with a solid-fill icon, and the resulting square is 44px x 44px. Nextcloud's build scripts I'm fairly certain expect the dimensions of the icon to be a base-2 number, e.g. 32px x 32px. The native macOS "play" glyph to the left of the Nextcloud icon is 26px x 26px, which suggests 32px square with a 3px margin.

<img alt="Screen Shot 2021-01-22 at 11 04 45 AM" src="https://user-images.githubusercontent.com/9206310/105515274-7f972000-5ca2-11eb-81dc-e955f3e395fc.png">

**Comment by elsiehupp** [comment]
As I suspected, resizing the icon canvas from 16x16 logical pixels to 22x22 logical pixels (i.e. adding significant padding around the icon) shrank it back down to size:

<img alt="Screen Shot 2021-01-22 at 12 45 13 PM" src="https://user-images.githubusercontent.com/9206310/105526125-fdadf380-5caf-11eb-984c-b29e19c751a6.png">

However:

1. This workaround would likely cause the icons to be *too small* on earlier versions of macOS.
2. There are still visible scaling artifacts, so while the icon is now sized correctly, it appears jaggy next to the native Apple icons.
3. If the reason the icon is squished/stretched to an oblong shape on a second desktop as in #2642 and #2829 is that the shape Qt is using to stretch the icon is not square, adding padding around the icon will not fix that problem, either.

**Comment by elsiehupp** [comment]
As an aside, using a 13px x 13px icon for Nextcloud rather than the current 14px x 14px would make it better match the size of the Apple icons, but it's unclear how centering the icon on a 16px x 16px canvas would work on a non-Retina screen.

**Comment by er-vin** [comment]
Not sure we'll get to it soon, but I'd like to point out: Thanks a lot @elsiehupp for all your efforts this definitely gives valuable information.

**Comment by supermina999** [comment]
The issues seems to be resolved in Qt 5.15.3 Preview, at least for my app

**Comment by elsiehupp** [comment]
@supermina999 that's great to hear! Do you know when Qt 5.15.3 is slated to be released from Preview? Hopefully the fix can get integrated into a Nextcloud release sooner rather than later!

I did some quick googling, and it sounds like [Qt 5.15.3 might be commercial-only](https://devclass.com/2021/01/05/qt-lts-5_15/). Do you know if that means Nextcloud will or will not be able to build against it?

**Comment by supermina999** [comment]
@elsiehupp I don't know the release dates, since I'm not affiliated with Qt Company, I do have the commercial edition though. My bet would be that if Qt has a fix internally, it should be available in the next Qt 6 releases, so you can try building with those as well. Unluckily, my commercial license doesn't cover Qt 6, so I can't try it out.

**Comment by haroldm** [comment]
#2891 is mentionned as a duplicate so I'll leave here the link to the associated Qt bug : https://bugreports.qt.io/browse/QTBUG-88600

**Comment by elsiehupp** [comment]
@haroldm ooh, that one's marked as fixed in 5.15.1, not 5.15.3, which suggests it might be available to non-LTS (i.e. non-paid) Qt users!

**Comment by b-a0** [comment]
This seems to be fixex in the Nextcloud client 3.1.3

**Comment by TheTrueTom** [comment]
> This seems to be fixed in the Nextcloud client 3.1.3

I don't think it is. At least the fix is not effective here.

**Comment by b-a0** [comment]
My bad, I wanted to indicate that for me this solves #2829 .As that issue was closed in favour of the current issue I figured that if #2829 was solved, the current issue would be solved as well. I've edited my comment above and added a comment to #2829.

**Comment by elsiehupp** [comment]
I just updated to 3.1.3, and the icon is still oversized. I don't have a second desktop, though, so I can't test for #2829. (It sounds like #2829 is fixed, though.)

**Comment by TheTrueTom** [comment]
For me the icon is still squished on my secondary monitor where it has the right height but not the corresponding width.
Unless the secondary monitor thing is another issue I wouldn't consider #2829 as fixed yet.

**Comment by haroldm** [comment]
#2829/ #2891 is not fixed with Nextcloud 3.1.3.

**Comment by b-a0** [comment]
Pity that this doesn't seem to fix the issue completely. For me at [least it does](https://github.com/nextcloud/desktop/issues/2829#issuecomment-792332961)(screenshot shows the menubar of my second monitor, while my first monitor has focus). Let me know if I can provide any information to help track down why it's fixed for me and not for others.

**Comment by elsiehupp** [comment]
@b-a0 since it's an upstream Qt bug, it really depends on whether the build came from a version of Qt that has fixed the issue or not. Depending on when they fix the bug, the fix may or may not be easy for Nextcloud to implement (i.e. if it's a major Qt version upgrade, it would probably be part of a more in-depth project).

**Comment by elsiehupp** [comment]
That is, if fixing the bug involves, say, upgrading to Qt 6, then it might take a while.

**Comment by b-a0** [comment]
The build came from the official nextcloud website (not sure what that means for the Qt version). 

Just for completeness, here are my icons when I use the built in display only and when I use my two DisplayLink monitors:

Built in display MacBook Pro:
<img width="147" alt="Screenshot 2021-03-08 at 16 33 20" src="https://user-images.githubusercontent.com/25707742/110346801-37547700-8030-11eb-9e10-2e1d5cd49fe9.png">

DisplayLink monitor which has focus (i.e. I clicked on a window on the monitor):
![Screenshot 2021-03-08 at 16 53 18](https://user-images.githubusercontent.com/25707742/110346860-463b2980-8030-11eb-92fa-1e9577b23f7f.png)

DisplayLink monitor which does not have focus (i.e. I clicked on a window on the other monitor):
![Screenshot 2021-03-08 at 16 53 24](https://user-images.githubusercontent.com/25707742/110346911-55ba7280-8030-11eb-930e-a1e17806767a.png)

**Comment by b-a0** [comment]
Alright, I think I found a confounding factor: the [DisplayLink](https://www.displaylink.com/downloads/macos) driver I use to connect to my monitors over USB. 

I downgraded the DisplayLink drivers from version 1.3 to 5.2.5 (yes, DisplayLink version number is backwards somehow) to resolve a separate issue (clamshell mode not working) and now, after a restart the squishy large icon is back.

DisplayLink monitor which has focus:
![image](https://user-images.githubusercontent.com/25707742/110350789-5d7c1600-8034-11eb-8479-bdbd7da576e7.png)

DisplayLink monitor which does not have focus:
![image](https://user-images.githubusercontent.com/25707742/110350815-653bba80-8034-11eb-9ce2-72822556fdaf.png)


Magically (and unrelated to Nextcloud) the KeePass icon is fine now (I though [the issue was related](https://github.com/keepassxreboot/keepassxc/issues/5762))

**Comment by b-a0** [comment]
This is still an issue for me with the nextcloud client (v3.1.3). [keepassXC](https://github.com/keepassxreboot/keepassxc/issues/5762) has resolved a similar bug, so perhaps they can be of help.

**Comment by elsiehupp** [comment]
My best guess is that this issue is going to stick with us until we upgrade the underlying version of Qt, which might even mean upgrading from Qt 5 to Qt 6 (a rather significant undertaking) because Qt 5 has entered LTS status. Thanks QTCOM! 🙄

**Comment by nicolasfella** [comment]
We do have the source code for the fix (https://codereview.qt-project.org/c/qt/qtbase/+/322772/2/src/plugins/platforms/cocoa/qcocoasystemtrayicon.mm), the only thing we don't have is prebuilt binaries from Qt itself.

In this case it's probably the best short-term solution is to ship our own Qt binaries built from source with that patch applied.

**Comment by Ein-Tim** [comment]
This issue is still existing on Nextcloud Desktop version 3.2.2.

**Comment by kaulex99** [comment]
Still in Desktop Version 3.2.3 on MacOS Big Sur 11.4

**Comment by haroldm** [comment]
For me this issue is not present anymore after upgrading DisplayLink Manager from 1.3.0 to 1.4.0.

**Comment by grizzy255** [comment]
Bug still exists in Desktop Version 3.2.4 on MacOS BigSur 11.5

**Comment by elsiehupp** [comment]
> For me this issue is not present anymore after upgrading DisplayLink Manager from 1.3.0 to 1.4.0.

This Issue covers several related Issues. Are you specifically referring to https://github.com/nextcloud/desktop/issues/2642 ? The main-desktop oversized (but not squished) icon doesn’t seem to be resolved, yet.

**Comment by haroldm** [comment]
I am referring to both the oversized and squished icon issues although I was wrong on the cause of resolution.

When I start Nextcloud with the lid closed and at least one external monitor (DisplayLink, HDMI or a combination of both), both issues are not present anymore. The menubar icon stays the correct size even when undocking the laptop.
For reference I use a M1 Macbook and Nextcloud 3.1.3. I hope I provided enough details to help other people.

**Comment by b-a0** [comment]
> For me this issue is not present anymore after upgrading DisplayLink Manager from 1.3.0 to 1.4.0.

Unfortunately the newer DisplayLink drivers (1.3+) have some issue with clamshell mode and Intel Macs, so I cannot upgrade.

**Comment by luc-ass** [comment]
The error persists in 3.3.6...
<img width="146" alt="Bildschirmfoto 2021-11-02 um 08 51 42" src="https://user-images.githubusercontent.com/3263257/139806728-642d9a1b-03ef-4264-ac77-7d420c90b5f0.png">
Strangely I could swear, that it was much smaller and very crisp for a brief moment during fresh installation, but became larger as soon as I was logged in.

**Comment by christian-fries** [comment]
This is fixed in version 3.4.0 (tested with macOS Monterey, Intel)

**Comment by elsiehupp** [comment]
I can confirm it seems to be somewhat fixed for me in 3.4.1 on 11.6.1:

<img width="816" alt="size comparison annotated" src="https://user-images.githubusercontent.com/9206310/147473573-d942cd40-1a0c-432b-8627-42092f2c8e90.png">

It’s “fixed” in that it isn’t comedically oversized anymore, but it still doesn’t look ideal. I’ve shown it next to two first-party status indicator icons for comparison (as did @luc-ass).

Zooming in, the first-party icons are 26px x 26px, while the Nextcloud icon is 32px x 32px, and the first-party icons are aligned with 12px above and 10px below, while the Nextcloud icon is aligned with 8px above and 8px below.

At this point, probably what would need to be done to fix the icon is modifying the icon assets so that they use the same margins as the first-party assets rather than having zero margins within a 32px canvas.

> Also, yay, this has been today’s example of actually putting my architecture degree to use! 📐

**Comment by elsiehupp** [comment]
That is, this is “fixed”, in that the Qt bug stretching or squishing the icon seems to have been fixed, but the titular issue ([**Menu Bar Icon Looks Wonky on macOS Big Sur**](https://github.com/nextcloud/desktop/issues/2584)) hasn’t quite been fixed, in that the icon assets look out of place, and the fix for the Qt bug still hasn’t fixed the vertical alignment. (I’m not 100% sure about this, but I think Apple did change sizes of its first-party menu bar icons with Big Sur, so the Nextcloud icon assets that now look too large may well have been perfectly fine on earlier versions of macOS.)

**Comment by claucambra** [comment]
Hi @elsiehupp, I would consider this issue fixed

You are correct that the icon sizing is different to the system status tray icons -- unfortunately I also think this is by design on the system. Compare the NC client icon to other application icons:

![Screenshot 2022-06-09 at 12 10 12](https://user-images.githubusercontent.com/70155116/172823097-b05cccf1-cd0c-41a4-8158-80ae50374884.png)

They are all sized the same, but still larger than the system icons.

Therefore will close. Thanks all for reporting!
