### ISSUE TITLE
Since enabling end2end encryption on NC - Desktop Sync Agents are no longer syncing (on several Desktop clients Windows 10)

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/desktop#2593]
### Steps to reproduce
Since enabling end2end encryption Desktop Sync Agents are no longer syncing (on several Desktop clients Windows 10)
Everytime when the Desktop Agent is trying to sync

Restart Agent agent shortly will bring sync to "green" .. one/two minutes later agent tries to resync and this resync will hung completely.

Only one Folder for testing purposes, was encrypted since.

### Expected behaviour
Syncing should work

### Actual behaviour
Sync does not work anymore.

Also restarting the Agent, does not help, nor force restart.

## Server configuration detail

**Operating system:** Linux 4.18.0-193.19.1.el8_2.x86_64 nextcloud/end_to_end_encryption#1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.4.11
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, imagick, msgpack, smbclient, zip, memcached, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

Update from 19.0.3

**Where did you install Nextcloud from:** Nextcloud source

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.1
 - analytics: 2.5.0
 - announcementcenter: 3.8.1
 - apporder: 0.11.0
 - audioplayer: 2.12.0
 - audioplayer_editor: 0.3.0
 - audioplayer_sonos: 1.2.0
 - bookmarks: 3.4.4
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - circles: 0.19.7
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.4.1
 - contactsinteraction: 1.0.0
 - cookbook: 0.7.6
 - cospend: 1.0.5
 - data_request: 1.6.0
 - dav: 1.15.0
 - deck: 1.1.2
 - dicomviewer: 1.2.2
 - documentserver_community: 0.1.8
 - drawio: 0.9.7
 - end_to_end_encryption: 1.5.2
 - event_update_notification: 1.0.2
 - extract: 1.2.4
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_3d: 0.3.2
 - files_antivirus: 3.0.0
 - files_automatedtagging: 1.9.0
 - files_downloadactivity: 1.8.0
 - files_markdown: 2.3.1
 - files_mindmap: 0.0.23
 - files_pdfviewer: 1.8.0
 - files_photospheres: 1.19.1
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - flowupload: 1.0.0
 - forms: 2.0.4
 - gpxedit: 0.0.13
 - gpxmotion: 0.0.11
 - gpxpod: 4.2.2
 - groupfolders: 7.1.0
 - impersonate: 1.6.1
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 6.1.0
 - passman: 2.3.6
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.5.4
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quicknotes: 0.6.1
 - quota_warning: 1.8.0
 - rainloop: 7.0.3
 - ransomware_protection: 1.7.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 9.0.4
 - support: 1.2.1
 - suspicious_login: 3.2.1
 - systemtags: 1.9.0
 - tasks: 0.13.5
 - terms_of_service: 1.5.2
 - text: 3.0.1
 - theming: 1.10.0
 - timemanager: 0.1.4
 - twofactor_backupcodes: 1.8.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.9.0
 - video_converter: 0.1.5
 - viewer: 1.3.0
 - workflow_ocr: 1.19.1
 - workflow_pdf_converter: 1.4.0
 - workflow_script: 1.4.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - breezedark
 - dashboard
 - drop_account
 - encryption
 - external
 - files_accesscontrol
 - files_external
 - files_fulltextsearch
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - joplin
 - jsloader
 - passwords
 - registration
 - richdocuments
 - socialsharing_googleplus
 - survey_client
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": EMOVED SENSITIVE VALUE*,
        "dbindex": EMOVED SENSITIVE VALUE*,
        "timeout": EMOVED SENSITIVE VALUE*,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        ".REMOVED SENSITIVE VALUE*.",
        "REMOVED SENSITIVE VALUE*."
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/www.swiss7cloud.ch",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "REMOVED SENSITIVE VALUE",
    "dbtype": "mysql",
    "version": "19.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "REMOVED SENSITIVE VALUE",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "REMOVED SENSITIVE VALUE",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "REMOVED SENSITIVE VALUE",
    "session_lifetime": 1200,
    "session_keepalive": false,
    "logtimezone": "REMOVED SENSITIVE VALUE\/REMOVED SENSITIVE VALUE",
    "logfile": "\/media\/log\/nextcloud.log",
    "knowledgebaseenabled": false,
    "log_rotate_size": REMOVED SENSITIVE VALUE,
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "passman",
        "dicomviewer",
        "radio"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

Sync Agent version: 3.0.2

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36 Edg/86.0.622.43

**Operating system:** W10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by er-vin** [comment]
Do you experience spikes in the server consumption? There's a problem about the e2e server app that gets the server consumption to go crazy when there's a large amount of files, which leads to timeouts sent back to the client hence why the client stops syncing.

If that's the case we got a tentative workaround for this shipped with 3.0.3 later this week.

If that's not the case it might be something else in which case I'd like to get debug logs of the client during a sync to see where it gets stuck.

**Comment by Githopp192** [comment]
Hey Kevin .. i do not think so, i tried the e2ee with my User .. (not so much files) .. and with only 258 Files (*.jpg Files).
After copying/syncing/encrypting 13 Files .. the whole get stuck .. 
i'm using a Intel Xeon E-2136 @ 3.30GHz | average CPU mark : 13,506
For the VM i'm using four vCPUS, Total memory: 8GB .. the VM itself gots never a spike - average load between 0 and 20%.

You can better decide, if this issue is resolved by the workaround (3.0.3) or there is another issue.

I did saved all the NC Logs .. if you would to check them .. or we could be repeat the case (but this is a productive system .. hm .. better test it on a test VM) ..

**Comment by er-vin** [comment]
No that looks like something else. Note that I'm more interested in the client logs than the server logs though. For such a case server logs might not help much.

**Comment by Githopp192** [comment]
ok Kevin .. which client logs you're looking for ?

**Comment by er-vin** [comment]
I'm referring to client debug logs, this can be achieved by adding the following in the nextcloud.cfg General group:
logDebug=true
logExpire=24
logDir=C:/nextcloud-logs

Also make sure C:\nextcloud-logs exists before launching the client. After launching, log files should appear in that folder, that's the files I'm interested in.

**Comment by NewRedsquare** [comment]
I didn't want to open another issue for a similar problem, but in my case the e2ee syncing works very slowly (it takes two minutes to check for changes in remote folders), and syncing also takes minutes.

It works, but very **slowly**.

I have debug logs from Desktop app on Win10, i tried to delete sensitive content like domain, username but i don't know if there's some other sensitive informations to delete, or i can send them in a non-public way ?

**Comment by Githopp192** [comment]
Thanks NewRedsquare for delivering the logs .. i would need more time for this, because - i do not want to repeat to enable e2ee on my productive system - not that users will be affected probably.

I need to build this up from scratch on my virtual environment (like VirtualBox).

On the other hand Kevin, was this not also deeply tested in one of your NC environments (performance .. sql behave and so on) ? or is this client specific ?

**Comment by er-vin** [comment]
> I didn't want to open another issue for a similar problem, but in my case the e2ee downloading task works very slowly (it takes minutes to check for changes in remote folders).
> 
> It works for **downloading** data, but very **slowly**.
> 
> I tried to **upload** around 10 MB of data from my computer to the encrypted folder, and it's completely stuck
> ![stuck-sync png](https://user-images.githubusercontent.com/38375491/97777365-9debf480-1b67-11eb-92b5-25b6f4e948ab.jpg)
> 
> I like this e2ee feature, i really want it to be working +1
> 
> Here are the client desktop logs :
> 
> [20201030_2137_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468922/20201030_2137_owncloud.log.0.txt)
> [20201030_2137_owncloud.log.1.txt](https://github.com/nextcloud/desktop/files/5468923/20201030_2137_owncloud.log.1.txt)
> [20201030_2138_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468924/20201030_2138_owncloud.log.0.txt)
> [20201031_1146_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468925/20201031_1146_owncloud.log.0.txt)
> [20201031_1147_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468926/20201031_1147_owncloud.log.0.txt)
> [20201031_1148_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468927/20201031_1148_owncloud.log.0.txt)
> [20201031_1152_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468928/20201031_1152_owncloud.log.0.txt)

Thanks for that, such logs are often what we miss to make progress on those. In your case it's blocked due to this:
`2020-10-31 11:48:45:843 [ warning nextcloud.sync.networkjob ]: QNetworkReply::ContentAccessDenied "Le serveur a répondu \"403 Forbidden\"  à \"POST https://***HIDDEN VALUE***/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/146663?format=json\"" QVariant(int, 403)`

Then it tries again at 2020-10-31 11:53:03:013 with the same result.

The server is replying that the folder is already locked (there's a lock mechanism on the encrypted folders, it's part of the protocol, we have to lock/modify/unlock). That said in the logs you provided I don't see any other lock attempt so it doesn't feel like the client deadlocked itself.

Do you see anything in the server logs around the same time which would tell us why there is a stale lock? Would you happen to have another client holding the lock somehow? (shouldn't hold it forever of course but I'm thinking aloud here)

**Comment by er-vin** [comment]
> On the other hand Kevin, was this not also deeply tested in one of your NC environments (performance .. sql behave and so on) ? or is this client specific ?

Well, we knew that the performance on the client side could be better. There are a couple of bottlenecks coming from the existing architecture (this code base is fairly old compared to other clients) which we can't solve yet (mainly because some other pieces are not in the right place yet + manpower). So it's expected to be slower than it could be while uploading encrypted files.

As for the SQL going mad on the server side (I guess this is what you were referring to) which should be fixed by 3.0.3, this didn't show up in our tests. I suspect there was a threshold effect somewhere at an amount of file larger than what we got in our tests.

**Comment by NewRedsquare** [comment]
> 
> 
> > I didn't want to open another issue for a similar problem, but in my case the e2ee downloading task works very slowly (it takes minutes to check for changes in remote folders).
> > It works for **downloading** data, but very **slowly**.
> > I tried to **upload** around 10 MB of data from my computer to the encrypted folder, and it's completely stuck
> > ![stuck-sync png](https://user-images.githubusercontent.com/38375491/97777365-9debf480-1b67-11eb-92b5-25b6f4e948ab.jpg)
> > I like this e2ee feature, i really want it to be working +1
> > Here are the client desktop logs :
> > [20201030_2137_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468922/20201030_2137_owncloud.log.0.txt)
> > [20201030_2137_owncloud.log.1.txt](https://github.com/nextcloud/desktop/files/5468923/20201030_2137_owncloud.log.1.txt)
> > [20201030_2138_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468924/20201030_2138_owncloud.log.0.txt)
> > [20201031_1146_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468925/20201031_1146_owncloud.log.0.txt)
> > [20201031_1147_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468926/20201031_1147_owncloud.log.0.txt)
> > [20201031_1148_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468927/20201031_1148_owncloud.log.0.txt)
> > [20201031_1152_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/5468928/20201031_1152_owncloud.log.0.txt)
> 
> Thanks for that, such logs are often what we miss to make progress on those. In your case it's blocked due to this:
> `2020-10-31 11:48:45:843 [ warning nextcloud.sync.networkjob ]: QNetworkReply::ContentAccessDenied "Le serveur a répondu \"403 Forbidden\" à \"POST https://***HIDDEN VALUE***/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/146663?format=json\"" QVariant(int, 403)`
> 
> Then it tries again at 2020-10-31 11:53:03:013 with the same result.
> 
> The server is replying that the folder is already locked (there's a lock mechanism on the encrypted folders, it's part of the protocol, we have to lock/modify/unlock). That said in the logs you provided I don't see any other lock attempt so it doesn't feel like the client deadlocked itself.
> 
> Do you see anything in the server logs around the same time which would tell us why there is a stale lock? Would you happen to have another client holding the lock somehow? (shouldn't hold it forever of course but I'm thinking aloud here)

I don't have access to server logs, my nextcloud server is managed by a provider ( still have admin access to the nextcloud UI )

**Comment by er-vin** [comment]
Ah too bad... Well I guess one thing we could try is to wait 24 hours while your client would be completely shutdown. Locks from the E2EE server app are supposed to be released after 24 hours.

Then you could try again and see if the same lock shows up in the client logs, or maybe we figure through those logs how a stale lock happened in the first place.

**Comment by jktoiuhito** [comment]
I have exactly the same problem as [NewRedsquare](https://github.com/nextcloud/desktop/issues/2593#issuecomment-719794269), and in my case as well [it seems to be related to the E2EE app not allowing the client to lock a folder](https://gist.github.com/jktoiuhito/e3c0a03fa13c971c187af3892fe264f0).

Uploading and syncing to a just created end-to-end encrypted folder worked fine, but after restarting my machine sync is stuck displaying the "0 seconds remaining" message [posted above](https://github.com/nextcloud/desktop/issues/2593#issuecomment-719794269).

Absolutely nothing on server log at `/var/www/nextcloud/data/nextcloud.log`. I wonder if the E2EE-app has its own log-file somewhere?

Server version: 20.0.1.1
Client version: 3.0.3 (Windows)

**Comment by jktoiuhito** [comment]
Solved the issue by manually deleting E2EE-apps locks from the database with [`DELETE FROM oc_e2e_encryption_lock`](https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590#Server).

Main cause of the problem seems to be that somehow the E2EE-apps locks aren't removed/released properly. I think that a cron-task which would remove all of the locks periodically might work as a temporary fix.

Other things I tried:

-  Restarting the app -> no effect (expected, as the problem seems to be on the server side)
-  Restarting the server machine / apache -> no effect, apparently locks persist on disk
-  Cleaning up file locks from db with [`DELETE FROM oc_file_locks WHERE 1`](https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883) -> no effect, since E2EE-apps locks are stored in a different place.

**Comment by er-vin** [comment]
> Main cause of the problem seems to be that somehow the E2EE-apps locks aren't removed/released properly. I think that a cron-task which would remove all of the locks periodically might work as a temporary fix.

Note that they're supposed to expire after 24h though.

**Comment by kruthoff** [comment]
[nx-client-3.0.3.log](https://github.com/nextcloud/desktop/files/5487727/nx-client-3.0.3.log)
All right I'll stick to this issue. My sync stops as well, but so far I didn't see 403 Forbidden. I'm running into timeout issues on the other hand, if E2E is enabled (see attached log).

**Comment by jktoiuhito** [comment]
Gathered up some more information related to the locking-related sync-stuck-permanently issue.

[This part of the E2EE-app](https://github.com/nextcloud/end_to_end_encryption/blob/d3471e160fe0ffdd540afeb27b9c9ea4915bffbb/lib/Connector/Sabre/LockPlugin.php#L166) returns (throws?) a HTTP `403` error with the log entry "Write access to end-to-end encrypted folder requires token -no token sent" if no token is sent by the client.

Related issues from the [E2EE-app repository](https://github.com/nextcloud/end_to_end_encryption/):

-  [#197 stuck with an encrypted folder](https://github.com/nextcloud/end_to_end_encryption/issues/197)
    - 403 error on windows client, "server unavailable" on android client, "Write access to end-to-end encrypted folder requires token -no token sent" on server log.
     - I have personally experienced these errors on both clients.
-  [#9 Lock file API](https://github.com/nextcloud/end_to_end_encryption/issues/9)
    - 403 error on client if no token is sent.
    - *"if you lose the token you are lost. That's the responsibility of the client. The server can't free the the lock because the server don't know if the client has finished it's operation and whether the files are in a useful and consistent state or not [...]. The client need to make sure that it frees every lock after a operation was completed."*

Related issues from the [desktop repository](https://github.com/nextcloud/desktop/):

-  [#2314 Desktop stops syncing after deleting/renaming a file inside encrypted folder](https://github.com/nextcloud/desktop/issues/2314)
    - 403 error on windows (and linux?) client, "Write access to end-to-end encrypted folder requires token -no token sent" on server log.
-  [#1822 Windows Client cannot upload more than 1 encrypted (E2E) file otherwise stucks forever](https://github.com/nextcloud/desktop/issues/1822)
    - 403 error on windows client.
  
I have certainly seen the "Write access to end-to-end encrypted folder requires token - no token sent" error in the server logs many times before, but for some reason there is nothing in the logs from the time I took the [log I linked above](https://gist.github.com/jktoiuhito/e3c0a03fa13c971c187af3892fe264f0)...

Anyway, seems to be an issue related to tokens not being sent properly?

**Comment by jktoiuhito** [comment]
Updated the summary above with some additional related issues. Hopefully it could be useful.

After manually deleting the E2EE-apps locks I haven't had any issues with syncing to encrypted folders, but I increased the servers logging level to DEBUG in hopes of possibly catching something in the future.

I don't have any C++ experience, but might dig in to the desktop clients source code to see if I could find anything strange with the token handling. Doing side-to-side comparison with the mobile clients token handling might be useful, as they don't seem to have any related issues.

**Comment by er-vin** [comment]
Thanks for your efforts, you might want to enable logs on the client as well then. In the General group of your nextcloud.cfg I'd advise adding something like the following:
logDebug=true
logExpire=24
logDir=C:/nextcloud-desktop-logs

I'll let you adjust the logExpire, it's in hours so obviously the bigger the better since it looks like there's some time between those stale locks being created and the client actually getting stuck on one of those. But the bigger the most disk space consumed by the logs (in my tests we're around 100MB/day).

Note that what I'm proposing here will be the new defaults for 3.1.0 (+ a button to harvest it all in a zip file) to help everyone chase this kind of stuff.

**Comment by mpranj** [comment]
I've had similar issues. NC desktop 3.0.3 showed "Waiting ..." forever on my clients (Linux, macOS). The problem appeared when upgrading frmo 19.0.4 to 20.0.1.

Disabling end2end encryption server-side mitigated the problem for me, but this is obviously suboptimal... 

Note: running `DELETE FROM oc_e2e_encryption_lock;` did not help, the table was already empty for me. I really had to remove the e2ee plugin.

**Comment by kruthoff** [comment]
> Note: running `DELETE FROM oc_e2e_encryption_lock;` did not help, the table was already empty for me. I really had to remove the e2ee plugin.

@mpranj Did you see 'Connection timed out' messages in you client log? I'm just curious.

**Comment by mpranj** [comment]
It appears once in the logs, yes.

But this appears >3000 times:

```
2020-11-03 13:34:29:274 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
```

and this appears >6000 times:

```
[ info nextcloud.sync.networkjob ]:	OCC::GetFolderEncryptStatusJob created for "https://example.com" + "remote.php/webdav" "OCC::ClientSideEncryption"
```

Server-side there was no high load or anything suspicious to my knowledge.

**Comment by NewRedsquare** [comment]
Someone has another logs to provide ? I had to disable e2ee, didn't want to lose work's files :/

**Comment by WhiteBahamut** [comment]
it is the same for me, logs provided in https://github.com/nextcloud/desktop/issues/2314. Nothing changed. NC server now 20.0.2, client 3.1.x (trying daily as well)

**Comment by er-vin** [comment]
Yes, trying to get some help from the server side and they've been busy so far. We'll need some adjustments to get this to rest and I can't solve this until this happens.

**Comment by hdlineage** [comment]
I have the same issue.
As soon as I try to sync the encrypted folder on the desktop client, the sync process stuck. 
When I untick the encrypted folder, the sync completed without problem and icon turned green.
I am on the stable Nextcloud 19 and windows client 3.x

**Comment by Taomyn** [comment]
Same issue here, have 3,1.0 clients and NC 20.0.4 running on Fedora 32 and all clients just sit there waiting.

**Comment by bcutter** [comment]
Very frustrating. Is someone working on it? There were logs provided. What else can we do?

**Comment by er-vin** [comment]
Well yes I do. I'd expect this fixed with 3.2 not before. For those on Linux I'm interested in someone testing the AppImage from #2700 and letting us know how this goes. This should hopefully fix the "server meltdown" case with E2EE. I don't expect it fixes the lock problem on some of the E2EE folder deletion we've been seeing (reported in another ticket) but that part is likely to be tackled during the 3.2 cycle as well.

**Comment by wiknor** [comment]
#2700 works well on Ubuntu LTS 20.04. No issues noticed so far.

**Comment by hdlineage** [comment]
> Well yes I do. I'd expect this fixed with 3.2 not before. For those on Linux I'm interested in someone testing the AppImage from #2700 and letting us know how this goes (obviously warning ensue: it might kill puppies). This should hopefully fix the "server meltdown" case with E2EE. I don't expect it fixes the lock problem on some of the E2EE folder deletion we've been seeing (reported in another ticket) but that part is likely to be tackled during the 3.2 cycle as well.

Do we know when 3.2 is going to be officially released?

**Comment by er-vin** [comment]
> > Well yes I do. I'd expect this fixed with 3.2 not before. For those on Linux I'm interested in someone testing the AppImage from #2700 and letting us know how this goes (obviously warning ensue: it might kill puppies). This should hopefully fix the "server meltdown" case with E2EE. I don't expect it fixes the lock problem on some of the E2EE folder deletion we've been seeing (reported in another ticket) but that part is likely to be tackled during the 3.2 cycle as well.
> 
> Do we know when 3.2 is going to be officially released?

It is aimed for end of March. This contains major changes to the engine so it'll need quite some QA time before we're confident releasing it in the wild.

**Comment by bcutter** [comment]
Thanks for the timetable.

Even that means 3 more months of server pain OR not being able zu use E2EE at all.

That would be 7 months after promoting it as "production ready" https://nextcloud.com/press/pr20200818/ ... anyway, at least there's light at the end of the tunnel.

**Comment by jonathanmmm** [comment]
Thanks for knowing that it till come in March, but still a long time.
What is the best way to disable e2ee encryption in the meantime?
I have one account that encrypts only one folder what is the best way to not loose data. What would happen to this folder if I deactivate e2ee? Would it get synced in plaintext again? Should I put this folder outside of nextcloud? I want to make Nextcloud usable for all other accounts until this is fixed (would downloading a client version before 3.x help if I don't need e2ee on these clients? Like 2.3.0.3, I believe this version was very stable)

Hope you can help us to have some manual/plan what to do in the meantime what is best to use the rest of the clients without e2ee.

Blessed Christmas by the way🎄

**Comment by MegaV0lt** [comment]
A shame that this feature was published without testing

**Comment by cupcakearmy** [comment]
Same here on macOS (3.1.1 Client & 20.0.4 Server)
How is this marketet as production ready 🙈
March is an awefull long time. But well at least it's on track to being fixed

**Comment by bcutter** [comment]
> 
> 
> How is this marketet as production ready 🙈
No idea, I´m sure the responsible persons involved feel ashamed and learned from it.

Much more important than looking back is looking ahead. While waiting for some march magic to happen I only see two options:
1) don´t use E2EE
2) use E2EE and live with awful long sync times and increased server load

Both are only bad options but at least there´s a choice 😂

**Comment by cupcakearmy** [comment]
@bcutter I was not bashing the team, just wondering 🙂
I've disabled E2EE for now

**Comment by jonathanmmm** [comment]
I would be glad to just disable E2EE encryption, but I don't know what happens with the E2EE folder that is already synced? Does the client recognizes that the server disabled it and just does not sync the folder or does the folder gets synced in plaintext (probably not, would be a security weakness)? Hope somebody can clarify how disabling for the meantime should be procedured and if anything could wrong with just disabling it.

**Comment by cupcakearmy** [comment]
@jonathanmmm I can't tell you that unfortunately. I just installed it (E2EE) and was fiddling around with it.

**Comment by evdcush** [comment]
Experiencing same issue on Ubuntu 20.04 3.1.1.

How do we disable E2EE? I cannot find an option for it anywhere in the GUI settings.

**Comment by bcutter** [comment]
You need to disable it on the server side by disabling the app.

**Comment by flrns** [comment]
> Well yes I do. I'd expect this fixed with 3.2 not before. For those on Linux I'm interested in someone testing the AppImage from #2700 and letting us know how this goes (obviously warning ensue: it might kill puppies). This should hopefully fix the "server meltdown" case with E2EE. I don't expect it fixes the lock problem on some of the E2EE folder deletion we've been seeing (reported in another ticket) but that part is likely to be tackled during the 3.2 cycle as well.

I'm using the AppImage from #2781 now (this should include the #2700 commits, right?) and it works so far - but still sync gets stuck with e2e encryption enabled.
Removing the encryption-locks in the DB helped to continue the sync once, but now there aren't any locks and after copying new files into the local Nextcloud folder, sync starts but quickly gets stuck again (after some few bytes according to the status bar, possibly after syncing one or two small files or so).
The logs don't seem to show anything of interest, but I am happy to share them if it helps you debug the issue.

Nextcloud Server version is 20.0.4 and E2E-App version on the server is 1.6.2.

**Comment by er-vin** [comment]
> I'm using the AppImage from #2781 now (this should include the #2700 commits, right?) and it works so far - but still sync gets stuck with e2e encryption enabled.
> Removing the encryption-locks in the DB helped to continue the sync once, but now there aren't any locks and after copying new files into the local Nextcloud folder, sync starts but quickly gets stuck again (after some few bytes according to the status bar, possibly after syncing one or two small files or so).
> The logs don't seem to show anything of interest, but I am happy to share them if it helps you debug the issue.

OK, could you use the "Create Debug Archive" button in the settings dialog and drop us the zip file in that file drop?
https://cloud.nextcloud.com/s/7ZSqepBdwCgwnkA

Please make sure the filename allows us to figure out for which issue this is and which user. Otherwise it might get lost in the other uploads we get.

**Comment by evdcush** [comment]
> You need to disable it on the server side by disabling the app.

@bcutter what if you are a user using free nextcloud hosting from a provider? I don't see anything either in the desktop app or the online app where I can disable encryption.

**Comment by bcutter** [comment]
Then... I'm out. Maybe just remove your E2EE files (copy them outside Nextcloud in a safe place) and delete the E2E encrypted folder(s), that's it. More comfort (turning it off, wait two more months, turn it back on and boom kickstart from where you stopped today) only when being able to disable the app on the server.

That's just my 2 cents. Maybe there are other ways like remove seed from desktop clients or sth. like that.

**Comment by PhilLab** [comment]
We are having the same issue with the win10 desktop client. Synchronization works fine when the e2ee application is enabled but no encrypted file is yet placed into an e2ee folder. After the first file is put in there and uploaded, synchronization stops working for **all users of the same server**, irregardless of them having any file encrypted themselves.

Disabling the application and restarting the clients resolves the problem, but you obviously cannot access the e2ee files anymore. When I briefly enabled the app again, I could access the files again - but don't take this for granted, I certainly will not.

**Comment by jonathanmmm** [comment]
> Then... I'm out. Maybe just remove your E2EE files (copy them outside Nextcloud in a safe place) and delete the E2E encrypted folder(s), that's it. More comfort (turning it off, wait two more months, turn it back on and boom kickstart from where you stopped today) only when being able to disable the app on the server.
> 
> That's just my 2 cents. Maybe there are other ways like remove seed from desktop clients or sth. like that.

Could you explain again what you think is the best way in steps?
What to do on client with E2EE folder?

I thought maybe this way:
1.) Get all Files outside the E2EE folder and delete it. Look as the user at the web UI to see if the folder got deleted (maybe it won't get deleted as sync does not work?!)
2.) Do step 1 for every user that has E2EE folders
3.) Disable E2EE and wait until March or so

For me this would be fine, as I only have one client that uses it.

Would this be the right way or can I just disable E2EE App on Server and the E2EE folder on clients just don't get synced and the rest just normally.
E2EE folders should not be uploaded in plaintext, when Server disables the App, as it would be a real security risk (an attacker could that way, when having access to the server get all E2EE files).

**Comment by er-vin** [comment]
If someone could try again with latest daily it would be welcome.

**Comment by flrns** [comment]
Looks like they issue I had is fixed with the latest daily. Sync in progress, hasn't stopped so far.
Thanks a lot for working on this!! :heart:

**Comment by flrns** [comment]
Okay, one thing I noticed is that (when syncing some Gigabytes of data) I get lots of files, most of them empty, in /tmp/ (which is mounted to RAM and eventually ran out of space in my setup..). I guess this comes from decryption.

Can these temporary files be cleaned up regularly during decryption (or are they, and this is just because I have big encrypted folders)?
If not, is there an option to set the temp-dir for Nextcloud to something where I have more free space?

**Comment by er-vin** [comment]
> Okay, one thing I noticed is that (when syncing some Gigabytes of data) I get lots of files, most of them empty, in /tmp/ (which is mounted to RAM and eventually ran out of space in my setup..). I guess this comes from decryption.

Yes, indeed those will go through the temp directory.
 
> Can these temporary files be cleaned up regularly during decryption (or are they, and this is just because I have big encrypted folders)?

I'll look into this. There might be a chance of a tmp file leak indeed. Could you please open a separate issue for that so it's tracked properly? Thanks in advance.

> If not, is there an option to set the temp-dir for Nextcloud to something where I have more free space?

Not really no, you could always try to play with env vars on your platform to try to make it go somewhere else? But I'm not sure there's really anything standard for that.

**Comment by er-vin** [comment]
> > Can these temporary files be cleaned up regularly during decryption (or are they, and this is just because I have big encrypted folders)?
> 
> I'll look into this. There might be a chance of a tmp file leak indeed. Could you please open a separate issue for that so it's tracked properly? Thanks in advance.

Double checked everything and there's no such leak... must be something else possibly not even related to e2ee. So please open a separate ticket and let's discuss that further there.

**Comment by er-vin** [comment]
> > > Can these temporary files be cleaned up regularly during decryption (or are they, and this is just because I have big encrypted folders)?
> > 
> > 
> > I'll look into this. There might be a chance of a tmp file leak indeed. Could you please open a separate issue for that so it's tracked properly? Thanks in advance.
> 
> Double checked everything and there's no such leak... must be something else possibly not even related to e2ee. So please open a separate ticket and let's discuss that further there.

OK, I'll contradict myself, I understood you as a leak on the download path and it's what I checked, there's no such leak. But there seems to be indeed one on the upload path.

**Comment by flrns** [comment]
Thanks for checking again. Does that mean I should not (or do not have to) report a new bug, but you'll track it here?

**Comment by LightTemplar** [comment]
@er-vin 
> If someone could try again with latest daily it would be welcome.
This problem has disappeared for me! I couldn't sync two of three my accounts, and now they work. For app updates I use ppa:nextcloud-devs/client.

**Comment by NewRedsquare** [comment]
Does this leak affect all platforms or only linux ? (as i guess with the /tmp/ path )

**Comment by er-vin** [comment]
> Thanks for checking again. Does that mean I should not (or do not have to) report a new bug, but you'll track it here?

Yes, please do open a separate issue. Otherwise we're bound to derail that one. ;-)

**Comment by bcutter** [comment]
@LightTemplar @flrns  what about server load - is it also back to normal again?

Symptoms were:
a) Sync stopped (with desktop client versions later than 3.0.2 I´m stuck at)
b) Sync takes loooooong time (with desktop client version 3.0.2 or before)
c) Sync puts high load on server (with desktop client version 3.0.2 or before)

Not confident enough to run a daily build on my productive environment...

**Comment by LightTemplar** [comment]
@bcutter 
> what about server load

I can't say for sure. Those two with sync issues aren't under my control, though I can see an overall server load of the second one: and there are not many differences between its works with my client syncing and without it. 
And on the third one, which is under my control, I don't have e2ee on, and I haven't seen any overload at all.

**Comment by kruthoff** [comment]
> If someone could try again with latest daily it would be welcome.

I'm testing Nextcloud-3.1.50.20210206-daily-x86_64.AppImage but can't get it working, unfortunately. I'm running into locked folders whatever I try. My steps are as follows:

1. enable encryption
2. create folder
3. encrypt folder
4. put a file into that folder
5. sync is locked

```
2021-02-06 12:07:28:483 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError(const QByteArray&, int)::<lambda ]:	Error locking the folder while no other update is locking it up.
2021-02-06 12:07:28:483 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError(const QByteArray&, int)::<lambda ]:	Perhaps another client locked it.
2021-02-06 12:07:28:483 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError(const QByteArray&, int)::<lambda ]:	Abort
```

**Comment by er-vin** [comment]
> > If someone could try again with latest daily it would be welcome.
> 
> I'm testing Nextcloud-3.1.50.20210206-daily-x86_64.AppImage but can't get it working, unfortunately. I'm running into locked folders whatever I try.

Just to be sure, you made sure there was no stale locks in the database before you started testing again?

**Comment by kruthoff** [comment]
NC 20.0.5, e2e 1.6.2, client 3.1.50.20210206.
Starting again from scratch.

1. delete from oc_e2e_encryption_lock; deletes 1 stale lock
2. enable encryption
3. 0 rows
4. create folder
5. 0 rows
6. encrypt folder
7. 1 row (!)
8. put a file into the e2e folder -> locked

**Comment by kruthoff** [comment]
e2e folder with id 875728. That was in the logs, maybe a hint? It can't unlock, 403.

```
2021-02-06 13:10:18:258 [ info nextcloud.sync.networkjob ]:	OCC::UnlockEncryptFolderApiJob created for "https://example.com" + "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/875728" "OCC::EncryptFolderJob"
2021-02-06 13:10:18:258 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::StoreMetaDataApiJob finished for "ocs/v2.php/apps/end_to_end_encryption/api/v1/meta-data/875728"
2021-02-06 13:10:18:663 [ warning nextcloud.sync.networkjob ]:	QNetworkReply::ContentAccessDenied "Error transferring https://example.com/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/875728 - server replied: " QVariant(int, 403)
2021-02-06 13:10:18:664 [ warning nextcloud.sync.credentials.webflow ]:	"Error transferring https://example.com/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/875728 - server replied: "
2021-02-06 13:10:18:664 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	error unlocking file "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/875728" "Error transferring https://example.com/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/875728 - server replied: " 403
2021-02-06 13:10:18:664 [ info nextcloud.sync.propagator.encryptfolder ]:	Unlocking error for "875728" HTTP code: 403
2021-02-06 13:10:18:665 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::UnlockEncryptFolderApiJob finished for "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/875728"
2021-02-06 13:11:03:323 [ info sync.discovery ]:	Processing "e2e" | valid: true/db/true | mtime: 1612613395/0/1612613398 | size: 4096/0/0 | etag: ""//"601e871652f67" | checksum: ""//"" | perm: 0x7fe54f11e158//0x56194dd72c48 | fileid: "00875728ocdjag5z8nms"//"00875728ocdjag5z8nms" | inode: 3408733/0/ | type: CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeDirectory | e2ee: true/true | e2eeMangledName: ""/""
2021-02-06 13:11:03:550 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	Requesting the metadata for the fileId "00875728ocdjag5z8nms" as encrypted
```

**Comment by bcutter** [comment]
Tried to test latest daily (`Nextcloud-3.1.50.20210207-daily-Win64-x64.msi`) but Nextcloud does not start at all.

![grafik](https://user-images.githubusercontent.com/13799156/107152432-1da80d00-6968-11eb-89fd-fb48e91ab157.png)

**Comment by bcutter** [comment]
Since NC server has been updated to 20.0.7.1 even older desktop clients (I used 3.0.2 which synced fine besides the fact syncs took a long time and server load was high for that longer sync duration) do not sync at all.

Sync progress stays at...
![grafik](https://user-images.githubusercontent.com/13799156/107152708-a07d9780-6969-11eb-82a7-f97262886794.png)
...and will never finish, while the server idles (no PHP processes active anymore).

Too bad I can´t test the daily, so now I finally need to disable E2EE too. What a pity.

**Comment by er-vin** [comment]
> Tried to test latest daily (`Nextcloud-3.1.50.20210207-daily-Win64-x64.msi`) but Nextcloud does not start at all.
> 
> ![grafik](https://user-images.githubusercontent.com/13799156/107152432-1da80d00-6968-11eb-89fd-fb48e91ab157.png)

Should be fixed in the next daily.

**Comment by bcutter** [comment]
> 
> 
> Since NC server has been updated to 20.0.7.1 even older desktop clients (I used 3.0.2 which synced fine besides the fact syncs took a long time and server load was high for that longer sync duration) do not sync at all.
> 
> Sync progress stays at...
> ![grafik](https://user-images.githubusercontent.com/13799156/107152708-a07d9780-6969-11eb-82a7-f97262886794.png)
> ...and will never finish, while the server idles (no PHP processes active anymore).
> 
> Too bad I can´t test the daily, so now I finally need to disable E2EE too. What a pity.

Update: Clearing table nc_e2e_encryption_lock resolved the issue desktop client v3.0.2 not syncing at all. Had 4 entries, oldest from October 2020... weird.

**Comment by anduz** [comment]
I've tried today to activate E2EE, but windows client 3.1.2 is not syncing, had to disable.
Table oc_e2e_encryption_lock is empty.

**Comment by jospoortvliet** [comment]
> I've tried today to activate E2EE, but windows client 3.1.2 is not syncing, had to disable.
> Table oc_e2e_encryption_lock is empty.

Please, if you can test the upcoming 3.2 release, it has a lot of E2EE fixes, including fixes for these syncing issues.
https://help.nextcloud.com/t/help-test-our-desktop-client/107344/12 for info. Would be helpful to know if the problems are fixed with that version!

**Comment by kruthoff** [comment]
A while ago, I've tested and commented this issue. I did a new try just now, with version 3.1.81 (linux), server is 20.0.8. And.......
It seems to work! Great!!

I've created a new folder. Encrypted it from the desktop client.
Put a file into the folder.
File is synced. No locking, blocking, whatever....
I put another file, more files...
They're synced. Everything is ok so far.

On the web client, the folder is accessible, but the content is encrypted. This is expected and good.

So. No high server load, no blocked desktop client sync. It looks good to me. Thanks a lot.

my 5c

**Comment by bcutter** [comment]
v3.2 isn't released yet, is it? @er-vin 

Looked in the calendar: it's March already I'm happily surprised 😀 

Nice feedback @kruthoff , sounds promising.

**Comment by WhiteBahamut** [comment]
I tried with NC21 (docker) and win client 3.1.3. Still not solved for me. 
- Enabled e2e on server
- add new folder on andorid device
- set as encrypted 
- add file to folder
- encrypted in NC web ui
- encrypted in win client
- high load on server :S

**Comment by kruthoff** [comment]
> I tried with NC21 (docker) and win client 3.1.3. Still not solved for me.
> 
That's the known bug. Please try with a development version newer than 3.1.3., if possible.

**Comment by bcutter** [comment]
> v3.2 isn't released yet, is it? @er-vin 
> 
> Looked in the calendar: it's March already I'm happily surprised 😀 
> 
> Nice feedback @kruthoff , sounds promising.

@er-vin finally it's April. With latest RC of 3.2 the stable is just around the corner right?

**Comment by carlfriedrich** [comment]
I tried 3.2.0rc3 on Windows:

- enabled e2e on server
- add new folder on android device
- set as encrypted
- add file to folder
- encrypted in NC web ui
- syncs correctly to win client
- add file to folder from win client
- syncs correctly to android app

Issue seems to be resolved on my side. Thanks everyone who took part in fixing this!

**Comment by carlfriedrich** [comment]
However, upload is quite slow. 300 files with 30 MB in total took about 10 minutes to upload from Windows client. I assume that the encryption algorithm takes that long?

**Comment by bcutter** [comment]
That's the interesting question: sync worked before (I still use it for months now), but desktop client sync took like forever (at least 6 to 10 minutes, even if only one text file has been changed) stressing the server (one PHP-FPM and database).

Therefore: Is sync time and server load also fixed?

**Comment by carlfriedrich** [comment]
For me, e2c sync started working with client 3.0 but stopped working again when I updated my server to some version (don't remember which one, sorry). So for the last client versions, syncing with e2e enabled did not work at all on my side. This is the first version, where it works again.
Thus, I do not have a reference concerning the sync time. Somebody else has to tell.

**Comment by bcutter** [comment]
Update: With `Nextcloud-3.2.0-rc3-x64.msi` (after some struggles installing - multiple reboots required, nextcloud.exe wasn´t created in the first run, needed to repair) the initial E2EE sync issue seems to be gone!

✅ Sync is instantly, no waste of several minutes anymore
✅ No excessive resource allocation on server side during sync progress anymore
✅ Syncing E2EE content still works

Finally after more than 1/2 a year my server can relax :-) Great work Nextclouders! Looking forward to the stable version of v3.2.0 desktop client.

**Comment by Githopp192** [comment]
Hi Gents and Dear Nextcloud Developpers, 

it seems, E2EE will make progress. Congrats on that.

I think, i will give it a new try, when we are on v3.2.0.

As i've got a very productive environment, i take care how and when i want to implement and test it.

So far, thanks again for your great work.

**Comment by carlfriedrich** [comment]
> Update: With `Nextcloud-3.2.0-rc3-x64.msi` (after some struggles installing - multiple reboots required, nextcloud.exe wasn´t created in the first run, needed to repair) the initial E2EE sync issue seems to be gone!

FYI: I had exactly the same issue with nextcloud.exe not being created. Had to repair install as well.

**Comment by TooManyHobbies** [comment]
I would like to test 3.2.0 as I have been having the issues described here since enabling E2EE.  My question is, can I use the Snap package for the test server install?  As of today, that will install 20.0.7 on the server.  Or does the server have to be at version 21 for tests to be valid?  I ask because I've never setup NC manually and I'm not a sys admin.  Thanks for E2EE, it is a huge part of my work flow.

**Comment by Githopp192** [comment]
Ok ... just wanny try NC Agent 3.2 (Windows 10).
Some days ago i did the Upgrade to NC 21.0.1. 

And what a surprise .. i can't really understand, why important (=Featured) Core Apps are not supported in new NC Versions ?

![ScreenShot1390](https://user-images.githubusercontent.com/32612067/115079481-862fdf00-9f01-11eb-8ef1-95a6e64725d3.jpg)

What is the expectation from Nextcloud ? Is the expectation/requirement, that before each Upgrade one should check, if all the Apps are supported in the new version ? - ok .. should be be fine for the NONE-Featured Apps .. but not for the Featured Apps, especially when it's one of the core core Apps.

**Comment by bcutter** [comment]
Have a look at https://github.com/nextcloud/end_to_end_encryption/issues/224

It's working with some tweaking and twerking. But yeah, should work out of the box. E2EE still is not part of the core team, even it's promoted like it would. And yes that's the expectation... :-( I completely get your frustration.

**Comment by szaimen** [comment]
> What is the expectation from Nextcloud ? Is the expectation/requirement, that before each Upgrade one should check, if all the Apps are supported in the new version ?

Yes, that's excactly what you should do before installing any new major Nextcloud version. 👍

**Comment by Githopp192** [comment]
Thanks Simon for the comment :-)

yes exactly ... for the not so important apps - I generally overlook this. But I am almost sure that E2EE was not there (in the "no update" list).

I do the updates via CLI - I think - I have never seen a similar message there (that would be possibly a CLI improvement !?).

Usually I always wait for the minor - releases (x.2 or 3) for big updates. Previously, it was common with Nextcloud that you could still choose "Production" and there was the upgrade only suggested when the next major release - I think - was on version x.2.

I have brought forward this upgrade only because there was a forced power interruption in our Datacenter and I wanted to use the situation to make the major upgrade.

On the other hand @caugner did open a case about the same concer/issue i had, too - about -->
(it remains to mention that the release 20.0.9 was skipped, although announced via GUI )!? from -->
https://github.com/nextcloud/server/issues/26573).

### Two questions arise here:

1. was/is the intended - that Nextcloud does an automatic upgrade from 20.0.6 to 21.0.1 - or is this a bug in the upgrade - procedure.

2. admins should be given the possibility to upgrade to any next version in the CLI (or GUI).

I know about the possibility to upgrade manually - but it would be better here - to offer the admin several update options (automated), with an included official recommendation from Nextcloud.

On the other hand, I sometimes wonder - when I see the many issues - especially now with version 21.x, if the stable versions are really to be considered as "stable".

(Simon - btw - i saw your great NAS-Guide .. a very good work - thanks, that you help others to build their own NAS environment).

**Comment by WhiteBahamut** [comment]
E2EE works on my NC21 instance and with the latests (3.2) clients Win and Linux were able to sync again. I am running NC as container and use the offical image. It still does not have the php version upgrade.
BUT E2EE will not work with VFS.

**Comment by Githopp192** [comment]
thanks @WhiteBahamut for the hint. Fortunately i'm still not in productive use. Only wanted to test E2EE again :-)
In your case, i think you already had E2EE installed (as NC App) - when you did the Upgrade.

**Comment by WhiteBahamut** [comment]
Yeha, it was installed and disabled after the upgrade 20->21. I just enabled it to see what happens.

**Comment by szaimen** [comment]
> btw - i saw your great NAS-Guide .. a very good work - thanks, that you help others to build their own NAS environment

Thanks for the feedback! Appreciate it :)

**Comment by adimol** [comment]
Sadly, after giving Nextcloud e2ee another try, since #1269 was fixed, I am still encountering syncing issues with the latest desktop client, e2ee module and NC 21.

Particularly, I get "Server replied 423 Locked... Write access to e2ee folder requires token". Then sync-ing on the desktop client freezes with no progress, despite restarting the sync.

I might have caused this locking issue by purposely accessing / modifying the encrypted folder from an Android device, while the upload sync was still happening on the desktop (macOs). However, it should not deadlock like this...

**Comment by hdlineage** [comment]
> c

latest desktop client still haven't fixed the issue. You need to install the latest release candidate.

**Comment by adimol** [comment]
@hdlineage , thank you for the reply. Could you confirm which release candidate that is? I checked the release page, and it would appear that 3.2.0 is the very latest package, which I assume is the same package provided on the official nextcloud download page.

**Comment by hdlineage** [comment]
@adimol nvm I was mistaken. I just checked, the latest client is indeed 3.2.0 which should include the fix. Could be a different issue on your end.

**Comment by kruthoff** [comment]
On March 18, everything was ok with E2EE for me, yeah! Desktop client version 3.2.0 was finally working as expected.

But things changed, unfortunately. I've upgraded to NC 21 and to client 3.2.1 in the mean time. And I can't create folders in an encrypted folder anymore. Stale locks remain in the NC database. Nextcloud log says such things as "Write access to end-to-end encrypted folder requires token - no token sent". The client is locked. Oh no, what happened?

I've downgraded to 3.2.0 which works. This is a workaround for me, at least.

**Comment by FlexW** [comment]
@kruthoff That sounds like a new issue. Could you open a new issue for that one, so we can keep track of it?

**Comment by kruthoff** [comment]
I was already preparing a new Issue as client V3.2.2 came out... which... worked! Synchronization takes very very very long (it runs really slowly), but it's stable. That's good.

**Comment by irdet2** [comment]
@kruthoff : What delays do you see? I was thinking to update but ....

**Comment by kruthoff** [comment]
> @kruthoff : What delays do you see? I was thinking to update but ....

I just observed that it uploads one file every few seconds. Hundred files take a long time, much much longer than unencrypted files which are uploaded in a few seconds. But it works. This issue can be closed in my opinion.

**Comment by Githopp192** [comment]
btw .. yesterday i did the upgrade to V3.2.2 from one of my client (they have also DLL's into their folders).
Now .. cloud is reporting thousands of "

Warning | ransomware_protection | Prevented upload of DoIt/bdeui.dll because it matches extension pattern ".dll"

i never saw this message about DLLs and i did not update the ranswomware app previously !?

**Comment by derykl** [comment]
This seems to be what I'm getting, so not sure if it's closed prematurely.

As I'm on a hosted server (Hetzner) I don't have direct SQL access so can't delete the locks that way - any suggestions?

**Comment by JoshBrownNeuro** [comment]
Bumping this, because the bug still exists as of windows client v3.6.0 and nextcloud 24.0.5 (Ubuntu 22.04). Basically I had the same issue as below, and same solution. The problem seems to happen when the sync is interrupted, and the client and/or server can't clean up the locks.

> Solved the issue by manually deleting E2EE-apps locks from the database with [`DELETE FROM oc_e2e_encryption_lock`](https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590#Server).
> 
> Main cause of the problem seems to be that somehow the E2EE-apps locks aren't removed/released properly. I think that a cron-task which would remove all of the locks periodically might work as a temporary fix.
> 
> Other things I tried:
> 
>     * Restarting the app -> no effect (expected, as the problem seems to be on the server side)
> 
>     * Restarting the server machine / apache -> no effect, apparently locks persist on disk
> 
>     * Cleaning up file locks from db with [`DELETE FROM oc_file_locks WHERE 1`](https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883) -> no effect, since E2EE-apps locks are stored in a different place.

**Comment by personinthedunes** [comment]
I have the same problem as @derykl ... Hetzner Webhost, same error...
