### ISSUE TITLE
Nextcloud client 3.1 syncs "ignored files"

### ISSUE THREAD

**Issue by libeanim** [nextcloud/desktop#2728]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud client should ignore files and folders that have been added to the "Ignored Files" list through the UI.

### Actual behaviour
Nextcloud client syncs folders that are in the "ignored files" list since the update to 3.1.  
I've experienced this bug on "folder sync-connection"-level (see "Steps to reproduce" if unclear), it is also possible that it happens when using the global ignore file.

### Steps to reproduce
1. Add a new 'Folder Sync Connection'
2. Click on the three dots on the settings window next to the newly added "folder sync connection" and select "Edit Ignored Files" from the dropdown menu.
3. Add a folder you want nextcloud to ignore
4. Start sync and create a folder that is in the ignored list
5. Watch nextcloud client sync this folder

### Client configuration
Client version: 3.1.0-20201214.180315.7f4ffd0f7-1.0~focal1

Using Qt 5.12.8, built against Qt 5.12.8

Using Qt platform plugin 'xcb'

Using 'OpenSSL 1.1.1f  31 Mar 2020'

Running on Ubuntu 20.04.1 LTS, x86_64

Installation path of client: /usr/bin/nextcloud

### Logs

Haven't seen any errors in the logs, it seems like a general client problem. If it is only my installation I can add this information.

**Comment by expert-geeks** [comment]
same issue experienced

**Comment by er-vin** [comment]
@camilasan could be related to your work in that area? rings any bell?

**Comment by nursoda** [comment]
Not only applies to _per-instance_ ignore lists but also for _global_ ignore list (in Settings→General).

**Comment by benjamindahl** [comment]
this slows down my client extremely. How can I go back to 3.0.3 under ubuntu?

**Comment by expert-geeks** [comment]
You might find this link helpful, https://download.nextcloud.com/desktop/releases/

**Comment by benjamindahl** [comment]
> You might find this link helpful, https://download.nextcloud.com/desktop/releases/

Thanks a lot. It works for the moment.

**Comment by libeanim** [comment]
Hmm so the global ignore file seems to work for me and it also appears in the log:
```
2020-12-21 18:02:28:264 [ info nextcloud.sync.configfile ]:
Adding user defined ignore list to csync: "/home/andreas/.config/Nextcloud/sync-exclude.lst"
```
I'm just guessing, but @camilasan is it possible that the new [path building](https://github.com/nextcloud/desktop/pull/2540/files#diff-7715de21ae1fe2d616b58abab81764c131d4936d3f5172758ee660e6f7f65bd7R418) in the directory traversal function has a bug?

**Comment by roundoutandabout** [comment]
@libeanim I also have this issue. `Nextcloud-3.1.0-x86_64.AppImage` syncs everything ignoring the ignore list.
`Nextcloud-3.0.3-x86_64.AppImage` works fine.
I'm using KDE Neon 5.20

**Comment by albgus** [comment]
I noticed this with 3.1.0 and 3.1.1 on Windows as well.

**Comment by chuck-r** [comment]
This isn't just a Windows problem. I noticed the same thing when I upgraded Nextcloud using the Linux AppImage yesterday. Unfortunately, I'm not sure what version I came _from_, but upgrading to 3.1.1 caused it to try to sync all of my excluded files. I downgraded to 3.0.3 as mentioned here and I still have the same problem. However, I noticed that if I move my excluded files out of the sync path and let the folders sync sans the ignored files it syncs fine (of course, since it doesn't have to consider them). Then, if I move the ignored files back into the folder once the initial sync finishes successfully the files are properly ignored -- at least in my very small test case.

In one of my problem folders I had two subfolders, one with 50 or so fairly large source archives within a couple dozen folders. When I moved that folder into place it had no problems and did not synchronize them as the whole folder was on the ignore list. However, I had an issue with moving my second folder into place which had 15,357 folders and 330,359 files -- basically it at up all 119GB of my RAM before I finally had to kill it. But, that's a separate issue I think.

So, there is some disparity between the ignore list when it comes to a full sync (or a force resync, presumably) and an update sync (when it detects a file change).

**Comment by qu1ck** [comment]
I have this issue with 3.1.1 on windows. Folder specific ignore list doesn't work, global one does.

**Comment by chuck-r** [comment]
Thanks @qu1ck! I was getting really frustrated by not being able to sync a couple of folders due to this bug. Adding the exception globally did fix the problem, albeit not a perfect solution.

**Comment by StarSmasher44** [comment]
If I may provide some small insight into my actions dealing with this, I had to exclude log folders & contents, adding just Logs/ did not work. 

However, adding both 'Logs/' and 'Logs/*' made the entire folder plus contents be ignored as it should. Not sure if it is useful information, but that worked well enough for me.

**Comment by camilasan** [comment]
I will investigate it.

**Comment by FiC5020** [comment]
Have the same problem / issue too. Upgraded from 3.0.3 auf 3.1.1. Now the the client would sync 300 GB off Data which are excluded. Downgrade to 3.0.3 the ignore list works.

Problem solved with an older client.

**Comment by StarSmasher44** [comment]
> Have the same problem / issue too. Upgraded from 3.0.3 auf 3.1.1. Now the the client would sync 300 GB off Data which are excluded. Downgrade to 3.0.3 the ignore list works.
> 
> Problem solved with an older client.

Curious, have you tried the method I spoke of a bit above here? it worked out for me in that way, it may also work for you without the need to go back versions :)

**Comment by RM-0454** [comment]
> 3. Add a folder you want nextcloud to ignore
> 4. Start sync and create a folder that is in the ignored list
> 5. Watch nextcloud client sync this folder

@libeanim I have been having the same issue, but after the following fix worked, I think I know the bug's source.

> However I noticed that if I move my excluded files out of the sync path and let the folders sync sans the ignored files it syncs fine (of course, since it doesn't have to consider them). Then, if I move the ignored files back into the folder once the initial sync finishes successfully the files are properly ignored -- at least in my very small test case.


After trying both, my sync excludes are working and I think I know why. 

Let's walk through our process again. Pretend we want to exclude the directory `foo` from a synced folder.

- So under Folder Sync Settings we click "Edit Ignored Files" 
- Add foo\ (because we are on windows)
- In file explorer, create new folder and name it "foo"
- Watch in helpless anger as nextcloud proceeds to sync "foo" anyway

However, if instead of **creating** foo, we **copy** foo into the synced folder, nextcloud ignores it (as it should). What's the difference?

**Theory**
When a new folder is created it is automatically assigned the name "New folder" (in windows). "New folder" isn't an excluded file, so it is immediately synced before you rename it. Then when you do rename it, nexctloud records the change in the directories name without double checking it against the exclude list


OS: Windows 7  | NC Version 3.1.1

**Comment by timpur** [comment]
i found the oposite of https://github.com/nextcloud/desktop/issues/2728#issuecomment-751670821

Global Ignore list didnt work but folder ignore list did. 

Sandard format `node_modules/` worked in folder ignore list not root list.

(windows 3.1.2)

**Comment by dasaweb** [comment]
> this slows down my client extremely. How can I go back to 3.0.3 under ubuntu? There's no 3.0.3. package in the repository anymore.

Are you sure that this is a related problem? I see the same 2 problems when I update from 3.0.3 to 3.1.x: 
1. .sync-exclude.lst are ignored.
2. The client get's extremly slow.

I'm not sure if these two are related. But I hope, that this is the case, so solving one problem would also solve the other ;-)

**Comment by benjamindahl** [comment]
> > this slows down my client extremely. How can I go back to 3.0.3 under ubuntu? There's no 3.0.3. package in the repository anymore.
> 
> Are you sure that this is a related problem? I see the same 2 problems when I update from 3.0.3 to 3.1.x:
> 
> 1. .sync-exclude.lst are ignored.
> 2. The client get's extremly slow.
> 
> I'm not sure if these two are related. But I hope, that this is the case, so solving one problem would also solve the other ;-)

I don't know exactly what the problem is but I'll stick now with 3.0.3 for a while.

**Comment by dasaweb** [comment]
Staying with version 3.0.3 is the only option for me at the moment. However, with version 3.0.3 I have this additional problem: https://github.com/nextcloud/desktop/issues/324 So no working client for me right now... :-/

**Comment by snowflakeas** [comment]
I'm having similar problems in Windows 3.1.3 client - how do I stop .git folders from being synced?
What magical %¤"# words to I need to write in the exclude list?

**Comment by talesam** [comment]
This should be simpler, in the GUI to have an option to deselect what you don't want to synchronize, is that so complex to do?

**Comment by SMESH109** [comment]
Has anyone tested the new 3.2.0 client yet? The changelog doesn't seem to address the problems from this thread, but you never know.

**Comment by dasaweb** [comment]
> Has anyone tested the new 3.2.0 client yet? The changelog doesn't seem to address the problems from this thread, but you never know.

I'm not brave enough to test it. My last test with a version > 3.0.3 resulted in hours of manual "synchronization" ;-/

**Comment by SMESH109** [comment]
> > Has anyone tested the new 3.2.0 client yet? The changelog doesn't seem to address the problems from this thread, but you never know.
> 
> I'm not brave enough to test it. My last test with a version > 3.0.3 resulted in hours of manual "synchronization" ;-/

Exactly the same here😄 I don't have a test server or something and don't want to ruin my currently working 3.0.3, although I'm getting sick of it digging through my HDD endless times (SSDs are no problem at all! but it's also just ¼ the amount of data).

**Comment by silviuvulcan** [comment]
I only have a handful of ignored files so I was using the workaround (Adding to "Ignored Files" under settings not under the account)

I removed them from there and redid my list under account - ... - Edit Ignored Files and the initial impression is that it's back working. 

My version is 3.2.0 stable.

**Comment by SMESH109** [comment]
> I only have a handful of ignored files so I was using the workaround (Adding to "Ignored Files" under settings not under the account)
> 
> I removed them from there and redid my list under account - ... - Edit Ignored Files and the initial impression is that it's back working.
> 
> My version is 3.2.0 stable.

I uninstalled 3.0.3, installed 3.2.0 and did the same—removed the folders to exclude from the global ignore list and added them to the folder sync ignored files—but they get synced.
Added them back to the global ignore list and they get ignored as they should

**Comment by dasaweb** [comment]
My problem is that I have to use different exclude patterns for different sync pairs, so I can't define them in the global ignore list :-/

**Comment by silviuvulcan** [comment]
I take it back, it's still not working. 

A simple exclusion like:
`apps/keypirinha/portable/Profile/User/Keypirinha.history`  (I have some portable apps under `apps` in nextcloud)

is ignored (it's synced constantly and get conflicts when changed).

I'm puzzled why this doesn't get more exposure ? Is it some exotic server side setting that causes this ? I feel a lot more people should be reporting if exlude really is broken...

Server: 21.0.1 (docker)
Clients: Windows 3.2.1

**Comment by bluebirch** [comment]
I accidentally started 3.1 instead of 3.0, all my `.git` repositories was synked (again!) and i have to clean up the mess (again!). Would really appreciate having this bug fixed. ;-P

**Comment by dasaweb** [comment]
Version [3.3.0-rc1](https://github.com/nextcloud/desktop/releases/tag/v3.3.0-rc1) has come out, unfortunately there seems to be no progress regarding this issue here :-/ . So I'm stuck on version 3.0.3 for about 1 year now (and that is really annoying because 3.0.3 and 3.3.0 look so similar :-) ). But maybe there is hope after the bug was labeled as "approved" by the team here 8 weeks ago.

**Comment by LecrisUT** [comment]
Maybe we can get some update from @camilasan for #2723. Would that PR likely fix this issue and what's the status of it?

**Comment by FlexW** [comment]
Just for the record (not sure if anyone mentioned it already): The bug only occurs on root folders. It does not happen in subfolders.

**Comment by alzxjm** [comment]
> Just for the record (not sure if anyone mentioned it already): The bug only occurs on root folders. It does not happen in subfolders.

I'm not sure about this, unless I'm doing my patters incorrectly. My root folder is `Nextcloud` and I want to ignore `Nextcloud/org/notes.org` and the directory `Nextcloud/org/journal`. Accordingly, my ignore patterns are:

```
notes.org
org/notes.org
org/journal
```
and yet everything is synced. This is client 3.2.0 on macOS.

**Comment by vigne** [comment]
For me, on Linux using the AppImage version 3.3 the bug also still exists.

**Comment by patagonaa** [comment]
@alzxjm I think what @FlexW meant, is that the ignore file in the root directory does not work but ignore files in subdirectories work (at least during my tests on Windows, that was the only way I could get ignore files to work at all).

So in your case instead of an ignore file `Nextcloud/.sync-exclude.lst`, you _should_ be able to use an ignore file `Nextcloud/org/.sync-exclude.lst` with the patterns
```
notes.org
journal
```
and those directories _should_ be correctly ignored.

**Comment by arrowd** [comment]
Have this problem on FreeBSD with Nextcloud client 3.2.4

**Comment by acsfer** [comment]
@camilasan as you're the PR author, could this be related to https://github.com/nextcloud/desktop/pull/2540?

**Comment by jobec** [comment]
It would be great to get this fixed. As mentioned in #1875 this is very very annoying.
Been scratching my head again for a few hours trying to figure out why the hell some folders got ignored and others didn't. 🤯

**Comment by arrowd** [comment]
Interestingly, this functionality does work on Windows.

**Comment by jobec** [comment]
Yes and no...
I'm also on Windows. And the ignore function works. But only the global ignore settings. Those per sync setting do not.
And I'm in a situation where I need to ignore some files in sync setting A, but include those in sync setting B.

**Comment by viendocraz** [comment]
Also on Windows and experiencing this issue with v3.3.5. Folder Sync excludes are ignored at the root level but global excludes are working, which is fine as a temporary workaround but I'm hoping for a fix to make it work better!

**Comment by LecrisUT** [comment]
By now there is a strong consensus on the current behaviour on both MacOS, Windows and Linux, and it appears to be a bug in the code not any specific implementation. So it is no longer necessary to report this behaviour unless there is any changes. 
## Observed behaviour
- In global `sync-exlcude.lst` all of the exclusion are properly recognized.
- On any `Floder Sync Connection`:
   - The root `sync-exlcude.lst` is not recognized. It is synced but it is not used.
   - Each child `sync-exlcude.lst` is properly recognized (synced and used).

## Temporary workaround
- Manually specify any folders that should not be synced at the root level.
- For root files currently there is no solution.
- Add a `sync-exclude.lst` to every 1st level directories with your desired ignore rules.

## Potential solutions
#2723 Please test it and report if it fixes the issue. I will try it out myself as soon as I have the time.

**Comment by dasaweb** [comment]
> I wondered the same. #3882 is already merged into main and set for Release 3.4 #2723 has been rejected from automatic merge and has to be reviewed manually before merging.

Both pull requests are merged into the master branch now. Does this mean that we can now hope?

**Comment by djpadz** [comment]
@dasaweb I just grabbed the latest nightly, and it looks like things are working!  Huzzah!

**Comment by bretthl** [comment]
Same problem, ignore list not working.
Ubuntu 20.04
nautilus-nextcloud 3.3.6-20211028.151202.6d3270dd2-1.0~focal1

**Comment by dasaweb** [comment]
@bretthl Release 3.4.0 RC1 came out today (https://github.com/nextcloud/desktop/releases/tag/v3.4.0-rc1) that fixes #3882 and #2723. This should help. You can install this RC and help testing it ;-)

**Comment by bretthl** [comment]
> @bretthl Release 3.4.0 RC1 came out today (https://github.com/nextcloud/desktop/releases/tag/v3.4.0-rc1) that fixes #3882 and #2723. This should help. You can install this RC and help testing it ;-)

Thanks for that, I will start using it and comment.

**Comment by bretthl** [comment]
3.4.1 RC1 is worked with my testing using the ignore pattern somedir/* to suspend sync of all files in somedir.  Keep up the good work, this app is awesome.

**Comment by LecrisUT** [comment]
Thank you for the pre-release. As expected, it works on MacOS as well with all the patterns in root and sub-directory being inherited correctly. Creating a `.sync-exclude.lst` overwrites the previous root one. Probably windows will work correctly as well, so any reason not to close the issue now that all changes have been merged?

Although, is there any `#include ../.sync-exclude.lst` functionality or similar?

**Comment by SMESH109** [comment]
> using the ignore pattern somedir/* to suspend sync of all files in somedir.

isn't the correct pattern just somedir/ without the asterisk? won't somedir/* scan all the files in the subfolder anyway but ignore them instead of just leaving out the whole folder for scan?

**Comment by FlexW** [comment]
> Although, is there any #include ../.sync-exclude.lst functionality or similar?
No

> isn't the correct pattern just somedir/ without the asterisk? won't somedir/* scan all the files in the subfolder anyway without syncing them afterwards instead of just leaving out the whole folder for scan?

As far as my understand goes, `somedir/` will ignore and don't sync the folder `somedir`. `syncfolder/*` sould still sync the folder `somedir` but no file inside it.

Closing this issue as it seems that the original issue is resolved. Thanks for your help!

**Comment by bretthl** [comment]
> > Although, is there any #include ../.sync-exclude.lst functionality or similar?
> 
> No
> 
> > isn't the correct pattern just somedir/ without the asterisk? won't somedir/* scan all the files in the subfolder anyway without syncing them afterwards instead of just leaving out the whole folder for scan?
> 
> As far as my understand goes, `somedir/` will ignore and don't sync the folder `somedir`. `syncfolder/*` sould still sync the folder `somedir` but no file inside it.
> 
> Closing this issue as it seems that the original issue is resolved. Thanks for your help!

Your are correct.  I've been playing with both options and probably best to leave out the asterisk.  Can anyone point me to a list of "flags" with explanations of each?  Been awhile since I have used these.

**Comment by dasaweb** [comment]
> @bretthl Release 3.4.0 RC1 came out today (https://github.com/nextcloud/desktop/releases/tag/v3.4.0-rc1) that fixes #3882 and #2723. This should help. You can install this RC and help testing it ;-)

I was now brave enough to test the 3.4.0 RC1 on Win11, and tataaaaaa: It works! Finally having an up-to-date Nextcloud client again after a year is great. THANK YOU to everyone who contributed here! 💖

**Comment by Detzi88** [comment]
I still have this issue on Version 3.4.2 (Ubuntu).
```
.git/*
.git/
.git
```
set in both the "general settings" and the "..." submenu are leading to the ".git" folder nor its content beeing ignored by nextcloud.

Is that only on my side or do others have the same issue?

**Comment by bop34** [comment]
Yeah me too

**Comment by Migsi** [comment]
> I still have this issue on Version 3.4.2 (Ubuntu).
> 
> ```
> .git/*
> .git/
> .git
> ```
> 
> set in both the "general settings" and the "..." submenu are leading to the ".git" folder nor its content beeing ignored by nextcloud.
> 
> Is that only on my side or do others have the same issue?

Me as well, I'm on EndeavourOS, my client version is:
```
$ nextcloud --version
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Nextcloud version 3.9.0git
Git revision c6c6c61f5e66e311abcd1e78ecec2266c2298dda
Using Qt 5.15.10, built against Qt 5.15.10
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.1.1 30 May 2023'
Running on EndeavourOS, x86_64
```
Steps to reproduce are:
1. Add "repo" and "repo/" to global and/or sync ignore list (mix as you wish, doesn't matter) 
2. Move folder "repo" into synced directory
3. Give the client ~5 seconds
4. Watch it sync the excluded folder

I carefully read through all this thread and related resources to ensure I'm not just messing up my exclusion "pattern", but at this point I'm pretty sure I don't and this has to be broken again :(

**Comment by bop34** [comment]
I have some new info to share. I just got this working on Windows by using two ignores. For example to ignore everything in a folder named `example` I added _both_ `example/` and `example\` to my ignore list. On Linux I was able to ignore with just `example/`. In both examples neither the folder itself nor the files in the folder synced to the server.
Notes:
- On Windows I got an error every sync if I did not do both `example/` and `example\`, but the files still synced.
- Be aware that after ignoring a folder any previously synced stuff will remain on the server.
- I also noticed that after removing a folder from the ignore list any previously existing files would not sync and I had to recreate the whole folder and the files in it to get it to sync.

**Comment by mxwell-dev** [comment]
My observation is that `.sync-exclude.lst` files further down in the sync'd directory tree seems overwrite top level exclude rules, rather than extend on them. This may make sense if there's no way to negate a rule (in `.gitignore` with a prefixed `!`), but sure as rain is unintuitive. So if `.git/` ignored top-level and some git repository synced by nextcloud contains a local exclude for `build/`, it will sync `.git` again.

**Comment by psyciknz** [comment]
Any further updates to this?  I have a .sync-exclude.lst file in a subdirectory for excluding (as others are doing .git).   If I have it in the global it exlcudes as I desire.  But if the excludes are set in a .sync-exclude.lst where the .git directory is a subdirectory.  Then I can see the sync log full of objects when I make a commit.

So for reference.
Nextcoud\Documents\Connections\.git is the .git folder I want to exclude everything but the config file.
Nextcoud\Documents\Connections\.sync-exclude.lst - is my exclude file (contents below)

```
].git/COMMIT_EDITMSG
].git/FETCH_HEAD
].git/HEAD
].git/ORIG_HEAD
.git/logs/
.git/logs/refs/
.git/logs/refs/heads/
.git/logs/refs/remotes/
.git/objects/
.git/objects/pack/
].git/objects/pack/tmp_pack*
.git/objects/*/
].git/objects/*/*.*
].git/objects/*/*
].git/objects/pack/*.*
].git/index.lock
.git/refs/
.git/refs/*/
.git/refs/*/*
.git/refs/tags/
```
Version 3.4.0 Windows.

**Comment by joshtrichards** [comment]
You're commenting on an Issue that has been closed out for several years. If experiencing something (even similar) please open a new dedicated Issue as it may have a different underlying cause.
