### ISSUE TITLE
Renaming files (Virtual files) shows syncing icon forever

### ISSUE THREAD

**Issue by claell** [nextcloud/desktop#3440]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Renaming a synced file should also sync and show a green checkmark icon

### Actual behaviour
Renaming seems to get synced but is still displayed with a sync icon (in Windows Explorer, not sure, whether other operating systems are also affected)

### Steps to reproduce
1. Copy a file
2. Paste it
3. Rename it

### Client configuration
Client version: 3.2.2

Operating system: Windows

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by claell** [comment]
Screenshot:
![grafik](https://user-images.githubusercontent.com/6171135/121914605-b560a200-cd32-11eb-9655-a79f6221ed77.png)

The syncing icon should not be there, instead a checkmark should be displayed.

**Comment by claell** [comment]
This also applies to moved files (probably because technically this is only a renaming of the path).

Since this is a rather annoying bug of a new feature, I hope it is seen as important and can be fixed soon.
Ping @er-vin @camilasan @jospoortvliet

**Comment by FlexW** [comment]
This is solved by https://github.com/nextcloud/desktop/pull/3432

**Comment by claell** [comment]
Ah, perfect, thanks for referencing that. Then I hope the next patch release will be soon :)

**Comment by claell** [comment]
@FlexW I can confirm things work as expected with 3.2.3 now. Unfortunately, already wrong icons are not fixed automatically. Another rename is needed in order to fix them. Not a big problem, but inconvenient for existing users who are upgrading.

**Comment by claell** [comment]
BTW: It also does not seem to fix the problem for folders directly at top level. All sub-items of them are marked as synced, but they still show the syncing icon for me. Reopening for now.

**Comment by claell** [comment]
Push. I don't really like how the stale bot behaves.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
