### ISSUE TITLE
Can't rename folders with virtual files enabled

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#3515]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

I should be able to rename or create a folder

### Actual behaviour

Windows explorer says that an "unexpected error" has occurred and that the operation cannot be completed because folder synchronisation is pending

![grafik](https://user-images.githubusercontent.com/3313208/124614156-416a7300-de74-11eb-9a78-9e8eded41dbf.png)

### Steps to reproduce
1. Switch from full sync to virtual files
2. try to create or rename a folder
3. watch what happens

### Client configuration
Client version: 3.2.3

Operating system: Windows 10

OS language: DE

Installation path of client:

C:\Program files\Nextcloud

### Server configuration

Nextcloud version: 21.2

Storage backend (external storage): (none)

### Logs

As requested, I have created a debug archive, but I cannot attach it here. Please provide a mail address to send it to.

**Comment by camilasan** [comment]
Drop the logs here https://cloud.nextcloud.com/s/8dMHFXDpWTSDGdw

**Comment by vasyugan** [comment]
> Drop the logs here https://cloud.nextcloud.com/s/8dMHFXDpWTSDGdw

Thanks, done.

**Comment by FlexW** [comment]
@vasyugan Does it still happen with 3.3.0? Because there were some changes in that area?

**Comment by vasyugan** [comment]
> @vasyugan Does it still happen with 3.3.0? Because there were some changes in that area?

I will have to test. Kindly remind me again, if I don't get back to you.

**Comment by vasyugan** [comment]
> 
> 
> @vasyugan Does it still happen with 3.3.0? Because there were some changes in that area?

Just tested with ver 3.3.1, no changes, unfortunately.

**Comment by mgallien** [comment]
> > @vasyugan Does it still happen with 3.3.0? Because there were some changes in that area?
> 
> Just tested with ver 3.3.1, no changes, unfortunately.

could you please test again with 3.3.2 because we fixed a bug related to rename ?

**Comment by vasyugan** [comment]
> > > @vasyugan Does it still happen with 3.3.0? Because there were some changes in that area?
> > 
> > 
> > Just tested with ver 3.3.1, no changes, unfortunately.
> 
> could you please test again with 3.3.2 because we fixed a bug related to rename ?

I currently cannot reboot the computer into Windows because it is busy with a lengthy deduplication operation of a 6GB btrfs file system on a mechanical hard disk. This seems to take forever.

I will reboot into Windows and try as soon as I can.

**Comment by vasyugan** [comment]
Persists, even after completely removing the app, including all the registry keys I was able to find and reinstalling it,

**Comment by vasyugan** [comment]
Problem persists. Sorry.

**Comment by vasyugan** [comment]
Bug still present. Seems to not only affect Nextcloud but other cloud storages, too.

**Comment by vasyugan** [comment]
Finally I found out, that this wasn't an issue related to nextcloud. No folder, including folders outside the Nextcloud directory tree, could be renamed at all, using windows explorer, while on the command line it worked fine.

While I did not find the exact culprit, resetting Windows explorer settings by deleting the registry tree HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer fixed it.
