### ISSUE TITLE
the difference between nextcloud/desktop and owncloud/desktop?

### ISSUE THREAD

**Issue by xinyuwang** [nextcloud/desktop#417]
I found these two repositories are similar. Are they compatible?
Is the bug will be fixed in both repositories (if existed)? will other improvements in both repositories?
The version of latest nextcloud is 2.3.3 while the owncloud is 2.4.1, any detail difference about them?
thanks a lot.

**Comment by Kjwon15** [comment]
I was using owncloud-client to sync with nextcloud server(it was migrated from owncloud) and it worked perfectly.
But I am using nextcloud-cloud now.

**Comment by jospoortvliet** [comment]
Hi,

At the moment, our 2.3.x is pretty much the same as the ownCloud 2.3.x. We didn't release the 2.4 series as we were unhappy with stability and many user interface changes made. We focus our work now on 2.5 where we add end-to-end encryption and a bunch of other improvements, including fixes for the UI changes.

We generally still take 95% of the code from upstream and make sure all bugs are fixed, and fix some more. So at least the Nextcloud client has all features and fixes of ownCloud when released, we don't yet know exactly if we enable some of their more experimental work, though.

**Comment by xinyuwang** [comment]
@jospoortvliet Thanks for your kind explanations.

**Comment by rizerzero** [comment]
For me the owncloud client is still way better than the Nextcloud one. even the interface gives us more informations, we have notifications about file changes ect ... 
I'm not  sure for how long it will be possible to use the owncloud client but for me the nextcloud client is still not mature.
