### ISSUE TITLE
[Bug]: macOS Nextcloud Finder extension is still crashing regularly, causing right-click menu to stop working 

### ISSUE THREAD

**Issue by briankendall** [nextcloud/desktop#4459]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

This is a follow up to #4277

I am running Nextcloud Desktop 3.5.0 RC3 as it contains changes to how it handles its Finder integration in macOS, which I had hoped fixed #4277. However, it has not:

On a regular basis, sometimes multiple times per day, Nextcloud's Finder extension will crash, causing the right-click menu to stop working. In order to get Finder integration working again, I need to restart Nextcloud.

Fortunately and unlike previous crashes with version 3.4.x, when this occurs, a dialog box will appear informing that the extension has crashed, allowing me to get at a crash report.

Among the crash reports, there are two unique stack traces. I have attached four recent crash logs, two for each unique crash, to this report.

Crashes: [Nextcloud_Desktop_3.5.0RC3_FinderSyncExt_crashes.zip](https://github.com/nextcloud/desktop/files/8564785/Nextcloud_Desktop_3.5.0RC3_FinderSyncExt_crashes.zip)
 

### Steps to reproduce

Unfortunately I have found no consistent way to trigger this crash, but will update if I find one.

### Expected behavior

Obviously the Finder extension should not crash.

### Which files are affected by this bug

N/A

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 10.14.6

### Package

Other

### Nextcloud Server version

22.2.3

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

**Comment by briankendall** [comment]
Quick update: just got another crash that happened while Nextcloud was idle and in the background. There was a little bit of activity in my synced folder, with a single file being updated once a minute. Other than that, I wasn't interacting with the app at all, nor using the Finder. Crash log attached
[FinderSyncExt_2022-04-26-162421_Qqqqqqq.crash.txt](https://github.com/nextcloud/desktop/files/8566697/FinderSyncExt_2022-04-26-162421_Qqqqqqq.crash.txt)
.

**Comment by EmmanuelLazard** [comment]
I'm having exactly the same bug since I upgraded to 3.5.0. Running on MacOS 10.13

**Comment by scheffle** [comment]
I've the same issue on an Intel mac while on an Apple Silicon mac it does not crash. (Both run macOS 12.3.1 connecting to the same server). This is new with version 3.5.
[FinderSyncExt-2022-05-08-132140.ips.zip](https://github.com/nextcloud/desktop/files/8646877/FinderSyncExt-2022-05-08-132140.ips.zip)

**Comment by scheffle** [comment]
After looking at the crashlog and the source code of the crash it is obvious that the crash happens because the macOS API `dispatch_source_cancel` should not be called with a nullptr. (See https://developer.apple.com/documentation/dispatch/1385604-dispatch_source_cancel) which the source code does according to the callstack. So guarding the calls to `dispatch_source_cancel` should fix the crash.

**Comment by fiveangle** [comment]
Came here to report same.

**Comment by claucambra** [comment]
> > After looking at the crashlog and the source code of the crash it is obvious that the crash happens because the macOS API `dispatch_source_cancel` should not be called with a nullptr. (See https://developer.apple.com/documentation/dispatch/1385604-dispatch_source_cancel) which the source code does according to the callstack. So guarding the calls to `dispatch_source_cancel` should fix the crash.
> 
> Hey all,
> 
> I have been unable to reproduce the issue on my machine but looking at the stack traces it seems @scheffle is most likely right. I've opened #4520 which ensures that `dispatch_source_cancel` is only called on the dispatch sources when they are valid.
> 
> Thanks @scheffle for highlighting the core of the issue and thanks all for your reports, I hope we can release the next bugfix release of the client to you all soon :)

**Comment by briankendall** [comment]
I'm afraid this crash isn't quite fixed yet. I'm still getting regular crashes in v3.5.1 (specifically 3.5.1git build 10326). I have several crash logs, though they all have the same stack trace so I'm attaching just the latest one. Can we reopen this issue?

[FinderSyncExt_2022-06-03-093813_Qqqqqqq.crash.txt](https://github.com/nextcloud/desktop/files/8902688/FinderSyncExt_2022-06-03-093813_Qqqqqqq.crash.txt)

**Comment by p-sims** [comment]
Hello, I'm not sure whether I should be raising this in a new thread or here, but I'm now running v3.5.3 and I'm still getting what I assume is finder extension issue, where the right click menu disappears. If I restart nextcloud client it comes back for a bit, but then are either hours or days it will disappear again. I can raise as a separate thread if helpful.
![Screenshot 2022-08-03 at 09 33 49](https://user-images.githubusercontent.com/64636731/182563196-8b113977-4ce1-4d9b-b27f-2e40aa611f24.png)

When right click menu disappears the nextcloud icons next to files and folders also seem to get stuck in slightly odd place (with nextcloud icons as a tick saying all synced).
![Screenshot 2022-07-18 at 17 18 36](https://user-images.githubusercontent.com/64636731/182563496-61028756-79df-4310-aff1-1058d7ec5863.png)

**Comment by briankendall** [comment]
I'm getting the same issue too, but with v3.5.4. The right-click context menu just stops working until I restart Nextcloud. I'll note that I've been having this issue with Nextcloud for as long as I've been using it (so a few years now), and alas it doesn't seem to be fixed even after the Finder extension was revamped.

There are no crashlogs I can send this time.

**Comment by gibelium** [comment]
Still an issue with v3.14.3 and it's not just annoying but **breaks the sync mechanism**. After the error occurs the Nextcloud Desktop Client is no longer able to sync files that have been changed. I have to close and restart the app before changes are synced again.

This should be fixed urgently..!!

**Comment by claucambra** [comment]
> Still an issue with v3.14.3 and it's not just annoying but **breaks the sync mechanism**. After the error occurs the Nextcloud Desktop Client is no longer able to sync files that have been changed. I have to close and restart the app before changes are synced again.
> 
> This should be fixed urgently..!!

Finder extensions have absolutely no effect on sync so you must be encountering some other issue, I'd recommend you check other open issues to see if your problem has anything in common with them

**Comment by gibelium** [comment]
> Finder extensions have absolutely no effect on sync so you must be encountering some other issue, I'd recommend you check other open issues to see if your problem has anything in common with them

Thank you for the clarification. I'll continue my search then...
