### ISSUE TITLE
[Bug]: Nextcloud desktop client linux creates "cacheDir" directory in home

### ISSUE THREAD

**Issue by jeekajoo** [nextcloud/desktop#4483]
### Bug description

When running Nextcloud Desktop client, it creates a ~/cacheDir directory.

```
 ~  tree cacheDir 
cacheDir
├── data8
│   ├── 0
│   │   └── vorgf4gp.d
│   ├── 1
│   ├── 2
│   │   └── 17xm0fmb.d
│   ├── 3
│   │   └── 10ue3sac.d
│   ├── 4
│   ├── 5
│   │   ├── 3dq0bw1u.d
│   │   └── 3o0tzdd5.d
│   ├── 6
│   │   ├── uswzahmv.d
│   │   └── x1ozaqjv.d
│   ├── 7
│   │   ├── 3juwzkdg.d
│   │   └── l7r9isyg.d
│   ├── 8
│   ├── 9
│   │   ├── 1nmfnw09.d
│   │   └── 3cj6jbpi.d
│   ├── a
│   ├── b
│   │   └── 1692ap7k.d
│   ├── c
│   ├── d
│   ├── e
│   │   ├── 2fshf8xn.d
│   │   └── 2q3smr0n.d
│   └── f
│       └── 22fmhbqo.d
└── prepared

18 directories, 15 files
```

### Steps to reproduce

1. install nextcloud client 3.5.0 on linux
2. run it

### Expected behavior

No ~/cacheDir directory is created. Nextcloud client uses standard cache directory in ~/.cache/...

### Which files are affected by this bug

~/cacheDir

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 21.10 (ubuntu-5.13.0-28-generic)

### Package

3.5.0 from PPA (deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu/ impish main)

### Nextcloud Server version

23.0.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jeekajoo** [comment]
Maybe it can help reproduce the issue : I have 2 nextcloud accounts from 2 different nextcloud servers registered in the desktop client.

**Comment by claucambra** [comment]
Hi, I can reproduce. Seems like our cacher for thumbnails and avatars for the tray window is dumping its files in the home dir

**Comment by solisinvictum** [comment]
I updated my System (Arch Linux) today. With Nextcloud 3.4.4 i dont had a "cacheDir" Folder in my home.

Now, with Nextcloud 3.5.0, i have a "cacheDir" Folder in home, wich i cant remove permantly (it comes back everytime).

**Comment by claucambra** [comment]
> I updated my System (Arch Linux) today. With Nextcloud 3.4.4 i dont had a "cacheDir" Folder in my home.
> 
> Now, with Nextcloud 3.5.0, i have a "cacheDir" Folder in home, wich i cant remove permantly (it comes back everytime).

Hi,

The fix for this has been merged and will be included in the next bugfix release :)

**Comment by solisinvictum** [comment]
ah ok, I understood that 3.4.4 has this bug and it would have been fixed with 3.5.0.

Thank you.

**Comment by agilob** [comment]
> the next bugfix release

when will it be?

**Comment by claucambra** [comment]
> > the next bugfix release
> 
> when will it be?

If all goes well it should be rolling out this week.

**Comment by jeekajoo** [comment]
Thanks much

**Comment by Pingger** [comment]
The issue still persists in Nextcloud `2:3.5.1-2` (in Settings>General `3.5.1 (Manjaro)`) from the "Offical Repositories (community)"
I'm running manjaro-5.15.41-1-MANJARO

**Comment by agilob** [comment]
Fixed on archlinux in `Version 3.5.1 (Arch)`
