### ISSUE TITLE
[Bug]: Windows Application don't sync all files

### ISSUE THREAD

**Issue by francofischer** [nextcloud/desktop#4610]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

In our organization we have our own server running Nextcloud 23.0.5 in an Ubuntu 20.04 Server with MariaDB. All the users use the Windows Client to keep synced all our files. 
Today I find that one user don't see any file in a shared folder, but if the user login in the web application and navigate to this folder he can see all the files. Also, when the user create a new folder in the windows explorer, the Nextcloud (3.5.1) client start to sync all the files inside this folder.
I force the sync in the client, but nothing happend.

### Steps to reproduce

1. I found a folder without any files in the windows explorer.
2. Check that this folder have files in the web browser.
3. Force the sync in the desktop client (nothing happend).
4. Create a folder/file in this empty folder.
5. Windows client start to sync all files inside this folder.

### Expected behavior

I expect that the user see the same files in the windows explorer and the web browser.

### Which files are affected by this bug

\Compartida\Proyectos\Lyrtron\Nexum\Desarollo\Mediciones\Mediciones con NRFConnect\Prueba Interna de Prototipos\FF\2021-06-11

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.5

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by konradbr** [comment]
+1 I have the exact same problem. Sometimes a modification or rename of the concerned folder triggers a re-sync.

**Comment by konradbr** [comment]
Updated NextCloud Server to v. 24.0.1
Will update this thread if the error still occurs.

**Comment by konradbr** [comment]
Under NextCloud Server v. 24.0.1. and Client v. 3.4.1 the issue persists. Renaming the folder on the server did not work. Only way to sync to client was to create a new folder on the server and move the contents of the folder not syncing to the new folder.

**Comment by camilasan** [comment]
@francofischer @konradbr We will really need logs for this issue.

**Comment by aalsamman** [comment]
+1 I have the same exact issue. Tried with multiple windows clients V3.5.x V3.6 and the issue is persistent. 
Server version 24.0.6
Windows 11

I only started having the issue recently (last 2 weeks). I don't have access to the server thus I can't provide logs :/

**Comment by konradbr** [comment]
@camilasan when I see it happening again I'll send you some more detailed data. I've got own servers running now.

**Comment by aalsamman** [comment]
@camilasan @konradbr @francofischer  I have checked out the logs of the client, and in all the folders that I have issues with, I found such a line

`2022-11-02 17:54:42:889 [ warning default C:\Users\sysadmin\AppData\Local\Temp\2\windows-11567\client-building\desktop\src\csync\csync_exclude.cpp:438 ]:	System exclude list file could not be read: "C:/[PATH]/.sync-exclude.lst"`

I fixed the issue through: I went to the _settings_ -> _edit ignored files_ -> clicked on _Remove_ **although the list is empty** -> save
This triggered a new sync and then the client showed an error that it couldn't sync the `.sync_execlude.lst` but then it synced itself again and the issue fixed!!!!

Now, the client is completely normal and is syncing as usual!

**Comment by gabgaud** [comment]
I had the same problem recently. The names of some of my files contained characters that were not allowed in the Windows client. Once renamed, the files synced.

**Comment by harleydica** [comment]
Any update from this bug? i had the same problem recently, please help me.

**Comment by oleskyetec** [comment]
Still reproducible on current versions (desktop client [4.0.x], server [13.0.4], Windows [11]).

Same behavior as the original report: a folder shows up empty in the client while every file is visible in the web UI, and "Force sync now" does nothing. Creating any new file in that folder, either locally or through the web UI, immediately makes the client pull down all the previously-missing files.

One detail that might help narrow this down: when the missing files finally sync after that trick, they arrive with their original modification timestamps, not the time of the workaround. So the files and their metadata are clearly on the server the whole time. The client just never re-reads the folder listing until something bumps the folder's ETag. That points at a stale-ETag / sync-journal problem rather than the files actually being absent.

This matches #6244, where the only reliable fixes were re-adding the folder sync or deleting sync*.db, i.e. forcing the client to drop its cached ETags.

For some people in related threads the trigger was an unreadable .sync-exclude.lst (a csync_exclude.cpp "could not be read" warning in the log), fixed via Settings -> Edit ignored files -> Remove -> Save, which kicked off a fresh sync. That may be a contributing factor for some of us but not all.

**Comment by Rello** [comment]
Please re-evaluate with a recent version
