### ISSUE TITLE
Mac beta client 2.5.0 prevents system to use integrated gpu

### ISSUE THREAD

**Issue by doits** [nextcloud/desktop#501]
I installed the latest mac desktop tryout client from https://download.nextcloud.com/desktop/daily/Mac/ (20180721) and syncing works great so far. Unfortunately the power consumption of my mac went up and I noticed the following in the activity monitor energy tab of my mac (in German, but I think you can correlate the columns):

<img width="1012" alt="bildschirmfoto 2018-07-21 um 10 36 01" src="https://user-images.githubusercontent.com/148003/43034461-132a349e-8cdd-11e8-93c4-8b96f794337c.png">

The client requires the high performance gpu, and therefore my system runs on the high performance gpu all the times:

<img width="200" alt="bildschirmfoto 2018-07-21 um 10 37 51" src="https://user-images.githubusercontent.com/148003/43034463-1b6711b8-8cdd-11e8-8279-e59aec05c35d.png">

... which noticably leads to higher power consumption.

Is this normal and tryout builds (maybe because of a DEBUG flag) or is this a bug?

**Comment by doits** [comment]
Unfortunately gfxCardStatus does not work for me – it always switches to `discrete`, even when I select `integrated` (and nextcloud is not running). Only when `automatic` is selected, it switches to `integrated`, but once nextcloud is started ...

**Comment by zoc** [comment]
Hi,

Is the fix supposed to be in the nightly from today ? (build 20180816)

My 2010 Macbook Pro is still switching to the discreet GPU instead of the integrated one.

**Comment by d235j** [comment]
@rullzer Unfortunately this key is not present in the 20180909 Mac daily build. I added it manually and it has to expected behavior.

**Comment by camilasan** [comment]
Apparently it is not fixed yet.

**Comment by HackintoshHD** [comment]
Just to confirm: Unfortunately this issue is **not solved**, the bug is still present in the current macOS Nextcloud Sync Client release 2.5.1final (build 20181204). Here's a screenshot taken on macOS 10.13.6 High Sierra:

![nextcloud-sync-client-macos---discrete-gpu-dependencies](https://user-images.githubusercontent.com/2894628/50046529-24e37100-00a5-11e9-8928-f89c2efebec8.png)

This is quite annoying especially for users of older MacBook Pros, as some models have a tendency to develop a significant heat when running on discrete graphics permantently. Not to mention the fact that you easily halve your battery life when using discrete graphics permanently. Including the fix in the next Client release would be highly appreciated!

@doits : If gfxCardStatus doesn't work for you, you might give @CodySchrank 's new [gSwitch](https://github.com/CodySchrank/gSwitch) app a try (like I did in the screenshot above).

**Comment by jospoortvliet** [comment]
Does anyone know how to fix this, what flag has to be set or something?

**Comment by jospoortvliet** [comment]
Some more info here... Not sure where that other flag is set:
https://stackoverflow.com/questions/12445561/nssupportsautomaticgraphicsswitching-support/25152391#25152391

**Comment by HackintoshHD** [comment]
@jospoortvliet https://stackoverflow.com/a/25152391 suggests there is more to do than what was done in commit https://github.com/doits/desktop/commit/2335688b6841afbb776d42bc70f08fbf85c342cc:

> The issue I was having was that I wasn't supporting multiple renderers as per [this technical note](https://developer.apple.com/library/archive/technotes/tn2229/_index.html). I needed to add to my `NSOpenGLPixelFormatAttribute` list the `NSOpenGLPFAAllowOfflineRenderers` attribute. Now that I have that, my app won't automatically trigger the discrete card, and I can actually switch between integrated and discrete at will.

If that's the relevant info for our case here is honestly beyond my knowledge.

**Comment by sroracle** [comment]
I can confirm @HackintoshHD's finding that version 2.5.1final (build 20181204) is still using discrete graphics (installed and tested today on OS X 10.10.5, confirmed using Activity Monitor). However, adding the following to `nextcloud.app/Contents/Info.plist` per @HackintoshHD's latest comment fixes the issue (i.e. Activity Monitor no longer shows discrete graphics usage by Nextcloud):

```
	<key>NSOpenGLPixelFormatAttribute</key>
	<string>NSOpenGLPFAAllowOfflineRenderers</string>
```

**Comment by myset** [comment]
The same behaviour on Linux 4.15.0-88-generic - Ubuntu 18.04.4 - 
nextcloud-client 2.6.4-20200303 require and use GPU
Why GPU?

**Comment by misch7** [comment]
Oh seems like this issue here got a bit lost in the past.

My first guess would be that the Qt framework tries to utilize the GPU for fast UI painting. But of course this should not drain the GPU so intensively.

Thanks for the suggestions @doits, @HackintoshHD and @sroracle ! That's a starting point to look into it.

**Comment by doits** [comment]
I'm using 2.7.0bet1 and for me it looks good:


<img width="1265" alt="Bildschirmfoto 2020-03-06 um 15 07 48" src="https://user-images.githubusercontent.com/148003/76090732-5b641f00-5fbc-11ea-9097-222892cb7f21.png">

<img width="192" alt="Bildschirmfoto 2020-03-06 um 15 08 17" src="https://user-images.githubusercontent.com/148003/76090735-5d2de280-5fbc-11ea-9f49-7b1457388031.png">

**Comment by misch7** [comment]
> I'm using 2.7.0beta1 and for me it looks good:
> 

Thanks for the update @doits, maybe this was solved then by our update to Qt 5.12 in more recent Desktop Client versions :)

**Comment by misch7** [comment]
> The same behaviour on Linux 4.15.0-88-generic - Ubuntu 18.04.4 -
> nextcloud-client 2.6.4-20200303 require and use GPU
> Why GPU?

@myset:
- Could you provide the output of `nextcloud --version`?
- Did you install it via system's package manager (not AppImage)?
- Do you also have the issue with our AppImage?
  https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.6.4-x86_64.AppImage

**Comment by myset** [comment]
> @myset:

    Could you provide the output of nextcloud --version?
2.6.4git
    Did you install it via system's package manager (not AppImage)?
Yes. deb version
    Do you also have the issue with our AppImage?
Yes


Mon Mar 23 23:11:26 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P0    25W /  N/A |   1007MiB /  6078MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4878      G   /usr/lib/xorg/Xorg                           663MiB |
|    0      5077      G   /usr/bin/gnome-shell                         339MiB |
|    0     19662      G   ...wnloads/Nextcloud-2.6.4-x86_64.AppImage     2MiB |
+-----------------------------------------------------------------------------+

**Comment by joeyalexander** [comment]
> > I'm using 2.7.0beta1 and for me it looks good:
> 
> Thanks for the update @doits, maybe this was solved then by our update to Qt 5.12 in more recent Desktop Client versions :)

Just to throw a spanner in the works @misch7, I'm using 2.7.0beta1 and it is still using high performance GPU. On Mac OS 10.13.6


![image](https://user-images.githubusercontent.com/28354568/80732343-15cb5a80-8b04-11ea-9784-0d4f29598d10.png)

**Comment by d235j** [comment]
@joeyalexander can you include your Mac model or model identifier?

**Comment by joeyalexander** [comment]
@d235j 

MacBook Pro 6,2 (15-inch, Mid 2010)
(It's getting on a bit)

**Comment by d235j** [comment]
@joeyalexander I believe this is specific to the Mid-2010 model. I experienced the same behavior with Google Chrome on the 17".

[This was reported to Google](https://bugs.chromium.org/p/chromium/issues/detail?id=479299) and they noted it as WontFix because Apple gave them guidance long ago that GPU switching would cause hangs. Those hangs seem to have been fixed by macOS 10.11, but Apple never updated the guidance [and has since made the computer obsolete for their purposes](https://support.apple.com/en-us/HT201624) — and macOS 10.11 was released roughly five years after the Mid-2010 model, which is their threshold for "vintage".

In the bug report, they provide a workaround for Chrome — the command-line parameter ` --force_discrete_gpu=0`; however, I am not sure how to pass this to Qt. A checkbox or hidden setting that enables this parameter would be nice. I'd be fine with a documented hidden setting as there probably aren't many people using this model of Mac.

If this problem happens on newer computer, then it is definitely a bug that needs to be addressed.

**Comment by d235j** [comment]
It looks like you can set the environment variable `QTWEBENGINE_CHROMIUM_FLAGS` to pass that parameter, and you can use [launchctl to set it globally](https://stackoverflow.com/a/14285335).

You'd want `QTWEBENGINE_CHROMIUM_FLAGS="--force_discrete_gpu=0"`. That said, I haven't tested it.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients). Thanks!

**Comment by Lord-Nightmare** [comment]
I can test this very soon.

**Comment by Lord-Nightmare** [comment]
Tested: It still happens here, stuck on the discrete gpu unless the app is exited.
Nextcloud Client 3.1.3
macOS High Sierra 10.13.6
MacBook Pro (17-inch, Mid 2010)
2.66GHz Intel Core i7
6GB Ram
Nvidia Geforce GT 330M 512MB (discrete)
Intel HD Graphics 288MB (integrated)

**Comment by d235j** [comment]
@camilasan do you need this re-tested, or would you say this is not worth fixing because the hardware is considered obsolete by now?

**Comment by myset** [comment]
Still require GPU also in Version 3.2.1 (Ubuntu)

**Comment by d235j** [comment]
This is not resolved. On the MacBook Pro (15-inch or 17-inch, Mid 2010), this problem still happens.

I would expect this problem to go away entirely if a build without QtWebEngine was used on these Macs.

**Comment by mgallien** [comment]
with regard to the Mac support our plan is to switch to a newer version of Qt that has native support for all architecture used by Macs
at this point we can revisit what would be needed to improve the situation on Macs
