### ISSUE TITLE
[Bug]: Desktop Client freezes in a 100% CPU load loop after server upgrade to 25

### ISSUE THREAD

**Issue by RainerKlute** [nextcloud/desktop#5094]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After upgrading the server to NC 25 stable (25.0.0.18, to be exact), the desktop client (3.6.1 on openSUSE Tumbleweed) does no longer sync from the client to the server. Instead, the **client totally freezes**, while using 100% CPU load.

It turned out that the **bulk upload** feature is in error. As a workaround, I turned off bulk upload in the server’s _config.php_ file by adding the following line:

`'bulkupload.enabled' => false,`

### Steps to reproduce

See the description above.

### Expected behavior

The client should never freeze, even if the server is behaving incorrectly. Ideally, the client should support bulk upload. As the very minimum – for example, if the origin error is on the server side –, it should fall back to normal upload.

### Which files are affected by this bug

–

### Operating system

Linux

### Which version of the operating system you are running.

openSUSE Tumbleweed

### Package

Distro package manager

### Nextcloud Server version

25.0.0.18

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{
   "app" : "webdav",
   "exception" : {
      "Code" : 500,
      "CustomMessage" : "Unknown error while seeking content",
      "Exception" : "Sabre\\DAV\\Exception",
      "File" : "/data/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php",
      "Line" : 111,
      "Message" : "Unknown error while seeking content",
      "Trace" : [
         {
            "class" : "OCA\\DAV\\BulkUpload\\MultipartRequestParser",
            "file" : "/data/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php",
            "function" : "isAt",
            "line" : 129,
            "type" : "->"
         },
         {
            "class" : "OCA\\DAV\\BulkUpload\\MultipartRequestParser",
            "file" : "/data/nextcloud/apps/dav/lib/BulkUpload/BulkUploadPlugin.php",
            "function" : "isAtLastBoundary",
            "line" : 71,
            "type" : "->"
         },
         {
            "class" : "OCA\\DAV\\BulkUpload\\BulkUploadPlugin",
            "file" : "/data/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "function" : "httpPost",
            "line" : 89,
            "type" : "->"
         },
         {
            "class" : "Sabre\\DAV\\Server",
            "file" : "/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "function" : "emit",
            "line" : 472,
            "type" : "->"
         },
         {
            "class" : "Sabre\\DAV\\Server",
            "file" : "/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "function" : "invokeMethod",
            "line" : 253,
            "type" : "->"
         },
         {
            "class" : "Sabre\\DAV\\Server",
            "file" : "/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "function" : "start",
            "line" : 321,
            "type" : "->"
         },
         {
            "class" : "Sabre\\DAV\\Server",
            "file" : "/data/nextcloud/apps/dav/lib/Server.php",
            "function" : "exec",
            "line" : 360,
            "type" : "->"
         },
         {
            "class" : "OCA\\DAV\\Server",
            "file" : "/data/nextcloud/apps/dav/appinfo/v2/remote.php",
            "function" : "exec",
            "line" : 35,
            "type" : "->"
         },
         {
            "args" : [
               "/data/nextcloud/apps/dav/appinfo/v2/remote.php"
            ],
            "file" : "/data/nextcloud/remote.php",
            "function" : "require_once",
            "line" : 167
         }
      ],
      "exception" : {},
      "message" : "Unknown error while seeking content"
   },
   "level" : 3,
   "message" : "Unknown error while seeking content",
   "method" : "POST",
   "remoteAddr" : "*****",
   "reqId" : "Qrxj5bFNAAPoYgTYGy9B",
   "time" : "2022-10-25T13:43:09+00:00",
   "url" : "/cloud/remote.php/dav/bulk",
   "user" : "*****",
   "userAgent" : "Mozilla/5.0 (Linux) mirall/3.6.1git (Nextcloud, opensuse-tumbleweed-6.0.2-1-default ClientArchitecture: x86_64 OsArchitecture: x86_64)",
   "version" : "25.0.0.18"
}
```

### Additional info

Under “Is this bug present after an update or on a fresh install?” I had to select something, although I did not update the client.

**Comment by appliedbarrel** [comment]
Looks like the same issue: #4106
I also just had it crop up again too

**Comment by mgallien** [comment]
@RainerKlute would you be able to share your logs ?
The error you report while in need of a fix should not cause such a big use of CPU.

**Comment by EVOTk** [comment]
Hello,
Thanks for creating this ticket, I have the same problem but with a cpu load of about 15/16%.

The addition of "'bulkupload.enabled' => false," in config.php solved my problem.

![image](https://user-images.githubusercontent.com/45015615/198352222-cfbb5813-f738-4190-aebe-14206313f62e.png)

like this: https://github.com/nextcloud/desktop/issues/5031

**Comment by PVince81** [comment]
I was able to sync a lot of files these days with desktop client 3.6.1 on openSUSE Tumbleweed 20221003 and Nextcloud 25.0.1 RC1.

However, after having synced a lot of files it's now stuck at 100%.
I see the UI saying it's going to sync about 111 kb of files.
The log only says this:
```
#=#=#=# Syncrun started 2022-10-31T21:55:05Z
#=#=#=#=# Propagation starts 2022-10-31T21:55:07Z (last step: 1771 msec, total: 1771 msec)
```

the nextcloud.log has this message:
```
{"reqId":"Y2BEO2rciF3muyD7udwG9AAAAAA","level":3,"time":"2022-10-31T21:55:17+00:00","remoteAddr":"85.95.203.93","user":"vincent","app":"webdav","method":"POST","url":"/remote.php/dav/bulk","message":"Unknown error while seeking content","userAgent":"Mozilla/5.0 (Linux) mirall/3.6.1git (Nextcloud, opensuse-tumbleweed-5.19.13-1-default ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.1.0","exception":{"Exception":"Sabre\\DAV\\Exception","Message":"Unknown error while seeking content","Code":500,"Trace":[{"file":"/var/www/html/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php","line":129,"function":"isAt","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/BulkUpload/BulkUploadPlugin.php","line":71,"function":"isAtLastBoundary","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPost","class":"OCA\\DAV\\BulkUpload\\BulkUploadPlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":171,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php","Line":111,"message":"Unknown error while seeking content","exception":{},"CustomMessage":"Unknown error while seeking content"}}
```

Basically: when I start the desktop client again, first I see the above message and then suddenly it's 100% CPU on the client side.
Maybe it's not dealing with this error correctly ?
Also unsure why there would be such error on the server side ?

Let me know where I should look if there's a way to provide more information.

@artonge @mgallien

**Comment by PVince81** [comment]
I've just tried to make the server return a clean 400 Bad Request but the client still stucks at 100% CPU, so perhaps the error handling there has some issue or infinite loop of sorts.

The server side error seems to be about some problem in the multi part request.

Ah, and I just noticed that today I enabled the upload speed limitation and that it was reported to cause trouble also in the original report. @mgallien

**Comment by PVince81** [comment]
I've restarted the client, paused the sync, then removed the upload and download speed limit, then resumed sync: no more issues

maybe there's something odd with the combination of bulk upload and upload speed limit
I hope the speed limit implementation itself isn't somehow truncating multipart requests ?

**Comment by artonge** [comment]
The server is failing when trying to seek the stream backward. Two possibilities:

1. Somehow, the stream content is not accessible anymore, not sure why this could happen.
2. The `fread` call does not return `false` when reading further than EOF, but the `fseek` call return `-1` when seeking back to an inaccessible offset.

**Comment by PVince81** [comment]
from my experience, doing an fseek backwards is often not a good idea as it can break on streams (not files)

**Comment by Nowaker** [comment]
Same thing here. Using Mac OS client.

**Comment by RobertGleaden** [comment]
Same, CPU & RAM usage are really high and I just get 
"Network Error: 99" aswell

**Comment by Devonavar** [comment]
I'm also affected after upgrading to Nextcloud 25.  Can confirm that disabling "upload limiting" in the desktop client makes this bug go away (but it then hoses my upload bandwidth to the point of making downloading impossible whenever I have a large upload).

NextCloud 25.0.1
Desktop Client Version 3.5.4 (Ubuntu)
Ubuntu 20.04

**Comment by SebastianBerlin** [comment]
Any updates to this? Even in v3.6.2 the errors occur.

**Comment by avatar1024** [comment]
I can reproduce this bug and can confirm that removing the speed limit solves it. It is the combo of bulk upload + speed limits that cause this issue but it "just" looks like a bug in the client and server side the files had synchronised properly, still the client hangs with high cpu use.

**Comment by mayonezo** [comment]
I can confirm this issue and the solution of setting the Bandwidths to "No limit" on Debian Bullseye.

**Comment by pchesneau** [comment]
Hello! 
I confirm the issue and the solution (disable bandwith limit") on Windows 10 21H2 with nextcloud client 3.6.2 and nextcloud 25.0.1.

**Comment by mrothauer** [comment]
> Hello! I confirm the issue and the solution (disable bandwith limit") on Windows 10 21H2 with nextcloud client 3.6.2 and nextcloud 25.0.1.

same here - solved the issue for me

**Comment by zeus86** [comment]
can confirm the issue on ubuntu 20.04 with client 3.5.4 (x86_64), when bw-limits are in place.
I can also confirm, that it is server-dependant. i have 2 NC-Servers hooked up to my client. one with NC25, one with NC23. Neither of those have anything configured regarding bulk-uploads, but the Client only locks up, when a file would be synced to the NC25-Server (just a plain textfile of a few kB, nothing that would've been complicated to seek).

**Comment by hussong** [comment]
I can confirm the issues on Ubuntu Mate 22.04 with the default client from the sources as well as the most recent version (3.6.2) from `ppa:nextcloud-devs/client`. Issues started happening once the server was updated to 25.0.1.

Disabling the bandwidth limits made the client sync again. 

At first, I couldn't access the settings in the GUI, because it would freeze right after (re-)starting the client. So, to get to the settings, I edited the config file `.config/Nextcloud/nextcloud.cfg` where I set `0\Folders\1\paused=false` to `0\Folders\1\paused=true`. With the client launching in paused mode, I could access settings and disable the bandwidth limit in the GUI. Then I hit play and it synced fine.

**Comment by zeus86** [comment]
> I can confirm the issues on Ubuntu Mate 22.04 with the default client from the sources as well as the most recent version (3.6.2) from `ppa:nextcloud-devs/client`. Issues started happening once the server was updated to 25.0.1.
> 
> Disabling the bandwidth limits made the client sync again.
> 
> At first, I couldn't access the settings in the GUI, because it would freeze right after (re-)starting the client. So, to get to the settings, I edited the config file `.config/Nextcloud/nextcloud.cfg` where I set `0\Folders\1\paused=false` to `0\Folders\1\paused=true`. With the client launching in paused mode, I could access settings and disable the bandwidth limit in the GUI. Then I hit play and it synced fine.

That's how i solved it, too.

**Comment by pierr0t** [comment]
Hello,
I see the same problem on MacOS Ventura with client 3.6.2 accessing a v25.0.1 server and the `'bulkupload.enabled' => false,` solution seems to fix it, at least for the last 10 min (client has been stuck for the last 24h).
For ref: https://help.nextcloud.com/t/macos13-1-ventura-ncclient-3-6-2-hang-does-not-respond-no-sync/150338/7
Pierre

**Comment by bugsyb** [comment]
Got into same problem too with upgrade to server side v25.
Tested multiple versions across Linux and Windows and found out that there's version of desktop client which works without disabling anything on server or client side (throttling).
```
Nextcloud version 3.3.6git (build 7957)
Git revision 6d3270dd251db42293233d5622a610ea172dabef
Using Qt 5.12.10, built against Qt 5.12.10
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1k  25 Mar 2021'
Running on Linux Mint 20.3, x86_64

```

**Comment by janvlug** [comment]
I can confirm this issue in Nextcloud Desktop 3.6.1-1.fc37 and the solution of setting the Bandwidths to "No limit" on Fedora 37.

**Comment by jeffglancy** [comment]
I have been chasing my tail on this one for over a week. I though for sure it was an issue with the new server I spun up as I had no issue with my old server also running NC 25. If there was nothing new to sync, the Windows client (3.6.2) would be happy. As soon as I added/modified any size file it would become unresponsive, use up a CPU core, and prevent right clicks in Windows Explorer. Once I found this thread, I removed the clients upload limit setting, and it functions normally.

**Comment by RainerKlute** [comment]
Removing the client’s upload limit setting, as many here suggested, is clearly a workaround, but I wouldn’t call it a _solution_.

Whether the bug is on the server side or the client side can be answered easily: The client should **never** behave like this, _no matter how badly the server acts._

**Comment by Nowaker** [comment]
> The client should never behave like this, no matter how badly the server acts.

Doch!

**Comment by Hightmar** [comment]
I just added the line `'bulkupload.enabled' => false,` on the server and it seems to fix the problem. Unlike many of you I had no bandwidth limitation on the Windows 10 client. 

The only "unusual" thing is that I sent almost 35GB of data, composed of several thousand files.

**Comment by ebastler** [comment]
I set up a fresh instance of nextcloud today and encountered the same issue while uploading ~20 GB of data. First 18 GB consisted mostly of large files and worked well, then 2 GB of tiny files locked my client up with error 99.

Adding `'bulkupload.enabled' => false,` fixed it. Upload finished without anymore issues.

**Comment by terbin** [comment]
Can confirm, have the same issue with NextCloud 25.0.2 and Windows Client 3.6.4.

I do have limit upload bandwith enabled.
Once I cut my network, started the client and disabled the upload limitation on the client, it works for now. 2nd time this happens.

**Comment by kftX** [comment]
Am running NC 25.0.2, was also running into this issue. Never turned on the "upload limits option" but can confirm that adding `'bulkupload.enabled' => false,` on my _config.php_ also fixed this issue.

Thanks everyone who has contributed on this thread!

**Comment by pablosavigne** [comment]
This is a Huge problem, I hope the NC team, can solve this in future updates. `'bulkupload.enabled' => false,` is the solution at now!

**Comment by RainerKlute** [comment]
> This is a Huge problem, I hope the NC team, can solve this in future updates. `'bulkupload.enabled' => false,` is the solution at now!

It’s not a solution, only a workaround.

**Comment by pablosavigne** [comment]
Right @RainerKlute

**Comment by ebastler** [comment]
I wonder by how much this workaround will slow down uploads of lots of small files - uploading my 2 GB of tiny files took a long time, while having a GigE connection straight to the NC machine. It's okay for now, but definitely something I'd like to get rid of asap.

**Comment by pablosavigne** [comment]
> I wonder by how much this workaround will slow down uploads of lots of small files - uploading my 2 GB of tiny files took a long time, while having a GigE connection straight to the NC machine. It's okay for now, but definitely something I'd like to get rid of asap.

Depending your server and network speed, also I uploaded 190GB just in est. 24h, more than 40k items, gigabit client = server

**Comment by terbin** [comment]
Whenever this happened, I seem to have this in my server log:
[webdav] Error: Sabre\DAV\Exception: Unknown error while seeking content at <<closure>>

0. /var/www/html/apps/dav/lib/BulkUpload/MultipartRequestParser.php line 129
   OCA\DAV\BulkUpload\MultipartRequestParser->isAt("--boundary_.oOo ... n")
1. /var/www/html/apps/dav/lib/BulkUpload/BulkUploadPlugin.php line 71
   OCA\DAV\BulkUpload\MultipartRequestParser->isAtLastBoundary()
2. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   OCA\DAV\BulkUpload\BulkUploadPlugin->httpPost(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
   Sabre\DAV\Server->emit("method:POST", [Sabre\HTTP\Requ ... }])
4. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
5. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
   Sabre\DAV\Server->start()
6. /var/www/html/apps/dav/lib/Server.php line 360
   Sabre\DAV\Server->exec()
7. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
8. /var/www/html/remote.php line 171
   require_once("/var/www/html/a ... p")

POST /remote.php/dav/bulk
from 172.22.0.4 by terbin at 2022-12-20T22:06:56+00:00

**Comment by rayheffer** [comment]
Same here on a new install of Nextcloud 25, syncing 1TB of data.

Client 3.6.4 (Windows)
Server 25.0.2
Host: Ubuntu 22.04 (VM)

I didn't have any bandwidth limits in place, so I've added `bulkupload.enabled' => false,` to `config.php`, restarted Apache, and it now appears to be working without freezing.

**Comment by barkawa** [comment]
Can confirm, same issue on

Host: macOS 12.6
Client 3.6.4git (build 12826)
Server 25.0.1

CPU is at 100%, Memory slowly rising (6GB is the most I've seen so far)

Analysis: [nextcloud_analysis.txt](https://github.com/nextcloud/desktop/files/10320547/nextcloud_analysis.txt)
Spindump: [nextcloud_spindump.txt](https://github.com/nextcloud/desktop/files/10320545/nextcloud_spindump.txt)
Debug Archive: [https://0x0.st/oRHx.zip](https://0x0.st/oRHx.zip)

The main thread is constantly running either `OCC::ProgressInfo::setProgressItem()` or `OCC::ActivityListModel::addErrorToActivityList()`

The app occasionaly unfreezes, showing some failed transfers with "Network Error 99" and promptly freezing again.
The web interface admin panel shows no logs.

Hope this helps.

**Comment by barkawa** [comment]
Is there any way of editing the `config.php` without root access to the server? I'm using a managed NC provider.

**Comment by Dronarg** [comment]
Hello,

I have the same problem with a fresh install of nextcloud.
But adding the workaround line in config.php  bulkupload.enabled' => false, ends up with an error and the server stops working..

**Comment by lakoliu** [comment]
After adding `'bulkupload.enabled' => false,` I get the error `Configuration was not read or initialized correctly, not overwriting /var/www/html/config/config.php`. What am I doing wrong? I added the line to the end of the config.php file (before the last `);`).

**Comment by vitobotta** [comment]
Adding myself to the list of people who disabled the bulk uploading as a workaround. Hope it gets fixed soon!

**Comment by MarcSeebold** [comment]
I can confirm that disabling the bulk upload fixed it for me. Nextcloud snap version 25.0.2snap1.

**Comment by giteichi** [comment]
I also can confirm that disabling bulk upload is working.

Server: 25.0.2
Client: 3.6.4 (Debian/ debian-5.10.0-8-amd64)

**Comment by hodgeslo** [comment]
**First signs of a problem:**
Nextcloud Sync Client froze when **any** change was made to the Nextcloud data directory that required an upload to the server.
Server log:  Sabre\DAV\Exception: Unknown error while seeking content


**Workaround:**
As others have done, disabling the bandwidth upload limits made the client sync again without freezing.

**Other details:**
Client OS: Windows 10
Server OS: Ubuntu 22.04.1 LTS
Nextcloud Hub 3 (25.0.3)
Nextcloud-3.6.4-x64

**Comment by JustinBack** [comment]
Got this issue as well, disabling bulkupload did fix it though, bandwidth limit was never turned on

**Comment by haydnjonesdesign** [comment]
Jumping in on this bug. Receiving the same issue on:

Host: macOS 12.6.2
Client 3.6.6 (macOS)
Server 25.0.3

I've disabled limit bandwidth as a temporary solution as suggested.

**Comment by wazhanudin** [comment]
Thanks for sharing this. 

`'bulkupload.enabled' => false,`

It's working now.

Host: Debian 11
Client: 3.6.6 (Windows)
Server: 25.0.3

**Comment by DL4AX** [comment]
Same issue. `'bulkupload.enabled' => false,` helped.

Host: macOS 13.2
Client: 3.6.6 (macOS)
Server: 25.0.3

**Comment by Bunyano** [comment]
I've been at this for weeks! Had an NGINX reverse proxy so assumed it was to do with that, removed it but problem still there. 

Install was fresh 25.0.3 on TrueNAS Scale with Windows 11 and 3.6.6 client. 

Then assumed it was Windows 11 incompatibility with the client, so spun up a Windows 10 VM. Same issue. 

Then tried pulling latest docker image, ran that locally and same issue!

Host: Windows 10 Home 22H2 | Windows 11 Pro 22H2
Client: 3.6.6 (Windows)
Server: 25.0.3

`'bulkupload.enabled' => false,` fixed it. Didn't have any upload/download limits configured in the client at any point.

**Comment by Clonkex** [comment]
New Nextcloud user here. I thought for sure I'd screwed something up somehow, even though I previously used Owncloud for many years. Very relieved to see it's not just me, not so excited to see it's been a bug for multiple months already 😐 

I previously had the speed limiter set manually (as in, to a specific KB/s) but disabling it has no effect. The GUI still locks up almost immediately. I have enough time to pause the sync (which prevents the GUI from freezing) but not much more.

For reference, I'm on Windows 10 and just downloaded the Nextcloud client today (3.6.6). The server is Ubuntu 22.04 LTS with NC installed via [the snap](https://github.com/nextcloud-snap/nextcloud-snap) (so NC 25, I assume).

Unfortunately, because it's installed via the snap I believe I'm unable to simply edit the config like normal. I'm not familiar with snaps so I can't say whether there's some other directory I can look under for the config, but I'm assuming since they're sandboxed it's probably not that easy. Googling hasn't produced any snap-specific instructions that I can find.

I'll stick with my old (and probably insecure) installation of Owncloud for now.

**Comment by itProfi** [comment]
[Nextcloud Hub 3](https://nextcloud.com/) (25.0.3) - same issue. Wth 'bulkupload.enabled' => false, - work all fine.

**Comment by MarcSeebold** [comment]
> New Nextcloud user here. I thought for sure I'd screwed something up somehow, even though I previously used Owncloud for many years. Very relieved to see it's not just me, not so excited to see it's been a bug for multiple months already 😐
> 
> I previously had the speed limiter set manually (as in, to a specific KB/s) but disabling it has no effect. The GUI still locks up almost immediately. I have enough time to pause the sync (which prevents the GUI from freezing) but not much more.
> 
> For reference, I'm on Windows 10 and just downloaded the Nextcloud client today (3.6.6). The server is Ubuntu 22.04 LTS with NC installed via [the snap](https://github.com/nextcloud-snap/nextcloud-snap) (so NC 25, I assume).
> 
> Unfortunately, because it's installed via the snap I believe I'm unable to simply edit the config like normal. I'm not familiar with snaps so I can't say whether there's some other directory I can look under for the config, but I'm assuming since they're sandboxed it's probably not that easy. Googling hasn't produced any snap-specific instructions that I can find.
> 
> I'll stick with my old (and probably insecure) installation of Owncloud for now.
> 
> **EDIT:** Actually nevermind, I realised that the snap's readme explains that the config can be edited at `/var/snap/nextcloud/current/nextcloud/config/config.php`. After adding `'bulkupload.enabled' => false,` I can confirm my client GUI no longer freezes (at least so far, after 30 seconds of watching it syncing).

Try editing "/var/snap/nextcloud/current/nextcloud/config/config.php".

**Comment by mayonezo** [comment]
Is this a duplicate of #4106? Should the two be merged?

**Comment by ebastler** [comment]
Is there any news? This bug has been going on for about 3 months now, with tens of users reporting in. Disabling speed quotas only works for some, while others get the issue even without any limiters set. Disabling bulk upload makes the cloud extremely slow when uploading large amounts of small files, which is a relevant usecase for many, among them me.

These "fixes" the users came up with are workarounds at best, each costing functionality. Would be nice to get some rough ETA for a fix, or at least a "we're working on it", to be honest.

I'm sorry if I sound rude - I know this is a community driven free software, and many people are working on it in their spare time, but this is a big bug, and some sort of official statement would be much appreciated.

**Comment by Hightmar** [comment]
> Is this a duplicate of #4106? Should the two be merged?

In [#4106](https://github.com/nextcloud/desktop/issues/4106) I did not see the "solution" proposed here, I left a comment. 

@mgallien approved the bug here

@ebastler I haven't seen any particular news and I quite agree with you. Even if this fix doesn't have any impact on my use it's still annoying.

**Comment by mayonezo** [comment]
@ebastler If this is a duplicate indeed, the bug has been around for over a year. And I could not agree more with your points.
@Hightmar Thanks for posting the workaround on issue #4106. Although the original author in issue #4106 could not reproduce the issue with newer Nextcloud Desktop releases anymore, there are still people posting in that issue thread.

**Comment by cjdg** [comment]
Can confirm, even on 3.7.1, the fix solves the problem

**Comment by mattdev44** [comment]
I am also having the same issue with Mac OS client, NC Server version 25.0.3 and NC Client 3.7.3. Changing 'bulkupload.enabled' => false in config.php workaround stops my CPU from spiking. Interested on a permanent fix. ETA?

**Comment by mxwmnn** [comment]
Same issue with NC 25.0.3 and NC Client 3.6.6 and 3.7.3. Both Linux and Windows Clients. Linux Flatpak and Linux Snap.
Very annoying, hope will be fixed soon!

**Comment by czen** [comment]
Encountered the same issue on Windows 10, NC Server 25.0.3, Client 3.7.3. 'bulkupload.enabled'=>false stops the issue from occuring.
The issue causes NC Client to hang in an infinite loop in the middle of sync. It consumes entire CPU core, causes explorer extension to hang as well, so the explorer itself hangs up if you try to use context menu.
This issue currently makes latest version NC completely unusable for me without the workaround.

**Comment by alessandrozigliani** [comment]
> Encountered the same issue on Windows 10, NC Server 25.0.3, Client 3.7.3. 'bulkupload.enabled'=>false stops the issue from occuring. The issue causes NC Client to hang in an infinite loop in the middle of sync. It consumes entire CPU core, causes explorer extension to hang as well, so the explorer itself hangs up if you try to use context menu. This issue currently makes latest version NC completely unusable for me without the workaround.

Same issue here, same client version, same solution.
I manage to narrow it down to the fact that the users had some .~lock.* files around because of LibreOffice crash (or intentional forced shutdown while documents were open). After the workaround, an error immediately comes up because the file seems to be in use, but synchronization proceed. Then you can workaround again by inserting ".~lock.*" into the list of files to ignore.

**Comment by pelzvieh** [comment]
To find the bug, the question is: where do bulk upload and rate limiting meet in the client?
Rate limiting: https://github.com/nextcloud/desktop/blob/master/src/libsync/bandwidthmanager.cpp
Bulk upload: https://github.com/nextcloud/desktop/blob/master/src/libsync/putmultifilejob.cpp
They meet in the "Device" generated for each uploaded file and which are "choked" by the bandwidth manager.
What appears suspicious: the bandwidth manager is distributing a byte quota per second on all registered devices. 

However, the dozens of devices registered for one bulk upload become active only one after each other when their respective body part is due to be transferred, right?

The "choking" state of an UploadDevice is realized by immediately returning 0 bytes on read: https://github.com/nextcloud/desktop/blob/master/src/libsync/propagateupload.cpp

It seems plausible to me that the only UploadDevice that actually is queried by the upload process receives only a fraction of the intended quota and busily loops once that quota is exceeded until the next time slice?

**Comment by mschoettle** [comment]
Can confirm on macOS Mojave, Nextcloud 3.7.3 and NextCloud Server 25.0.3.

Steps to workaround:

1. Disable network (e.g., Wifi)
2. Start NextCloud Desktop
3. Go into settings > Network and set bandwith limits to "no limit"
4. Enable network

**Comment by pailloM** [comment]
Same issue with in docker with:
Image 25.0-apache, and nextcloudcmd 3.7.3 as client on ubuntu 22.04
 
'bulkupload.enabled'=>false in config.php resolved the issue

**Comment by Hyperspeed1313** [comment]
Windows Desktop client. Server version 25.0.4. Error 99 until I set 'bulkupload.enabled'=>false in config.php

**Comment by spookyrecharge** [comment]
Is there any way to mount nextcloud storage as a network drive on windows 10/11 just to avoid using this app?

**Comment by Hightmar** [comment]
> Is there any way to mount nextcloud storage as a network drive on windows 10/11 just to avoid using this app?

I don't really understand your question? 
You can make a Samba share to mount the folder directly on Windows, but you lose the very interest of Nextcloud.

**Comment by spookyrecharge** [comment]
> > Is there any way to mount nextcloud storage as a network drive on windows 10/11 just to avoid using this app?
> 
> I don't really understand your question? You can make a Samba share to mount the folder directly on Windows, but you lose the very interest of Nextcloud.

webdav, winfsp

**Comment by ebastler** [comment]
> Is there any way to mount nextcloud storage as a network drive on windows 10/11 just to avoid using this app?

You should be able to do a WebDAV mount - that should give you nextcloud sync but without the app, and ofc without a bunch of the comfort features. But it should work. Never tried myself though.

**Comment by spookyrecharge** [comment]
> > Is there any way to mount nextcloud storage as a network drive on windows 10/11 just to avoid using this app?
> 
> You should be able to do a WebDAV mount - that should give you nextcloud sync but without the app, and ofc without a bunch of the comfort features. But it should work. Never tried myself though.
> 
> Sadly the app feels quite janky and dated compared to the Amazing webgui/server, I hope we'll see some more focus on app updates some day. Mine keeps doing weird things recently, in addition to this bug that still persists after months

Same feelings. At first I thought that I've got a virus because my system was completely unresponsive (90% cpu load on 8700k) and this is because of this app lol

**Comment by willemb2** [comment]
We ran into this problem with a fresh install of server 25.0.4 on Ubuntu 22.04 LTS and the Windows client v 3.7.4. `'bulkupload.enabled'=>false` in config.php as suggested above resolved the issue but I have no idea what the side effects could be. Is this related [File bulk upload](url=https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/bulkupload.html) API in the docs? A side effect noticable to me is that the tray icon in Windows is blinking now between Syncing/successfull about once per second.

**Comment by mightymt** [comment]
I experienced this problem for the first time yesterday.

Setting the bandwidth to "No limit" in the client seems to have fixed it for me.

Client version: 3.7.4 on Windows 10 22H2 (Build 19045.2728)
Server version: 25.0.4

**Comment by Excel1** [comment]
Hello!

Im using Ubuntu 22.04. LTS with the latest nextcloud client version and experienced the same problem. I got this issue also on W10 / W11 - https://github.com/nextcloud/desktop/issues/3937#issuecomment-1477621913

Thx for the workaround @mightymt - this lets me sync now (on Ubuntu - Windows not tried yet)

**Comment by muonicpress** [comment]
Still seeing this issue using 26.0.0 in a Truenas plugin, combined with Win 10 and 3.8.0. Disabling bulk upload in the Nextcloud config.php has caused my uploads to drastically slow down due to not having bulk uploads, but they're actually uploading instead of causing the client to die.

**Comment by aixzellent** [comment]
Same issue with 

server:
ubuntu 20.04 LTS
snap nextcloud 25.0.4
client:
ubuntu 20.04 LTS
client 3.5.4 (ppa package)

both solutions solved my problem:
'bulkupload.enabled'=>false 
or disable upload limit in client network config

**Comment by Cris70** [comment]
Same issue here

Server: 
Rocky Linux 9.1
Nextcloud 25.0.6

Client:
Opensuse Tumbleweed
Nextcloud client 3.8.1

Disabling speed limits on the client solved the issue. No changes server-side.

**Comment by zgqq** [comment]
Any news on this?

**Comment by zizzithefox** [comment]
> Is there any way to mount nextcloud storage as a network drive on windows 10/11 just to avoid using this app?

Not a question very related to the bug. However there are windows app that allow easy mount/unmount like Raidrive and Webdrive, but they are not free. Sometimes I use Raidrive because it's free, if you can tolerate the ads.

**Comment by ebastler** [comment]
> Not a question very related to the bug. However there are windows app that allow easy mount/unmount like Raidrive and Webdrive, but they are not free. Sometimes I use Raidrive because it's free, if you can tolerate the ads.

https://docs.qnap.com/operating-system/qts/4.5.x/en-us/GUID-31D5B05F-F29E-4D61-9758-C8CF839C14FD.html

IMO this should work with Nextcloud, but I never tested.

**Comment by KaeTuuN** [comment]
@zizzithefox **Never ever do that!**
Nextcloud does way more than simple Mount a drive to copy some files!

**Comment by zizzithefox** [comment]
> @zizzithefox **Never ever do that!** Nextcloud does way more than simple Mount a drive to copy some files!

I don't know what you are talking about. However, if webdav operations are a problem, nextcloud should remove that possibility or warn about it. Never had any problem though, because the only reason I use nextcloud for is sharing personal documents with myself or read only to other people. Can you please point me to the documentation that says webdav mounting nextcloud folder is a problem please?

**Comment by mgallien** [comment]
Fix has been released in 3.9.0 (see https://github.com/nextcloud/desktop/pull/5680)

**Comment by corincorvus** [comment]
Not fixed in 3.9.0
![image](https://github.com/nextcloud/desktop/assets/21257329/38780e6f-3874-4873-bdf0-bfdfe1f0764f)
![image](https://github.com/nextcloud/desktop/assets/21257329/8f0aaeb1-e5ef-44f3-96ce-547fe77b4799)

Error and App freeze:
![image](https://github.com/nextcloud/desktop/assets/21257329/d4e3ab59-0e24-4c9d-b6e4-b13c366eb154)

Well known works correctly

**Comment by jcjveraa** [comment]
@corincorvus this is quite different from what I experienced with this bug - for me the app became totally unresponsive and no type "99 network error messages" were generated. Can you confirm this is the same issue / solvable by disabling bulk uploads?

**Comment by ByMynix** [comment]
@corincorvus @jcjveraa  I can confirm it too. I had the same issue today, first time sync for nextcloud. I had the problem with network error 99. I disabled speed limits = no success, I tried to disable bulk uploads on server-side and now it's working fine. I also used the newest version 3.9.0

**Comment by Amasis** [comment]
@jcjveraa , I can confirm what @corincorvus  observes, and the workaround `'bulkupload.enabled' => false,` fixes it.

- Desktop-Client Version 3.9.0, same settings as in the screenshots and "Netzwerkfehler: 99".

On my side the client is not absolutely unresponsive/frozen but takes about 30 seconds to react to any input. I was able to pause the sync before closing the client, but it took its time...

**Comment by jcjveraa** [comment]
Ok, maybe the solution provided in 3.9.0 then did indeed do something as the error 99 seems to be new, but it didn't fully solve the issue.I'm not an active developer here by the way, just one of the earlier people involved in providing info for this issue to be solved. A dev should probably decide to reopen this or create a new one based on your reports.Op 15 jul. 2023 om 12:48 heeft Marc ***@***.***> het volgende geschreven:﻿
@jcjveraa , I can confirm what @corincorvus  observes, and the workaround 'bulkupload.enabled' => false, fixes it.

Desktop-Client Version 3.9.0, same settings as in the screenshots and "Netzwerkfehler: 99".

On my side the client is not absolutely unresponsive/frozen but takes about 30 seconds to react to any input. I was able to pause the sync before closing the client, but it took its time...

**Comment by RainerKlute** [comment]
I just tested it: Looks good! Thanks for the fix!

**Comment by alerque** [comment]
I regret to have to say this but I'm pretty sure this is *not* fixed. It took a while for me to end up with systems where *BOTH* the client and server sides did not have workarounds in place for this (disabled bulk uploads in server side, patched clients downstream, etc.) but now that I have all workarounds removed and bulk uploads enabled both server and client side I started seeing this again. I disabled bulk uploads on the server side and the clients are back to functional.

**Comment by corincorvus** [comment]
Same.

With the Workarounds uploads are very Slow too.

**Comment by pelzvieh** [comment]
Please understand that the "fix" is absolutely equivalent to setting Download -> Bandwidth and Upload -> Bandwidth to "no limit" in previous versions of the client – if used with servers with bulk transfer enabled. If these settings don't help with a certain problem, the fix won't either. If a bandwidth limit appears necessary, be prepared that with the fix you'll see the network congestion you tried to avoid.

**Comment by Simon1V** [comment]
Version 3.7.3  snap 
in  config.php I set
'bulkupload.enabled' => false
fixed the errorcode 99 errors. 
That being said, the transfer of files (from NVME SSD to NVME SSD on the same motherboard) is still slow

**Comment by griffi-gh** [comment]
Was getting the same issue, the solution is to disable automatic speed limiting.

**Comment by quentinDupont** [comment]
> Was getting the same issue, the solution is to disable automatic speed limiting.

What is that ? and where do you disable it ? :) thank you !

**Comment by bugsyb** [comment]
@quentinDupont  - workaround is posted in the very first post - in `config.php`:
```'bulkupload.enabled' => false,```

With that said, the being on v27.1.2 (client 3.10.1 - Linux)), if there's a fix in the code, didn't work for me and if bulkupload is enabled client gets stuck (CPU 100%).

**Comment by cls-nebadje** [comment]
Problem persists on Nextcloud version 3.11.1-20240130.181818.c65a8fd6a-1.0~jammy1

**Comment by b-rad15** [comment]
Same issue, same fix. Windows 3.12.2

**Comment by rstockm** [comment]
I just ran into this issue:
Clean Install
Client Version 3.6.6 (macOS)
Nextcloud 29.0.2

Banwidt-Limnit was _never_ acive.
Adding 'bulkupload.enabled' => false, to the config.php fixed the issue, resulting in slower uploads.

I am quite shocked that such a substantial bug (unresponsive client app at 100%) is still around - after two years?!

**Comment by PhilippSchlesinger** [comment]
@rstockm 
The client version you use is nearly 1 1/2 years old, the recent version is 3.13.0.
You might want to check with this version that contains the fix mentioned in https://github.com/nextcloud/desktop/issues/5094#issuecomment-1620192817

**Comment by alerque** [comment]
@PhilippSchlesinger I don't know why @rstockm is running such an old client but this issue is still happening in 3.13.0. The fix mentioned as being in 3.9.0 never did work. Many people have confirmed the issue on versions since then.

**Comment by farvardin** [comment]
> @PhilippSchlesinger I don't know why @rstockm is running such an old client but this issue is still happening in 3.13.0. The fix mentioned as being in 3.9.0 never did work. Many people have confirmed the issue on versions since then.

I can confirm on Linux the 3.13.0 version is buggy and causes my computer to hang with 100% cpu load. It works fine with the 3.9.0 appimage 

https://github.com/nextcloud/desktop/issues/6749#issuecomment-2146266666

**Comment by kupietools** [comment]
> > @PhilippSchlesinger I don't know why @rstockm is running such an old client but this issue is still happening in 3.13.0. The fix mentioned as being in 3.9.0 never did work. Many people have confirmed the issue on versions since then.
> 
> I can confirm on Linux the 3.13.0 version is buggy and causes my computer to hang with 100% cpu load. It works fine with the 3.9.0 appimage
> 
> [#6749 (comment)](https://github.com/nextcloud/desktop/issues/6749#issuecomment-2146266666)

I have tried 3.3.4, 3.9, and 3.13.2 on Mac. They all have this showstopper bug. As near as I can determine, is no working NextCloud client for Mac, and nobody wants to admit it. 

Is this project abandoned? Why are issues going months without a response?

**Comment by alerque** [comment]
@kupietools You're being a bit rediculious, obviously with an ongoing string of releases this project is not abandoned. Some issues are just a bit miss-managed. For whatever reason nobody wants to own up to there being a bug here and just re-open the issue. Also if you actually read the comments before you you'll notice it is not a Mac issue and there is a work around.

Meanwhile you can use any client version you like just fine but you have to get your Nextcloud cloud instance admin (maybe that's yourself?) to add `'bulkupload.enabled' => false` to the server's `config.php`.

**Comment by ebastler** [comment]
> add `'bulkupload.enabled' => false` to the server's `config.php`.

Sadly that leads to a huge performance loss. I'm often syncing a bunch of tiny data around (target folder for scientific simulations with a lot of small results files) and even when synced directly over GigE in the same network, the workaround made syncing lots of small files very tedious.

**Comment by TheThief** [comment]
Yes, the workaround is very much suboptimal.

**Comment by alerque** [comment]
Yes, the work around is very much less than sub-optimal. But for most folks slow is better than 100% CPU usage and no functionality. I don't know how this hasn't hit any developers such that they would be motivated to actually chase it down, and I don't know enough about debugging the desktop app to track down the problem myself.

**Comment by RainerKlute** [comment]
The workaround was useful while it was needed. I reverted my Nextcloud instance back to ``'bulkupload.enabled' => true`` a year ago. So the bugs seems to be fixed, at least sort of. However, there seem to be some loose ends, affecting some people. :-(

**Comment by ebastler** [comment]
> I don't know enough about debugging the desktop app to track down the problem myself.

Same. I'd help if I could, but I really lack the skills for that, sadly.

**Comment by alerque** [comment]
@RainerKlute Clearly not everybody is affected (or developers would have given it more attention long ago) but also whatever the trigger is many people are still affected. I'm glad you are not, but that just suggests whatever the trigger scenario is is not being hit by you, not that the bug is fixed. Also what clients are you using? Besides the server-side work around the client can also be compiled without bulk upload support, and several distros do this. For example the Arch Linux has the feature patched out so that nobody on Arch Linux is likely to ever see this issue.

I've thought of re-enabling it to put pressure back on devs to find this problem, but I also don't want to deal with a bunch of bug reports and hassle for all Arch Linux users that would be negatively affected.

**Comment by ebastler** [comment]
Oh, now that explains why I only encountered it on Windows, not on Arch...

**Comment by alerque** [comment]
The nextcloud desktop client app on Arch Linux [has this monkey patch](https://gitlab.archlinux.org/archlinux/packaging/packages/nextcloud-client/-/blob/main/PKGBUILD?ref_type=heads#L72-L74) that changes the code that detects never capabilities to always report false for bulk upload. This makes it slower than necessary but keeps the client from freezing up. I've tried disabling it several times and not only my own systems but other reports of problems start flooding in.

**Comment by RainerKlute** [comment]
> Also what clients are you using? Besides the server-side work around the client can also be compiled without bulk upload support, and several distros do this.

I am using the Nextcloud client that comes with openSUSE Tumbleweed. Don’t know whether bulk upload is inhibited there or how to find out. The server is also running openSUSE Tumbleweed.

**Comment by alerque** [comment]
I just reviewed the sources for OpenSUSE Tumbleweed's Nextcloud [server](https://build.opensuse.org/package/show/openSUSE:Factory/nextcloud) and [desktop](https://build.opensuse.org/package/show/openSUSE:Factory/nextcloud-desktop) packages and it does *not* look like they have patched out bulk upload support on either side. Thanks an interesting data point but doesn't isolate what the unique factors are, and we know multiple host platforms and all of Windows/macOS/Linux clients are affected in some cases.

Do you by chance use any of the rate limiting features on the client? Those seem to be another way people work around triggering this bug.

**Comment by kupietools** [comment]
Thanks for responding, all.

Unfortunately my server is a Hetzner Storage Dhare, they've already passed the buck and told me that while I can continue to pay them, this is not their problem and they'll do nothing to help, and it's entirely up to me to convince the NextCloud devs to address the problem. However, I'll ask them if setting `'bulkupload.enabled' => false` is an option.

I did discover that the OwnCloud client works and appears not to freeze. However, while NextCloud told me (between freezes) to expect about a four-day wait to upload 400GB of files, OwnCloud wavered between 3-9 months for the same files, so this doesn't seem like a workable solution. I'd rather not wait the better part of a year for my first sync to finish. 

> Do you by chance use any of the rate limiting features on the client? Those seem to be another way people work around triggering this bug.

I've tried rate limiting both auto and off for download, for both NextCloud and OwnCloud clients. I am reluctant to turn rate limiting off for upload as this can easily slow up the machine's entire connection due to the back-and-forth packets needed just for downloading, but I'll give it a shot.

**Comment by pelzvieh** [comment]
Obviously, we're discussing something here that is different to the original bug reported, which is not the most effective thing to do.

My installation has been affected by the problem, and to cure that problem as originally reported it has been - and is - sufficient to switch Download and Upload bandwidth limit to "no limit" at the client. Though I'm [not a fan of the way it was fixed](https://github.com/nextcloud/desktop/issues/5094#issuecomment-1646823164), certainly this problem is fixed.

As you are experiencing problems with clients freezing with 100% CPU load, obviously it is a different problem and deserves a different report.

**Comment by TheThief** [comment]
> Obviously, we're discussing something here that is different to the original bug reported, which is not the most effective thing to do.
> 
> My installation has been affected by the problem, and to cure that problem as originally reported it has been - and is - sufficient to switch Download and Upload bandwidth limit to "no limit" at the client. Though I'm [not a fan of the way it was fixed](https://github.com/nextcloud/desktop/issues/5094#issuecomment-1646823164), certainly this problem is fixed.
> 
> As you are experiencing problems with clients freezing with 100% CPU load, obviously it is a different problem and deserves a different report.

I never used the rate limiting, the only thing that worked ever since it first happened has been to disable bulk upload on the server. It's definitely the same issue - bulk upload being enabled results in clients freezing while using 100% CPU. That's the same as the original.

**Comment by unterkomplex** [comment]
> Thanks for responding, all.
> 
> Unfortunately my server is a Hetzner Storage Share, they've already passed the buck and told me that while I can continue to pay them money, this is not their problem and they'll do nothing to help, and it's entirely up to me to convince the NextCloud devs to address the problem. However, I'll ask them if setting `'bulkupload.enabled' => false` is an option.
> 
> I did discover that the OwnCloud client works and appears not to freeze. However, while NextCloud told me (between freezes) to expect about a four-day wait to upload 400GB of files, OwnCloud wavered between 3-9 months for the same files, so this doesn't seem like a workable solution. I'd rather not wait the better part of a year for my first sync to finish.
> 
> > Do you by chance use any of the rate limiting features on the client? Those seem to be another way people work around triggering this bug.
> 
> I've tried rate limiting both auto and off for download, for both NextCloud and OwnCloud clients. I am reluctant to turn rate limiting off for upload as this can easily slow up the machine's entire connection due to the back-and-forth packets needed just for downloading, but I'll give it a shot. I did try turning the upload limiting off in OwnCloud to see if it made a difference in the speed, and it didn't seem to.
> 
> UPDATE: I let it run with the upload and download both not rate-limited, and it froze again inside of a few hours.

This won't fix any bugs in any way, but if you just want to run an initial sync of your data this is what worked for me with a Hetzner Share:
- Use rclone  to access the WebDAV interface of Nextcloud ( https://rclone.org/webdav/ )
- rclone sync your local directory to remote

**Comment by kupietools** [comment]
> This won't fix any bugs in any way, but if you just want to run an initial sync of your data this is what worked for me with a Hetzner Share:
> 
>     * Use rclone  to access the WebDAV interface of Nextcloud ( https://rclone.org/webdav/ )
> 
>     * rclone sync your local directory to remote

Thanks for the suggestion! I decided to pay for Hetzner's NextCloud hosting because I did look at just paying for cloud storage and using WebDAV to sync, and it wasn't going to work for my purposes.

**Comment by kupietools** [comment]
@unterkomplex  So, just to follow up, I did end up trying rclone, just to see if maybe, once one sync was done, maybe the owncloud client's slowness wouldn't be an issue in keeping everything up to date. 

The results:

1.) Through several days of crashes and manual restarts, the NextCloud client got me about 75% synced. That had taken a few days, including a lot of downtime when I didn't realize it was crashed. Last I looked, Rclone estimated it would take over a month to complete the final 25%. 

2.) I tried anyway and gave it about a week. Twice in that time, I looked and the command-line rclone client had aborted due to I/O errors. (BTW I'll spare you an exhaustive description of my network, but any configuration or connectivity problems on my computer or network would cause way more things going wrong than just one single app reporting errors and nothing else.) This isn't usable. 

I just canceled my Hetzner Storage Share account. I won't using NextCloud, since in several weeks of trying it hasn't worked for me at all and I haven't been able to find any sign at all that the devs have any interest in fixing the bugs. 

Thank you so much to the several people here who did reply here—I really appreciate your efforts to be helpful!

**Comment by farvardin** [comment]
@kupietools have you tried using an older nc client? The bug ceased to affect my server and computer whenever i was using an old client.

**Comment by lightlike** [comment]
@kupietools if you want to sync data and do not really care about a fast response time and you just want to keep the data up to date after the initial sync, then you should try looking at https://github.com/syncthing/syncthing.

I am currently using that as a backup solution for my rasberry pies to my storage server.
I also successfully used it to keep 2 NFS servers in sync at an old job with minimal missing data when the server would crash.
It would also start right back up after the crashed server would restart.

It might be a bit slow to start the sync but should handle your crashes fine. It will just wait until the connection is back.
You can also create a mesh of multiple devices and you have full control over the way everything is synced.

It is also very lightweight.

**Comment by christoph-buente** [comment]
I have the same problem with Hetzner Storage Share aka Nextcloud v30 and the latest Nextcloud client available via homebrew: `3.16.1`. As the StorageShare is fully managed by Hetzner, I have no control over the server settings whatsoever. 

It looks like, for many years people have been plagued with this issue and I'm wondering if there are any plans to reliably fix this issue in the client to deal with IO errors or whatever happens between server and client. But even when everything is synced, and no transfer is needed, I see the client getting into 100% CPU usage mode.

This issue was closed, but is there a solution out there that does not involve changing the server config?

**Comment by alerque** [comment]
@christoph-buente You can track this is #6990. The problem has finally been acknowledged but not actually tracked down or resolved ... for years now. Disabling the bulk upload feature on the server side or compiling your clients without the feature are the two ways to fix it. If you are the server admin, add that to your config.

**Comment by christoph-buente** [comment]
Thank you @alerque 
As I have no control over the server side, the only thing I can do is change my client config.

But the client goes into unresponsive mode 5 seconds after startup. So I changed the config file after it took me a while to find it. Leaving my workaround here, for other people to hopefully benefit:

On a Mac, the config files for the Nextcloud client are located under `$HOME/Library/Preferences/Nextcloud/nextcloud.cfg`
The file is separated into several section. Find the section starting with `[BWLimit]` and remove the values for `downloadLimit` and `uploadLimit` like this
```
[BWLimit]
downloadLimit=
uploadLimit=
useDownloadLimit=-1
useUploadLimit=-1
```

That is what helped me make the client survive for more than 5 seconds.
