### ISSUE TITLE
[Bug]: Virtual files thumbnails not working

### ISSUE THREAD

**Issue by ParisGreen** [nextcloud/desktop#5301]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

virtual files aren't showing thumbnails, even on files available locally

### Steps to reproduce

Enable Virtual Files on windows

### Expected behavior

Virtual files include thumbnails

### Which files are affected by this bug

birdie.jpg

### Operating system

Windows

### Which version of the operating system you are running.

10

### Package

Appimage

### Nextcloud Server version

24.0.5.1

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![Screenshot 2022-12-30 16 42 41](https://user-images.githubusercontent.com/8505474/210113585-b268c497-395e-4b3b-9e75-c10e998458e6.png) 
I'm not sure if this is a bug or if I set something up wrong, but I'm not seeing previews for virtual files anymore, even if they're saved locally. I could swear this wasn't the case previously, and it's a bit inconvenient to boot.

**Comment by ParisGreen** [comment]
![Screenshot 2022-12-30 22 41 59](https://user-images.githubusercontent.com/8505474/210123791-da77d7a8-68d6-4cfd-b97c-8b3bf155e324.png)
Just for reference, I tried reverting to client 3.5.2 and it behaves the way I'd expect with thumbnails. Hopefully that at least confirms it's a bug, and not user error.

**Comment by Moosetracks555** [comment]
If you copy a file that has a thumbnail into a nextcloud directory the thumbnail shows in the nextcloud directory until the file is synced.  As soon as the file syncs the thumbnail goes to a white page.   Has anyone found a work around for this?

**Comment by Leinad4Mind** [comment]
Any news? Same problem here. Very annoying.

**Comment by wonx** [comment]
I am also experiencing this bug.

**Comment by 3dK** [comment]
Same here with Version 3.9.0 (Windows).
Image thumbnails not showing, but showing for video files.

**Comment by sachz19** [comment]
Hi, experiencing the same issue on multiple clients on the latest agent version.

**Comment by git-kick** [comment]
+1   would greatly appreciate to see that one solved.

**Comment by PW87** [comment]
I´ve the same problem. I´m using Version 3.10.0 (Windows - enable support for virtual files). When I open a folder with imagefiles, I can see all the thumbnails first. A few seconds later the thumbnails disappear one by one. I hope the issue could be fixed soon.

**Comment by PhilippSchlesinger** [comment]
I confirm the same problem as described above by the reporter and those who commented.
I may be able to provide you with a workaround and an approach to the issue below.

In search of the root of the problem, I tried other steps first:
- I removed the relevant sync folder in the Nextcloud client and added it again. This completely recreated the placeholder files.
There was no change to the thumbnails issue.
- I cleared the thumbnail cache as described at https://www.tenforums.com/tutorials/5655-clear-reset-thumbnail-cache-windows-10-a.html.
This also resulted in no change to the thumbnails
- I have reinstalled the latest release of the Nextcloud client under the user account in question.
After the final necessary reboot and login, the thumbnails suddenly appeared, both for hydrated and for dehydrated files.
_**But this is still not the answer to the problem.**_

### Upon further testing I came to the following conclusion:
If there are multiple user accounts on the Windows system, thumbnails will be displayed in the account where the first login occurs. If there is a logout on the first user account, thumbnails will be displayed correctly after logging in again on the second account. If a second account is logged in parallel to the first, no thumbnails will be displayed there. If there is a logout on the first user account, thumbnails will be displayed correctly after logging out and in again on the second account.

**Comment by PhilippSchlesinger** [comment]
An additional note: It is sufficient to ensure that only one instance of Nextcloud is running at the same time on a Windows system.
Therefore, if you close the Nextcloud Client on a Windows account and then start the Nextcloud Client on a different account, the display of thumbnails will work there.
@ParisGreen, @PW87, @git-kick, @sachz19, @3dK, @wonx and others who confirmed that bug: could you please test and report back if that is a workaround for you?

@allexzander, @mgallien Does the issue relate to the way in which the thumbnail provider shell extension registers itself with Windows Explorer?

**Comment by sachz19** [comment]
Hi,

 

All systems I had the issue with only have a single user known on the system.
No other users running in the background.
Since updating it has fixed itself on my system, I still have to check the other systems to see if the issue is resolved after updating, due to holiday I haven’t had the time yet to check.

Thanks for the thorough investigation!

**Comment by git-kick** [comment]
Thanks for following this up.

Unfortunately, I cannot confirm PhilippSchlesingers observations:
- I restarted my PC
- logged in with my account (only)
- made sure only 1 Nextcloud instance is running
but thumbnails disappear (after showing up for a very short time after opening Windows Explorer) 

In general, I have a single user PC which has been showing the problem for months.

**Comment by PhilippSchlesinger** [comment]
@git-kick did you try removing and re-adding your sync folder?

**Comment by git-kick** [comment]
> @git-kick did you try removing and re-adding your sync folder?

No. Should I? Your yesterday's post suggests this doesn't help.

**Comment by PhilippSchlesinger** [comment]
> No. Should I? Your yesterday's post suggests this doesn't help.

I did not help in *my* case.
If you see this problem for a long time in a single user environment I would suggest to try to make a folder available locally via context menu "Always keep on this device". Mabe you can see thumbnails after this.
Then you can try context menu "Free up space" and it should load thumbnails from the Nextcloud server afterwards.
If this does not help, maybe re-adding the sync folder cleans up things, but this is just a suggestion.

**Comment by PhilippSchlesinger** [comment]
> OK, after **re-adding the folder with "virtual files"=off**, I can see thumbnails on my machine.

Ok, this really *should* work after all, as with any other local folder on a Windows system.
I intended to recommend re-adding the synchronisation folder with virtual files enabled just to set it up clean and fresh.

**Comment by PhilippSchlesinger** [comment]
@Leinad4Mind @Moosetracks555 @ParisGreen and others who confirmed that bug:
Does someone have a similar scenario like described in https://github.com/nextcloud/desktop/issues/5301#issuecomment-1768009683 and https://github.com/nextcloud/desktop/issues/5301#issuecomment-1770527884?

**Comment by lordyavin** [comment]
Just wanted to bump this up. Discovered the issue with windows client version 3.11.0stable-Win64 (build 20231211). I disabled the support of virtual files to get working thumbnails back. This is major for me when working with photo folders.

**Comment by virtualbitzz** [comment]
> there is a logout on the first user account, thumbnails will be displayed correctly after logging in again on the second account. If a second account is logged in parallel to the first, no thumbnails will be displayed there. If there is a logout on the first user account, thumbnails will be displayed correctly after logging out and in again on the second account.

I'm running the same version and am having the same issue

**Comment by virtualbitzz** [comment]
> @Leinad4Mind @Moosetracks555 @ParisGreen and others who confirmed that bug: Does someone have a similar scenario like described in [#5301 (comment)](https://github.com/nextcloud/desktop/issues/5301#issuecomment-1768009683) and [#5301 (comment)](https://github.com/nextcloud/desktop/issues/5301#issuecomment-1770527884)?
> 
> If it holds true, please check if you can reproduce the corresponding similar issue #6145 as well. Thanks!

I'm on a single user system. This issue affects all users on my server, who also use single user systems.

**Comment by PhilippSchlesinger** [comment]
> I'm on a single user system. This issue affects all users on my server, who also use single user systems.

Are preview images (thumnails) enabled on the server? Do the users on your server see preview images in the Nextcloud web interface?
With virtual files enabled, thumnails are generated on the server.

**Comment by MichaelLeenheer** [comment]
Windows 11, only one NextCloud account on my system and having this same issue for a long time now.

A behavior I wanted to add to the conversation is that the thumbnails DO appear, but only for a moment.  When I open a locally synced folder in Windows Explorer it displays the thumbnails, then goes through the folder one by one removing them.  If I switch to another folder and back again, I can once again see the thumbnails for a moment before the same procedure happens again.

Possibly unhelpful but related data: The photos are almost all JPG files, from 3 to 7 MB.  Image metadata changes seem to be a major cause of sync issues for me, especially if I let Lightroom automatically apply changes. Not sure if that's related or helpful at all.

**Comment by lordyavin** [comment]
> thumbnails DO appear, but only for a moment.

The same for me on windows 10. At least before I disabled the virtual files.

**Comment by virtualbitzz** [comment]
> > I'm on a single user system. This issue affects all users on my server, who also use single user systems.
> 
> Are preview images (thumbnails) enabled on the server? Do the users on your server see preview images in the Nextcloud web interface? With virtual files enabled, thumbnails are generated on the server.

Yes previews work great on the server

**Comment by virtualbitzz** [comment]
> @virtualbitzz @lordyavin @MichaelLeenheer: could you please check if you can reproduce the corresponding similar issue #6145? Thumbnails and overlay icons are both provided by shell extensions and maybe there is a common root for this issue.

I will do some additional testing, however the rest of the shell extension appears to be functioning normally. I see proper icons for virtual files vs locally available files (blue arrows vs green check mark), the nextcloud menu when right clicking on a file or folder all works properly (sharing, copying links, etc.) 

With #6145 the entire shell extension appears to not function properly for all but one user on a multi-user system. This is not the case for me. The shell extension works flawlessly, with the exception of file previews.

**Comment by virtualbitzz** [comment]
One additional note, it's my understanding that Nextcloud uses the same shell integration technique as onedrive. I attempted the same procedure with OneDrive (copying the image file to one drive, and clicking 'free up space'). The image preview is displayed properly in Onedrive.

**Comment by lordyavin** [comment]
Sorry, I did not test anything yet. Have it on my backlog but it's not of high priority for me. Disabled virtual files (real files) are okay for me at the moment. I will leave a comment if I have something to report. Thanks for your efforts.

**Comment by PhilippSchlesinger** [comment]
@MichaelLeenheer
Do have more than one windows account logged in at the same time?
Then please check if you have a similar scenario like described in https://github.com/nextcloud/desktop/issues/5301#issuecomment-1768009683 and https://github.com/nextcloud/desktop/issues/5301#issuecomment-1770527884?

**Comment by MichaelLeenheer** [comment]
No, in my case I have (had) only one Windows account on the computer.  

I now have 2 accounts on this computer, but only one is logged in.  Your email made me look again and hey presto! the thumbnails are working.
So there does seem to be a link there ... 

Michael


 

    On Tuesday, July 2, 2024 at 04:41:04 AM MDT, PhilippSchlesinger ***@***.***> wrote:  
 
 


@MichaelLeenheer
Do have more than one windows account logged in at the same time?
Then please check if you have a similar scenario like described in #5301 (comment) and #5301 (comment)?

**Comment by PhilippSchlesinger** [comment]
@MichaelLeenheer
Is one or are both of those accounts admin accounts?
Are thumbnails working in both windows accounts at the same time (both accounts logged in in parallel)?

Could you please also check if you can reproduce this corresponding issue https://github.com/nextcloud/desktop/issues/6145?

Thank you.

**Comment by virtualbitzz** [comment]
I'm still having this issue. 

- Fully patched server and clients
- All users on the server affected
- single user systems
- all Windows users are admins
- All users auth via LDAP on server
- Clients are a mix of AD accounts and local Windows accounts
- TOTP enforced for all users

**Comment by dutchmendesign** [comment]
May 2025 and the bug is still there.
It took me a lot of time and frustration to finally find out it is the Nextcloud client app.
On my windows 10 machine I do not experience this bug.

**Comment by PhilippSchlesinger** [comment]
@dutchmendesign 
Could you please share some more information about the systems you use? 

Do have more than one windows account logged in at the same time?
Then please check if you have a similar scenario like described in https://github.com/nextcloud/desktop/issues/5301#issuecomment-1768009683 and https://github.com/nextcloud/desktop/issues/5301#issuecomment-1770527884?

Could you please also check if you can reproduce this corresponding issue https://github.com/nextcloud/desktop/issues/6145?

Thank you.

**Comment by dutchmendesign** [comment]
I have 2 accounts on the machine, 1 admin, 1 limited user.
Normally, I only log in with the user account.

I reinstalled the user account from scratch and changed the folder structure.
Put all my picture files in the windows Pictures folder.
Put all my documents in the windows Documents folder.
Checked thumbnails are working.

Then installed Nextcloud.
Created 2 synchronizations/connections for both folders.
The problem is solved, at least for now.

![Image](https://github.com/user-attachments/assets/6b2f8a73-f39b-4c2e-bc68-fba390b221dc)

Before I put all sync folders (virtual included) in the same folder under Nexcloud with just one synchronization/connection.

**Comment by mgallien** [comment]
I am closing this issue as the client improved a lot and we think this is solved

**Comment by PhilippSchlesinger** [comment]
I am sorry, this is still an issue with 3.17.2.

**Comment by darknight7** [comment]
Closing this bug is a bit premature unfortunately. At least on my system I still can't view thumbnails, both for files with a green check and with the blue cloud.
Windows 11, v 3.17.2
Let me know if I can help in any way. This has been around for too long.

**Comment by ALERTua** [comment]
Nextcloud 3.17.2 @ Windows 11: the thumbnails are working.

<img width="587" height="333" alt="Image" src="https://github.com/user-attachments/assets/b1fb4b82-16e7-41e6-9dfd-39a2a14ac47a" />

**Comment by virtualbitzz** [comment]
Still broken. This has to be a server side issue in my environment. It doesn't work on any client, whether it's domain joined or not, single or multi-user. They're all broken. 

<img width="628" height="524" alt="Image" src="https://github.com/user-attachments/assets/aa7f6871-48ec-4873-95aa-d0223108f62b" />

@mgallien

**Comment by darknight7** [comment]
> Still broken. This has to be a server side issue in my environment. It doesn't work on any client, whether it's domain joined or not, single or multi-user. They're all broken.

Interesting, I'd rule out a server setting in my case because on android I do see all previews.
I just made a test: I associated .jpg with the default windows app. Lo and behold: after opening an image once I DO see its preview in the nextcloud folder. Nothing changes until I open them however, triggering the green checkmark icon. With .jpg associated to xnviewmp this did not happen.
Re-associating images to xnviewmp does NOT make the few thumbnails that are already displayed disappear but opening more doesn't let them show either.
Just visiting the folder is not enough either way.

**Comment by GHBLoos** [comment]
I have a brand new installed windows 11, and seem to have the same issue. 
I do have one image that does not seem to be downloaded to the computer, but does show an image.  

<img width="983" height="202" alt="Image" src="https://github.com/user-attachments/assets/d290bf1b-abb2-43a2-8d77-c55825173356" />

Additionaly:
If I _select make always available_, the thumbnails are shown. If I then select 'free up local space' the thumbnails dissapear. I am not sure that is expected behaviour, but I rather have the thumbnails still available.

Nextcloud Hub 10 (31.0.8)
Desktop client 3.17.2

**Comment by MichaelLeenheer** [comment]
> I am closing this issue as the client improved a lot and we think this is solved

Definitely not solved, I would vote that it should not have been closed.  Truthfully, I have had this issue for _years_ through multiple versions of NC and multiple Windows, and have just stopped complaining about it.

It is on all my systems, including old and brand-new ones, systems signed in with one user and systems with multiple users, laptops, Windows 10 and 11 machines, shared computers and 2 different single-user laptops, self-built systems and off-the-shelf brand name computers.  My photography company has 14 computers in different locations on different networks and I've seen this on all of them.

I'm by no means an amateur user so I am confident it isn't something obvious.  

When I open a folder that is synced, it often starts with all the thumbnails visible but then goes through them all one at a time and removes them.  They turn in to the generic icon as posted above.  This clue may indicate it is happening when NextCloud refreshes or does a version check on the files.

Anything that's helpful in here?

- Mostly I use JPG files, don't have much data on other file types.
- Photos are set to open with the default Windows Photos app (but I have tried other apps like PS and it still happens)
- background apps include Windows PowerToys, Everything Search, OneDrive (different folders of course), ToDoist, and Adobe Creative Cloud. 

Processor	Intel(R) Core(TM) i9-14900HX (2.20 GHz)
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Graphics    NVIDIA GeForce 4070 Laptop GPU

**Comment by virtualbitzz** [comment]
For the server I did use a turnkey Linux lxc container that I deployed on proxmox. Looking for corollaries. 

I have ZFS array on the proxmox host that I passed directly through to the lxc container. The web interface sits behind a reverse proxy on a Fortigate.
