### ISSUE TITLE
[Bug]: Support Account Domains Matching Common Bundle Extensions

### ISSUE THREAD

**Issue by sjg2203** [nextcloud/desktop#7979]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I am trying to use Virtual files with Nextcloud desktop on macOS, but this functionality does not seem to work.
I installed Nextcloud desktop Virtual files 3.15.3 and skipped the setup part.

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/69a0137b-25c6-449d-a6ff-8e738bf3bbfa" />

I then enabled Virtual files as well as fast sync.

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/5fed2731-66af-46a2-b4fe-2c9b29d27a1e" />

I saw that it scanned over the files currently on the server, though after it seemed it had finished, there was nothing in `Users/macos/Library/CloudStorage/Nextcloud-admin@IP` (`Locations → Nextcloud`), it is empty.
The loading wheel keeps turning indefinitely.

<img width="1317" alt="Image" src="https://github.com/user-attachments/assets/ad8f81d4-d55d-4a11-bcdb-b214b6f8c922" />

I tried to click on the sign-in button on the top right but welcomed me with this blank popup that didn't go anywhere and had to relaunch the Finder.

<img width="1317" alt="Image" src="https://github.com/user-attachments/assets/d736ffa4-895d-4197-93cc-394ea193a017" />

Any idea how to fix this and have Virtual files working on macOS?
If needed, I can troubleshoot on an Intel Mac Pro or ARM MacBook Pro; both are running macOS 15.3.1 (24D70) Sequoia.

### Steps to reproduce

1. Installed Nextcloud desktop 3.15.3 macOS Virtual files 12+
2. Connected using my server IP address
3. Skipped setting up the account
4. Enabled `Enable virtual files` and `Enable fast sync` in `Settings → Virtual file sync`
5. Scanned files on the server
6. `Locations → Nextcloud` is empty, keeps loading

### Expected behavior

When enabling Virtual files and after it finished scanning files, it should appear in `Locations → Nextcloud` on macOS

### Which files are affected by this bug

All

### Operating system

macOS

### Which version of the operating system you are running.

macOS 15.3.1 (24D70) Sequoia

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

31.0.0

### Nextcloud Desktop Client version

3.15.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

Anonymised Nextcloud desktop debug archive:
[2025-03-06_nextcloud-debug-archive.zip](https://github.com/user-attachments/files/19112580/2025-03-06_nextcloud-debug-archive.zip)

**Comment by buiapp** [comment]
VFS also doesn't work for me on MacOS 15.3.1. But I get an error message when clicking on the Location entry:

```
You can’t open the application “Nextcloud-45cde930008fce46ad077d23c8e7d6c@nextcloud.abc.abc” because it may be damaged or incomplete.
```

**Comment by nilsding** [comment]
@buiapp the issue you're facing has been fixed with #7835 and will be part of the next release 3.16.0 (assuming the domain of your Nextcloud instance ends in `.app`)

as for OP's issue, I wonder if #7768 resolved this too (that PR is also part of 3.16.0)

**Comment by buiapp** [comment]
Wow, that's a very niche bug I tapped into. 😅 Just because of the .app domain...

**Comment by sjg2203** [comment]
I sometimes have this bug [#7768](https://github.com/nextcloud/desktop/pull/7768) on my Intel macOS after a reboot, but never on my ARM macOS.
I tried with Nextcloud `3.16.0-rc2`, as I could not find `rc3` on this [site](https://download.nextcloud.com/desktop/prereleases/Mac/), same empty Finder with loading wheel appears.

> as for OP's issue, I wonder if [#7768](https://github.com/nextcloud/desktop/pull/7768) resolved this too (that PR is also part of 3.16.0)

**Comment by nilsding** [comment]
@sjg2203 hmm, interesting that the architecture matters there. 🤔 

Regarding this issue you've opened -- does that occur on both Intel and ARM?

**Comment by buiapp** [comment]
@nilsding My Mac client still crashes even with the newest version 16.0. I attached a console log that could help troubleshoot.

[nextcloud.log](https://github.com/user-attachments/files/19160525/nextcloud.log)

**Comment by sjg2203** [comment]
@nilsding I updated to Nextcloud `3.16.0`, rebooted my Mac, still no change.

I played around a bit and found that some people had to add `showExperimentalOptions=true` to `nextcloud.cfg` under `/Users/youruser/Library/Preferences/Nextcloud/`, though it did not help in this case.
In the same file, there is `isVfsEnabled=false`, I tried to switch to `true` but it automatically reverted to `false`.

As seen [here](https://docs.nextcloud.com/desktop/latest/macosvfs.html#supported-features), it is recommended to install notify_push, though its installation is not the most straightforward and quite buggy, I managed to have it installed and more or less running. It, however, did not help in this case.

Any idea what could cause VFS not to work? Could you guys investigate this

**Comment by SchVinzenz** [comment]
Same problem here. I'm using Nextcloud 3.16.1 (with ARM) and it still doesn't work. Like @buiapp the normal client works for me without any problems.

**Comment by masterbachelormaster** [comment]
exact same issue. It's frustrating. I've already tried everything. Looking forward to a solution :)

**Comment by Rello** [comment]
Hello,
we had an issue with VFS on systems where no notfy_push was installed. can you give the new .2 another try?

thank you for your support

**Comment by buiapp** [comment]
I installed 3.16.2 yesterday but it still crashed. But I didn‘t reboot (will try later). Do you need any specific logs to debug it further?

**Comment by masterbachelormaster** [comment]
> Hello, we had an issue with VFS on systems where no notfy_push was installed. can you give the new .2 another try?
> 
> thank you for your support

.2 doesn't work for me. I also installed the notify_push from the appstore. It did not fix the issue, unfortuantely :/

**Comment by sjg2203** [comment]
@Rello, version '3.16.2' did not resolve the issue. Using a domain instead of the IP address helps see the server in Locations in the Finder's menu, but once in there I can access the first order of folders but then these are empty.

> Hello,
> we had an issue with VFS on systems where no notfy_push was installed. can you give the new .2 another try?
> 
> thank you for your support

**Comment by sjg2203** [comment]
@Rello, version `3.16.2` did not resolve the issue. Using a domain instead of the IP address helps see the server in Locations in the Finder's menu, but once in there I can access the first order of folders but then these are empty.

> Hello,
> we had an issue with VFS on systems where no notfy_push was installed. can you give the new .2 another try?
> 
> thank you for your support

**Comment by SchVinzenz** [comment]
@sjg2203 Thank you for your advice. I know it still doesn't work for you, but I also tried using the IP address (with http) instead of the domain (with SSL certificate). And it works wonderfully! Files are also displayed in the folders and I can open and view them without any problems.

**Comment by mark-ka** [comment]
You have to add the account newly, after you installed the VF-client. there you can set the virtual-files-function

**Comment by masterbachelormaster** [comment]
> You have to add the account newly, after you installed the VF-client. there you can set the virtual-files-function

Thanks for your comment and the advice. What do you mean exactly? Many people have tried various things without any success including resetting the Nextcloud installation and signing only into the vsf option. Would be curious about your suggested solution, since nothing works for me.

**Comment by mark-ka** [comment]
> > You have to add the account newly, after you installed the VF-client. there you can set the virtual-files-function
> 
> Thanks for your comment and the advice. What do you mean exactly? Many people have tried various things without any success including resetting the Nextcloud installation and signing only into the vsf option. Would be curious about your suggested solution, since nothing works for me.

I had the same problem before, like described above. after I removed the complete account (click on the three points beside your account-name) and added it again (server-address), it gave me the option to use VF. when the account was set, I activated it SETTINGS >>> STANDARF FILE SYNC >>> three points >>>. lowest point: enable VF ... and it worked.

But key was: setting your account from new.
Maybe it helps some of you guys :)

**Comment by masterbachelormaster** [comment]
> > > You have to add the account newly, after you installed the VF-client. there you can set the virtual-files-function
> > 
> > 
> > Thanks for your comment and the advice. What do you mean exactly? Many people have tried various things without any success including resetting the Nextcloud installation and signing only into the vsf option. Would be curious about your suggested solution, since nothing works for me.
> 
> I had the same problem before, like described above. after I removed the complete account (click on the three points beside your account-name) and added it again (server-address), it gave me the option to use VF. when the account was set, I activated it SETTINGS >>> STANDARF FILE SYNC >>> three points >>>. lowest point: enable VF ... and it worked.
> 
> But key was: setting your account from new. Maybe it helps some of you guys :)

Thanks for this. It was recommended somewhere else. I did try this several times. Even completely erased Nextcloud with AppCleaner. IT DOES NOT WORK. Thanks for the suggestion though!

**Comment by sjg2203** [comment]
Thank you for the advice but as stated by @masterbachelormaster, this trick does not work either, unfortunately☹️

> I had the same problem before, like described above. after I removed the complete account (click on the three points beside your account-name) and added it again (server-address), it gave me the option to use VF. when the account was set, I activated it SETTINGS >>> STANDARD FILE SYNC >>> three points >>>. lowest point: enable VF ... and it worked.
> 
> But key was: setting your account from new.
> Maybe it helps some of you guys :)

**Comment by buiapp** [comment]
Nextcloud VFS doesn't crash anymore with the new 3.16.3 version. But clicking on the sidebar entry Locations -> Nextcloud, doesn't do anything for me.

**Comment by masterbachelormaster** [comment]
Quick update on my side again... I just got the ne M4 Air and set it up from scratch without any backups to see whether the issue is a server or client side issue. The issue is even present with an absolutely new clean MacOS installation on my new M4 Air. So, it must be a server side issue. Pretty side that I don't get it to work. So, I'm going to move back to Synology Drive, as there's no solution in sight. Good luck y'all!

**Comment by Rello** [comment]
> Nextcloud VFS doesn't crash anymore with the new 3.16.3 version. But clicking on the sidebar entry Locations -> Nextcloud, doesn't do anything for me.

Hi,
you can create the debug log in the settings. see if you find something - or post it here.
In general it is working with >20k installations of 16.2.
lets see...

**Comment by buiapp** [comment]
> > Nextcloud VFS doesn't crash anymore with the new 3.16.3 version. But clicking on the sidebar entry Locations -> Nextcloud, doesn't do anything for me.
> 
> Hi, you can create the debug log in the settings. see if you find something - or post it here. In general it is working with >20k installations of 16.2. lets see...

Here are my logs.

[logs.zip](https://github.com/user-attachments/files/19779298/logs.zip)

**Comment by Unfaehig** [comment]
Hey guys,

so i also run into the issue, while trying to migrate to another domain name. 
So with my old domain it seems to work fine. However the new domain use special chars *non ASCII". There is a spcial method called **Punycode** to input the domain name for compatibility reasons. However i see that the URL in the `nextcloud.cfg` is always saved as undecoded URL, also the logs use the non Punycode version. So i guess in my case it might be related to this special chars in the domain.

So lets take this example `hellò.com` gets in Punycode is `xn--hell-oqa.com` however in nextcloud.cfg it will always shown as `hellò.com`
So my guess is that the underlying Apple API expects the URL as `xn--hell-oqa.com`. It is currently just a guess, because i haven't found a good log entry, however it would explain why it works with my old domain without flaws, but not with the new one.

**Comment by sjg2203** [comment]
@Unfaehig, it might be the issue when having a domain name but I am using the IP address, no special characters or else here. Still not working even with `3.16.3` for me with the latest macOS `15.4`…

> Hey guys,
> 
> so i also run into the issue, while trying to migrate to another domain name. 
> So with my old domain it seems to work fine. However the new domain use special chars *non ASCII". There is a spcial method called **Punycode** to input the domain name for compatibility reasons. However i see that the URL in the `nextcloud.cfg` is always saved as undecoded URL, also the logs use the non Punycode version. So i guess in my case it might be related to this special chars in the domain.
> 
> So lets take this example `hellò.com` gets in Punycode is `xn--hell-oqa.com` however in nextcloud.cfg it will always shown as `hellò.com`
> So my guess is that the underlying Apple API expects the URL as `xn--hell-oqa.com`. It is currently just a guess, because i haven't found a good log entry, however it would explain why it works with my old domain without flaws, but not with the new one.

**Comment by buiapp** [comment]
Just for update: Still the same for me in 3.16.4.

**Comment by JoshVelvet** [comment]
Having the same issue with macOS 15.4.1 and NextCloud VFS 3.16.4. Had it working before, shuffled my NextCloud hosting around and now having the issue with both my domain and IP address with Virtual Files in Finder showing the same as the original bug report. Will make do for now, but would be nice to get a fix as using Virtual Files is a deal breaker for me.

**Comment by jdub850000** [comment]
Seems to work on Apple Silicon for me but not on my Intel Mac.

**Comment by sjg2203** [comment]
Lucky you, any specific setup to have it working? It still doesn't work on both my Intel or ARM macOS with fresh install of NextCloud `3.16.4`

> Seems to work on Apple Silicon for me but not on my Intel Mac.

**Comment by jdub850000** [comment]
> Lucky you, any specific setup to have it working? It still doesn't work on both my Intel or ARM macOS with fresh install of NextCloud `3.16.4`
> 
> > Seems to work on Apple Silicon for me but not on my Intel Mac.

Nope. Nothing other than install, point and authenticate at the Nextcloud server and select VFS only.

**Comment by sjg2203** [comment]
Did you log in with a domain name or IP address? I logged in with my IP address since I don’t own a domain name, and it doesn’t work.
> Nope. Nothing other than install, point and authenticate at the Nextcloud server and select VFS only.
> > Lucky you, any specific setup to have it working? It still doesn't work on both my Intel or ARM macOS with fresh install of NextCloud `3.16.4`
> > > Seems to work on Apple Silicon for me but not on my Intel Mac.

**Comment by JerFlying** [comment]
Same issue, just commenting for awareness. It used to work, but stopped working a couple of weeks ago.

**Comment by Shrinks99** [comment]
I'll add that I'm also experiencing this issue and it started when I switched from using my local IP (192.168.2.99:30045) to my Tailscale address (https://server.tree-barn.ts.net:30045).  It's worth noting that none of these are non-ascii characters.

**Comment by Shrinks99** [comment]
This has been fixed for me as of [v3.16.6](https://github.com/nextcloud/desktop/releases/tag/v3.16.6)!

**Comment by thejazzid** [comment]
same exact issue on 3.16.6 mac client both intel and apple silicone. 
server side [Nextcloud Hub 10] (31.0.6). no external DNS, using self signed certs, and access by ip only. 
last line in the logs: 
`2025-07-19 11:06:44:513 [ warning nextcloud.gui.macos.fileprovider.xpc /Volumes/builds/31608/macos-31608/src/gui/macOS/fileproviderxpc_mac.mm:169 ]:	Could not get service for extension "account@192.168.my_IP"`

**Comment by Manners13** [comment]
im using lets encrypt certs and having the same issue using the domain name(lets encrypt) or ip address (self signed) its odd as some files seem to sync. 

if i drop a file in the main folders it uploads but many of the subfolders remain empty on the mac but files on the webpage

in fact ive just noticed even when i make changes to the settings they are ignored and overwritten, like disabling fast sync i untick, close the window, go back in and its ticked again

**Comment by L-Neur0** [comment]
Same issue as [sjg2203](https://github.com/sjg2203) on MacOs 15 and latest version of Nextcloud vfs. The extension seems disabled: 
`-    com.nextcloud.desktopclient.FinderSyncExt(1.0)`

**Comment by Shrinks99** [comment]
From what I can tell, this also appears to be a dupe of #7571.  Still no solution, since posting my comment above after the update it has stopped working once and somehow reset itself and is currently working again.

**Comment by Rello** [comment]
> Same issue as [sjg2203](https://github.com/sjg2203) on MacOs 15 and latest version of Nextcloud vfs. The extension seems disabled: `- com.nextcloud.desktopclient.FinderSyncExt(1.0)`

to comment on this: this is the extension of the classic sync. this is automatically disabled by apple as soon as the FileProviderExt (VFS) is in use

**Comment by L-Neur0** [comment]
> > Same issue as [sjg2203](https://github.com/sjg2203) on MacOs 15 and latest version of Nextcloud vfs. The extension seems disabled: `- com.nextcloud.desktopclient.FinderSyncExt(1.0)`
> 
> to comment on this: this is the extension of the classic sync. this is automatically disabled by apple as soon as the FileProviderExt (VFS) is in use

Ah ok, thanks. Still the vfs in Finder is like [sjg2203](https://github.com/sjg2203) screenshot.

**Comment by Manners13** [comment]
it is quite possibly the same issue but having spent 8hours yesterday uninstalling and reinstalling Nextcloud client with reboots and finding special folders to delete files in between, I'm totally lost on why it syncs some things but not others and says the sync is fine and complete, but folders remain empty even though they show with files via the webpage. The Windows client just works so beautifully I'm really hoping this mac one will to soon

**Comment by L-Neur0** [comment]
> From what I can tell, this also appears to be a dupe of [#7571](https://github.com/nextcloud/desktop/issues/7571). Still no solution, since posting my comment above after the update it has stopped working once and somehow reset itself and is currently working again.

I am using tailscale too. Which MacOs version is it working for you? thx

**Comment by Manners13** [comment]
it doesn't work properly by any means, I'm using Monterey with the latest 16.6 virtual files client. which uploads/syncs things in the main folder but doesn't seem to go any deeper that that.

i have a folder with 400GB worth of data in a group folder and several others with a few files in each one that needs to be accessible from this Mac due to space available on the mac mini I cant do a full download without upgrading so virtual files would be perfect

Mine doesn't say its offline at all, when i hover over what looks like a tiny grey i it says it has a problem which led me to the logs virtually the same as above.  if i go to settings and virtual files it shows the same as the [sjg2203](https://github.com/sjg2203) post, untick and ticking enable virtual files makes the bar start again but as soon as settings are closed and reopened it goes straight back to complete

also if you untick the fast sync option then close settings and reopen its ticked itself again

I did try an earlier version i found but that didn't even want to open so i aborted on that front very quickly.

also push notify i dont think is an option for me as the nextcloud server is running on mysql and a requirement is redis

**Comment by Rello** [comment]
Hello,
I recommend a little patience here. the next 3.17 had a very basic rework of the VFS and will be much quicker and stable

**Comment by Manners13** [comment]
sounds good, is there any timescale on release?

just so I'm aware, I'm actually going away for a few weeks so it shouldn't matter too much but just wondering if we are looking at days, weeks, months?

**Comment by Rello** [comment]
RC was planned for this week but something came up.
next week is planned

**Comment by buiapp** [comment]
I tried the new 3.17.0-rc1 but VFS still does not work. The Nextcloud entry in the Locations section is not clickable. Is that problem because I use Nextcloud with an .app domain?

<img width="181" height="142" alt="Image" src="https://github.com/user-attachments/assets/e690a7df-b0bc-4412-9212-c928787493e6" />

**Comment by Manners13** [comment]
Can anyone explain why the nextcloud client doesn't trust the letsencrypt certificate but if I go to the web page on the same device it's automatically trusted and accepted as secure.

I'm not back from hols yet but will test the release candidate for mac when I am back and update on the vfs

**Comment by DTepl** [comment]
So I had the same problem and for me it was an authentication problem. My self-signed SSL certificate was expired but I still could access my instance via the app and browser but not via vfs in the finder under "local". It seems that apple is pretty strict with certificates. What fixed the issue for me was to renew the certificate on the server side, download it to my macbook and trust it manually in the keychain (double click on certificate to add it to the keychain and then set it in the keychain to trust "always"). After that, I just needed to disable vfs and re-enable it. Since then it is working like a charm.

Edit: This worked for version 3.16.6. The newest updates break it again

**Comment by Manners13** [comment]
Sorry my bad,  I was seeing it on an android phone.  Weirdly the problem seems to have vanished now on my android.  I will retest the Mac when I get home

**Comment by Manners13** [comment]
Still having the same issue with sync on mac, many folders seem to have synced but the group folder and a few other have not, i get the error a problem has occured see below but it doesnt really explain why.

ive tried the reset vfs environment but it doesnt fix it.

<img width="864" height="193" alt="Image" src="https://github.com/user-attachments/assets/f5165635-e573-440b-a8e6-eb4adc1d6716" />

<img width="1601" height="366" alt="Image" src="https://github.com/user-attachments/assets/20af65c2-7031-4224-a96e-96bbaaa6b0bb" />


 i have the debug log but nothing looks obvious, if a developer would like to see it please give me your email and i will forward it across
 the images show nothing in RES Server when clicking on it in finder and below shows the web interface showing which folders i expect to see

yet updates time seems to be correct

**Comment by Rello** [comment]
> I tried the new 3.17.0-rc1 but VFS still does not work. The Nextcloud entry in the Locations section is not clickable. Is that problem because I use Nextcloud with an .app domain?
> 
> <img alt="Image" width="181" height="142" src="https://private-user-images.githubusercontent.com/116504091/473336640-e690a7df-b0bc-4412-9212-c928787493e6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ4MDk3MDgsIm5iZiI6MTc1NDgwOTQwOCwicGF0aCI6Ii8xMTY1MDQwOTEvNDczMzM2NjQwLWU2OTBhN2RmLWIwYmMtNDQxMi05MjEyLWM5Mjg3ODc0OTNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxMFQwNzAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2RhYjY5MDRmOTllZmE1YjMyZmQwOTAwYmU0M2MzMjVjN2NiOTUxNDU3MTk5YTUwMDg1ZmUwOThjMWNhM2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z-eE5mIBzmjH20U_WS5AfPtCfgI71l0c1_6zhPb3il8">

@buiapp that looks really strange. the logo is also not matching. could be related to the .app domain because macOS will use the domain as an identifier - and this will become an app in your case. did you test it against another server already?

**Comment by Rello** [comment]
@Manners13 also on the 3.17 already?

**Comment by Manners13** [comment]
Yes that's on 3.17 rc3

This is pretty much the same as i was experiencing before. Some folders show files within them but several do not. The single group folder does not show anything but also many personal ones dont show anything.

saving a debug log into the nextcloud location. does sync back to the server and is available to download on a different device using the webpage.

My logs are attached below. any help is greatly appreciated 

[__nextcloud_client_buildinfo.txt](https://github.com/user-attachments/files/21714831/__nextcloud_client_buildinfo.txt)
[__nextcloud_client_parameters.txt](https://github.com/user-attachments/files/21714830/__nextcloud_client_parameters.txt)

[20250810_1423_nextcloud.log.txt](https://github.com/user-attachments/files/21714844/20250810_1423_nextcloud.log.txt)

[nextcloud.cfg.txt](https://github.com/user-attachments/files/21714880/nextcloud.cfg.txt)

**Comment by Manners13** [comment]
am i doing something wrong or is this a bug thats likely to get fixed?

**Comment by Rello** [comment]
Hi @Manners13 

your log is full of ssl issues. also something seems to be wrong with your file provider domain.
its not a general issue and seems to be related to your setup somewhere.

one thing you can try is to start from scratch with VFS and see if everything works.

- open your app and disable VFS
- close the app
- delete the following content:
```
rm -rf "$HOME/Library/Application Scripts/com.nextcloud.desktopclient"*  
rm -f  "$HOME/Library/Application Support/CrashReporter/Nextcloud_"*  
rm -rf "$HOME/Library/Application Support/Nextcloud"  
rm -rf "$HOME/Library/Caches/Nextcloud"  
rm -rf "$HOME/Library/Containers/com.nextcloud.desktopclient"*  
rm -rf "$HOME/Library/Group Containers/com.nextcloud.desktopclient"  
rm -f  "$HOME/Library/LaunchAgents/com.nextcloud.desktopclient.plist"  
rm -f  "$HOME/Library/Preferences/com.nextcloud.desktopclient.plist"
```

do NOT delete `~/Library/Preferences/Nextcloud` to keep your account settings.

Reinstall the current 3.17 and see if the VFS gets a clean setup

**Comment by sjg2203** [comment]
> Hi [@Manners13](https://github.com/Manners13)
> 
> your log is full of ssl issues. also something seems to be wrong with your file provider domain. its not a general issue and seems to be related to your setup somewhere.
> 
> one thing you can try is to start from scratch with VFS and see if everything works.
> 
> * open your app and disable VFS
> * close the app
> * delete the following content:
> 
> ```
> rm -rf "$HOME/Library/Application Scripts/com.nextcloud.desktopclient"*  
> rm -f  "$HOME/Library/Application Support/CrashReporter/Nextcloud_"*  
> rm -rf "$HOME/Library/Application Support/Nextcloud"  
> rm -rf "$HOME/Library/Caches/Nextcloud"  
> rm -rf "$HOME/Library/Containers/com.nextcloud.desktopclient"*  
> rm -rf "$HOME/Library/Group Containers/com.nextcloud.desktopclient"  
> rm -f  "$HOME/Library/LaunchAgents/com.nextcloud.desktopclient.plist"  
> rm -f  "$HOME/Library/Preferences/com.nextcloud.desktopclient.plist"
> ```
> 
> do NOT delete `~/Library/Preferences/Nextcloud` to keep your account settings.
> 
> Reinstall the current 3.17 and see if the VFS gets a clean setup

Hi @Rello,

Got `3.16.6` working with VFS once I got a domain name. VFS does not work with a raw IP address, despite saying it does. Updated to `3.17.0`, broke everything. VFS is no longer syncing; folders/files are disappearing, and I can't sync or download anything. I don't know what change was made, but clearly, this affected VFS in a major way on macOS. Has VFS been deactivated in `3.17.0` because it feels like so? Also, when setting `3.17.0` up fresh, selecting VFS in the installer, and everything crumbles, VFS is empty even if you let the system sync for days. I had to uninstall `3.17.0` and reinstall `3.16.6` for VFS to work properly.

**Comment by Manners13** [comment]
Thanks,  I will try that this weekend.  The ssl errors I don't really understand as if you go to the web interface the certificate is accepted.  Windows doesn't complain and my android doesn't complain yet mac seems to have issues but only in the client, if I use Chrome there's no issues certificate is accepted. 

Can you advise what to look for on the server side as the issue or is there a way to do a clean install of next cloud server without losing any files or users that currently exist.  I use mysql as the database

**Comment by Manners13** [comment]
Ive done as explained but it still seems to have the issue, I have now sorted the SSL Errors by switching certificate provider to sectigo but still seeing a lot of these errors within the log file

2025-08-19 14:20:44:404 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/33044/macos-33044/src/gui/macOS/fileprovidersettingscontroller_mac.mm:252 ]:	Fetching materialised files storage usage
2025-08-19 14:20:44:478 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/33044/macos-33044/src/gui/macOS/fileprovidersettingscontroller_mac.mm:256 ]:	Could not get file provider domains: The application cannot be used right now. Will try again in 2 secs

Im assuming this is an error within the nextcloud application as Onedrive seems to work fine and also connecting to nextcloud over webdav on the mac seems to work ok

[20250819_1031_nextcloud.log.txt](https://github.com/user-attachments/files/21857515/20250819_1031_nextcloud.log.txt)

**Comment by sjg2203** [comment]
@Rello @i2h3 @mgallien Tested version `3.17.1`, VFS is still completely broken on macOS. Only temporary fix is to downgrade to [`3.16.6`](https://github.com/nextcloud-releases/desktop/releases/tag/v3.16.6).

I am pinning similar issues related to this one:
#8617 For the blank pop-up that renders Finder unusable.
#8599 Which is literally the same issue as reported here.

**Comment by Rello** [comment]
> Ive done as explained but it still seems to have the issue, I have now sorted the SSL Errors by switching certificate provider to sectigo but still seeing a lot of these errors within the log file
> 
> 2025-08-19 14:20:44:404 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/33044/macos-33044/src/gui/macOS/fileprovidersettingscontroller_mac.mm:252 ]: Fetching materialised files storage usage 2025-08-19 14:20:44:478 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/33044/macos-33044/src/gui/macOS/fileprovidersettingscontroller_mac.mm:256 ]: Could not get file provider domains: The application cannot be used right now. Will try again in 2 secs
> 
> Im assuming this is an error within the nextcloud application as Onedrive seems to work fine and also connecting to nextcloud over webdav on the mac seems to work ok
> 
> [20250819_1031_nextcloud.log.txt](https://github.com/user-attachments/files/21857515/20250819_1031_nextcloud.log.txt)

Hi,
just to confirm: you did do the steps mentioned above to completely clean the old leftovers?
then you installed 3.17 again?

Your domain is with HTTPS now and a valid cert?

**Comment by Manners13** [comment]
Yes, tried first without removing the account settings then tried again with the account settings file too.

Yes using https now with a paid sectigo cert instead of a free let's encrypt cert. 

And again it syncs some folders but not others and if I put a new file within the nextcloud location it does get synced back to the server. 

Many folders remain empty though

**Comment by pelzvieh** [comment]
> Hi [@Manners13](https://github.com/Manners13)
> 
> your log is full of ssl issues. also something seems to be wrong with your file provider domain. its not a general issue and seems to be related to your setup somewhere.
> 
> one thing you can try is to start from scratch with VFS and see if everything works.
> 
>     * open your app and disable VFS
> 
>     * close the app
> 
>     * delete the following content:
> 
> 
> ```
> rm -rf "$HOME/Library/Application Scripts/com.nextcloud.desktopclient"*  
> rm -f  "$HOME/Library/Application Support/CrashReporter/Nextcloud_"*  
> rm -rf "$HOME/Library/Application Support/Nextcloud"  
> rm -rf "$HOME/Library/Caches/Nextcloud"  
> rm -rf "$HOME/Library/Containers/com.nextcloud.desktopclient"*  
> rm -rf "$HOME/Library/Group Containers/com.nextcloud.desktopclient"  
> rm -f  "$HOME/Library/LaunchAgents/com.nextcloud.desktopclient.plist"  
> rm -f  "$HOME/Library/Preferences/com.nextcloud.desktopclient.plist"
> ```
> 
> do NOT delete `~/Library/Preferences/Nextcloud` to keep your account settings.
> 
> Reinstall the current 3.17 and see if the VFS gets a clean setup

I've been suffering from the same symptoms with Nextcloud.app 3.17.1. In contrast to the hints given, I _did_ reset the client session in personal security sessions, and _did_ remove ~/Library/Preferences/Nextcloud, as it appeared to have accumulated lots of garbage of the previous years of upgrades.

Note that you need to give Terminal.app (temporarily) full file access or you won't be able to delete Containers/....desktopclient*.

After reinstalling nextcloud.app and logging in, I was able to directly connect the virtual file system which is up to now working.

**Comment by jwvanderbeck** [comment]
Having the same issues as well.  I do not have a domain, nor a certificate for SSL.  Is this the problem? I don't even want to use SSL honestly, as I do not expose the instance outside my network so getting a domain and certificates just adds complexity for no purpose.
So is this not expected to work without SSL?

[nextcloud-vfs-debug.zip](https://github.com/user-attachments/files/22085219/nextcloud-vfs-debug.zip)

**Comment by Rello** [comment]
> Having the same issues as well. I do not have a domain, nor a certificate for SSL. Is this the problem? I don't even want to use SSL honestly, as I do not expose the instance outside my network so getting a domain and certificates just adds complexity for no purpose. So is this not expected to work without SSL?
> 
> [nextcloud-vfs-debug.zip](https://github.com/user-attachments/files/22085219/nextcloud-vfs-debug.zip)

Hello,
you can always use the client without SSL. I do the same on my local docker containers. just make sure that you did not tell the server to expect the oposite

https://github.com/nextcloud/desktop/issues/8654

**Comment by pelzvieh** [comment]
> > Hi [@Manners13](https://github.com/Manners13)
> > your log is full of ssl issues. also something seems to be wrong with your file provider domain. its not a general issue and seems to be related to your setup somewhere.
> > one thing you can try is to start from scratch with VFS and see if everything works.
> > ```
> > * open your app and disable VFS
> > 
> > * close the app
> > 
> > * delete the following content:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > rm -rf "$HOME/Library/Application Scripts/com.nextcloud.desktopclient"*  
> > rm -f  "$HOME/Library/Application Support/CrashReporter/Nextcloud_"*  
> > rm -rf "$HOME/Library/Application Support/Nextcloud"  
> > rm -rf "$HOME/Library/Caches/Nextcloud"  
> > rm -rf "$HOME/Library/Containers/com.nextcloud.desktopclient"*  
> > rm -rf "$HOME/Library/Group Containers/com.nextcloud.desktopclient"  
> > rm -f  "$HOME/Library/LaunchAgents/com.nextcloud.desktopclient.plist"  
> > rm -f  "$HOME/Library/Preferences/com.nextcloud.desktopclient.plist"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do NOT delete `~/Library/Preferences/Nextcloud` to keep your account settings.
> > Reinstall the current 3.17 and see if the VFS gets a clean setup
> 
> I've been suffering from the same symptoms with Nextcloud.app 3.17.1. In contrast to the hints given, I _did_ reset the client session in personal security sessions, and _did_ remove ~/Library/Preferences/Nextcloud, as it appeared to have accumulated lots of garbage of the previous years of upgrades.
> 
> Note that you need to give Terminal.app (temporarily) full file access or you won't be able to delete Containers/....desktopclient*.
> 
> After reinstalling nextcloud.app and logging in, I was able to directly connect the virtual file system which is up to now working.

Unfortunately, after 2 weeks, the problem is back exactly as before. No indication is given of a specific problem, neither in the Nextcloud app, nor in the Finder window showing the Nextcloud VFS.

The Nextcloud app is showing a yellow exclamation mark and a notice on "some files could not be synchronized, see details below", but without any details. Previous experience seems to tell not to take care about this, as it is related to the classical file sync, which here is not configured at all.

On the settings screen, the "classical" sync tab is just empty (/) , the virtual sync tab is showing a progress bar with 0% or 50% progress, but not making any real progress. The local memory number didn't change in the last days or after restarting the Nextcloud app.

Opening a not previously visited folder in Finder just shows a grey "Loading..." animation (in rare cases an error message as well, but I can't reproduce that nor does it tell anything concrete about the problem). Opening a previously visited folder shows a file list. Double clicking on such files launches the associated app wich receives an error on opening the file.

Looking at the Nextcloud app logs, I'd say, the app does nothing at all:
[nextcloud-vfs neuer Neustart.zip](https://github.com/user-attachments/files/22090879/nextcloud-vfs.neuer.Neustart.zip)

Looking at the web server's logs, I see regular PROPFIND queries to files/someuser which are all successfully completed with 207. Apart from that, nothing is happening at the server.

At the same time, Nextcloud Web, and Nextcloud for Android are working flawless on the same instance.

**Comment by jwvanderbeck** [comment]
> > Having the same issues as well. I do not have a domain, nor a certificate for SSL. Is this the problem? I don't even want to use SSL honestly, as I do not expose the instance outside my network so getting a domain and certificates just adds complexity for no purpose. So is this not expected to work without SSL?
> > [nextcloud-vfs-debug.zip](https://github.com/user-attachments/files/22085219/nextcloud-vfs-debug.zip)
> 
> Hello, you can always use the client without SSL. I do the same on my local docker containers. just make sure that you did not tell the server to expect the oposite
> 
> [#8654](https://github.com/nextcloud/desktop/issues/8654)

Well that's what I thought I was doing, but maybe I'm doing it wrong.  The normal file sync works perfectly fine in the client, it is just the VFS that doesn't.  I mention it because of the other posts that seemed to be pointing  to an incorrect SSL configuration as the cause.

That said maybe I don't have it configured correctly on the server (This is not my area of expertise) as when I connect the client it does require me to use HTTPS and say I have an invalid certificate.  But it has a check box to allow it anyway and like I said that works fine for the normal file sync, just not VFS which never loads like the rest in this thread.

**Comment by faspie** [comment]
This bug also affects me but came during the last 2 weeks on three MacOS clients, and I don't know why....

### Expected behaviour
After enabling Virtual Files (VFS) on macOS, the Finder should display a **Nextcloud** location under *Locations* and placeholder files should be available.

### Actual behaviour
On macOS 15.6.1 (Sequoia) with Nextcloud Desktop client 3.17.1:
- The client reports “synchronisation successful”
- VFS placeholders appears in Finder
- “Nextcloud” location is shown under *Locations*
- The location "Nextcloud" is empty, Finder crashed while showing "loading..."
- The behaviour occurs simultaneously on multiple macOS clients

### Steps to reproduce
1. Install Nextcloud Desktop 3.17.1 on macOS 15.6.1  
2. Enable Virtual Files in the client settings  
3. Observe Finder → crash on "loading"

### Logs / outputs
**Server side (Nextcloud Snap, Ubuntu):**
- MySQL 8.0.43 and Redis running normally
- PHP-FPM / Apache active
- No related errors in `nextcloud.log` at the time of testing

**Client side (macOS):**
- `fileproviderctl dump -l` → no Nextcloud domain listed

### Workarounds attempted
- Removing and reinstalling the Nextcloud client  
- Removing the account and re-adding it  
- Manual cleanup of residual paths:
  - `~/Library/CloudStorage/Nextcloud` (when only placeholders existed)  
  - `~/Library/FileProvider/` (Nextcloud-related containers)  
  - `~/Library/Group Containers/group.com.nextcloud.desktopclient/File Provider Storage`  
- Restarting macOS and re-adding the account  

➡️ Result: Behaviour remains unchanged, VFS domain never created.

### Environment
- **macOS:** 15.6.1 Sequoia  
- **Nextcloud Desktop Client:** 3.17.1  
- **Server:** Nextcloud Snap (Ubuntu)  
- **Database:** MySQL 8.0.43  
- **Redis:** enabled  
- **Web:** PHP-FPM / Apache (via Snap)  

### Notes
- The issue is reproducible across multiple Macs on 15.6.1.  
- File Provider domain for Nextcloud is never created.  
- Since Apple removed `fileproviderctl remove` and related verbs in 14.4, there is no CLI option to reset a domain anymore.  
- This leaves no reliable way to force re-registration of the File Provider domain for Nextcloud testing on current macOS versions.

**Comment by i2h3** [comment]
@faspie You wrote about an attempt which relies on `fileproviderctl remove` on **macOS 15.6.1 Sequoia** but that command (among others) got [removed already back in macOS 14.4](https://i2h3.de/fileproviderctl-changes-macos-14.4/). How does this fit together? I mean, it would be nice to have those commands back since they simplified development a lot but to my knowledge Apple removed them already in early 2024.

**Comment by faspie** [comment]
@i2h3 

You’re absolutely right — Apple removed the critical `fileproviderctl` subcommands (like `domain remove/evict`) starting with macOS 14.4, and they’re still gone on Sequoia 15.x. My earlier mention of `fileproviderctl remove` was incorrect — thanks for catching that.

What I actually used for diagnostics was `fileproviderctl dump`. For a real reset/removal there is no CLI option anymore. The only working way since 14.4 is to remove the account in the app itself (so the client calls `NSFileProviderManager` to deregister the domain) and then clean up residual folders manually if needed:

- `~/Library/CloudStorage/Nextcloud` (if only placeholders are left)  
- `~/Library/FileProvider/` → Nextcloud-related containers  
- `~/Library/Group Containers/group.com.nextcloud.desktopclient/File Provider Storage`  

After that: restart macOS, launch Nextcloud, re-add the account.

Unfortunately, there’s no “hard reset” from the command line anymore. `fileproviderctl dump` is still useful for inspection, but that’s about it.

Refs: Apple dropped those verbs in 14.4 (see Eclectic Light and HN discussions, spring 2024).

**Comment by faspie** [comment]
@i2h3 

Bug report has been edited

**Comment by ldehner** [comment]
also getting the damaged or incomplete error when trying to open the Nextcloud location

**Comment by buiapp** [comment]
My problems has gone away after using a non .app domain.

**Comment by jwvanderbeck** [comment]
> My problems has gone away after using a non .app domain.

At least in my case, I'm not even using a domain or SSL.  Just an IP address.
Again, works fine without VFS, and VFS works fine with the same server on Windows.

**Comment by ldehner** [comment]
> My problems has gone away after using a non .app domain.

would try that too, but I am using the AIO setup, which only allows one domain 🫤

**Comment by i2h3** [comment]
> My problems has gone away after using a non .app domain.

Ohh… This rings a bell! I saw code related to this months ago. We actually have a mapping code which should take care of these invalid names.

1. So, it all comes down to [application bundles](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AboutBundles/AboutBundles.html) as they always existed on macOS. If you force display of all file extensions on macOS, you can see that all your apps usually have an ".app" suffix. In fact and on macOS, those actually are just folders and they are treated in a very special manner with this suffix (there are a lot more and even arbitrarily added by third-party software).
2. Newly setup file provider domains from our client in recent releases use UUIDs as the internal identifiers.
3. Though, the display name of the file provider domains is composed based on the app name ("Nextcloud") and the programmatically defined account name (in example "whoever@example.tld"). The appearance in the Finder sidebar is controlled by macOS and we cannot influence that when it comes to the difference between single (shows app name only) and multiple accounts (shows domain display name prefixed by app name) being set up.
4. Given a Nextcloud account on a domain with a problematic top-level domain, you might end up having a folder in `~/Library/CloudStorage` named like an app bundle. Besides those folders not being traditional folders but some low-level wizardry which hooks into the file system (as far as I know), it messes up macOS because it considers them to be apps. At least that is how it used to be a while ago but Apple might have improved in that regard since and I did not learn about it yet.

**Conclusion so far**: I assume we need to change how we define display names of file provider accounts to avoid creation of file system items which mess up macOS in their handling. Somehow escape certain suffixes or domains or whatever. This needs some thought. Obviously, we need to verify and check this lead with ".app" suffixes first.

**Comment by i2h3** [comment]
We just discussed this and the background. I looked up something in the code (`bundleExtensions` in `fileproviderutils.h` which I remembered from a while ago). At some point we have already implemented handling of these bundle extensions in file provider domain identifiers and display name.

This actually is a regression by now. We switched to UUIDs for the file provider domain identifiers recently to avoid inconsistent and broken account states when they were set up multiple times. Before that, display name and identifier were equal. This assumption no longer applies. We need to change the handling of bundle suffixes to cover the file provider domain display name again, too.

**Comment by ldehner** [comment]
Any Updates @i2h3?

**Comment by i2h3** [comment]
Not yet. But this is still part of the 33.0.0 scope which will be our next major release expected around the end of February. **If** my current idea works out, then I can verify it tomorrow at earliest.

**Comment by i2h3** [comment]
I have not tested it with the `.app` domain. That requires more effort like either buying such a domain or setting up a test environment with self-signed SSL certificates because `.app` is on HSTS preload list. Browsers are hardwired to require HTTPS for those domains.

But there are other special bundle extensions I can set up as test domains which do not require a secure connection, such as `.framework`. Without the fix, I definitely noticed that some part of macOS is struggling to cope with the folder not being a framework. 😬 "**Do not try this at home!**" 😅 It was a bit more complicated to clean up by manually deleting files of the file provider framework here and there and rebooting twice in the process of figuring out.

With the fix for the display name, it looks better. 😮‍💨 I mean not purely superficial but in terms of function.

<img width="350" height="124" alt="Image" src="https://github.com/user-attachments/assets/75d73de2-dc5b-474e-83c3-6d04d0841328" />

But there is another problem with the authentication now, maybe due to residual broken state in macOS from the previous attempts. 🫣

**Comment by jwvanderbeck** [comment]
I'm curious what happened to this issue that it morphed into "Support Account Domains Matching Common Bundle Extensions"?
Because the original issue was seen by myself and others without the use of any special domains.  In my case the bug exists just using an IP address.  So does this mean that the original use case is just flat out not supported and we HAVE to have a domain now?

**Comment by i2h3** [comment]
@jwvanderbeck You are right! I got distracted and even only now saw the collapsed GitHub section of 83 comments. 😳 And no, IP addresses work just fine. They are not the problem.

By now, this issue has diluted into a collection of various problems and no longer is on the original topic. I kindly ask @sjg2203 to provide an update on whether the original issue is still reproducible with 4.0.5 or not. After completely removing the account configuration from the client once and setting it up anew, just to be sure. A lot change since the release in the original report above and it might already resolve the problem by setting up the account anew in the recent release. Otherwise, the new logging provides much more insights on what is going on and enriches the debug archive which can be exported. When the client does **not** run and before trying to set it up again, the local installation can be cleaned up with these shell commands:

```bash
rm -rfv ~/Library/Containers/com.nextcloud.desktopclient*
rm -rfv ~/Library/Group\ Containers/com.nextcloud.desktopclient
rm -rfv ~/Library/Group\ Containers/*.com.nextcloud.desktopclient
rm -rfv ~/Library/Preferences/Nextcloud*
```

**Warning:** This will delete your local client configuration. Use only in case you are fine with setting up your account in the Nextcloud desktop client again. In context of this: With our next bigger release on the horizon a proper cleanup procedure is also intended to become documented in the official manual.

For everyone else: Please also check whether this issue still applies in your case with the recent client after setting up the account anew.

**Comment by jwvanderbeck** [comment]
Ok I will  test this anew on my macbook as soon as I get a chance, but it might not be right away.  I do know last time I used it, maybe a few months ago (I typically only use that laptop when traveling) I recall running into the issue but I had not cleaned everything out or anything, just done regular updates as they came in.

**Comment by sjg2203** [comment]
@i2h3 I ran the commands you provided and reinstalled Nextcloud `4.0.6` from scratch (not just updating the existing one). I cannot reproduce the issue anymore **but** I am now using a domain name and if trying to connect using the IP, it redirects to the domain name. If @jwvanderbeck can try on its end and see if the error is still there or not, that would be fantastic.

**Comment by jwvanderbeck** [comment]
I can say that just upgrading to 4.0.5 was not enough to fix it.  I was hoping not to wipe the whole connection but I'll do that and report back.

**Comment by jwvanderbeck** [comment]
After running the above commands and installing 4.0.6, I no longer even see the option for virtual files in the settings.
EDIT Right I forgot on macOS it was a separate client for VFS.  Let me find that

**Comment by jwvanderbeck** [comment]
So now for some reason i have TWO entries for Nextcloud in my Locations, one shown by account name and one by email address, but they both have the exact same issue where it says Loading forever.

**Comment by jwvanderbeck** [comment]
Rebooted and now I only have the one "Nextcloud" location again, rather than two that have usernames on them, but the same issue still persists.

[NextCloudDebug.zip](https://github.com/user-attachments/files/24807091/NextCloudDebug.zip)

**Comment by i2h3** [comment]
> but I am now using a domain name and if trying to connect using the IP

@sjg2203 I am sure this is caused by a HTTP redirect from the server.

> So now for some reason i have TWO entries for Nextcloud in my Locations

@jwvanderbeck Sometimes the file provider framework in macOS can messed up, too. Especially in the older releases where file provider domains did not use unique IDs for their identification the reuse of identifiers could mess up things easily. A reboot indeed sometimes is the solution to resolve some issues.

Background information: Finder always displays the app name of a file provider domain. In case of only one domain managed by an app, the app name is rendered. In case there are multiple domains by the same app, the domain display name (in our case equal to the account identifier) is appended for distinction.

In your case, the problem is quite obvious:

```plaintext
2026-01-22 15:36:34 [ERROR] Error in auth check: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.0.153” which could put your confidential information at risk.
```

You attempt to connection via HTTPS to a host identified by IP address. This was not possible until only recently. SSL certificates used to work only with domains. [Apparently, this has changed](https://letsencrypt.org/2025/07/01/issuing-our-first-ip-address-certificate). Also, we currently do not support self-signed certificates (AFAIK) in the file provider extension because its network stack is functionally independent from the main app by design and necessity. Please check for existing issues about that setup and open a new one, if required for it being a different problem.

**Comment by jwvanderbeck** [comment]
Ok well I had stated in the very beginning that I was using an IP address without a certificate.  Honestly I don't even WANT to use SSL but seem to be forced to.  

It is rather confusing though because shouldn't the Application then tell you this isn't a supported configuration? Because it acts like everything is fine. It connects just fine, and asks if you want to trust the certificate..  If it really isn't a supported configuration then it should probably tell you rather than leave you scratching your head as to why the normal sync works and not the virtual sync.

**Comment by i2h3** [comment]
@jwvanderbeck Our client supports both insecure HTTP and secure HTTPS connections. Personally, I work with a `http://localhost:8080` (Nextcloud Docker container) but also `https://<redacted public domain>` (Nextcloud All-in-One) on a daily basis. In case you do not explicitly specify the insecure HTTP scheme when setting up an account, the secure and default HTTPS is automatically prepended to the server address. There is no enforcement.

> Because it acts like everything is fine. It connects just fine, and asks if you want to trust the certificate.

As stated, the file provider extension mostly is independent from the main app (a constraint imposed by the platform), its network stack in particular. What you are describing is a feature not implemented yet, if I am right. Though, you are right, the error should be propagated correctly unless we can ensure that the file provider extension considers the certificates trusted by the main app. I would need to look into that specifically first. Please open a dedicated issue for your case, if you want to use self-signed SSL with an IP address.

**Comment by sjg2203** [comment]
> > but I am now using a domain name and if trying to connect using the IP
> 
> [@sjg2203](https://github.com/sjg2203) I am sure this is caused by a HTTP redirect from the server.

@i2h3 @i2h3 Yes, apologies for not mentioning it earlier. I’ve added automatic redirection for the IP address to HTTPS.

**Comment by i2h3** [comment]
Closing this issue because the original problem cannot be reproduced anymore and one of many possible reasons was fixed. Please open new and more specific issues for similar observations.

**Comment by chromowanewrozki** [comment]
# Proposed Solution: Fix for Virtual Files Sync Issues (macOS 4.0.6)

## Overview
Users on **macOS running Nextcloud Desktop Client 4.0.6** may experience issues where Virtual Files fail to sync or appear. This is often caused by SSL certificate verification failures or stalled WebDAV sessions. 

Manually mounting and unmounting the share "primes" the macOS networking stack to trust the connection.

---

## Step-by-Step Fix

### 1. Manual Connection via Finder
Establish a manual connection to handle the SSL handshake:
1. Open **Finder** and press `Cmd + K`.
2. Enter the server address:
   `https://<your.ip.address>/remote.php/dav/files/<user>/`
3. Enter your credentials.

> **Note:** Use `http` if `https` fails due to self-signed certificate issues (local networks only).

### 2. Verify Mount in Terminal
Run the following to ensure the system registered the mount:

```bash
mount
```
OR
```bash
df -h
```

### 3. Force Unmount
The manual mount must be removed so the Nextcloud client can take control:

# Force unmount the manual connection

```bash
diskutil unmount force /Volumes/<your_mount_name>
```

### 4. Verification
Confirm the volume is no longer listed:

```bash
mount
```
OR
```bash
df -h
```

### 5. Restart macOS
A full restart is **required** to clear the `webdavfs` cache and allow the Nextcloud Virtual Files provider to initialize without being blocked by previous SSL attempts.
