### ISSUE TITLE
Bug Report: Upload fails due to incorrect quota check in version 3.17.0-20250805

### ISSUE THREAD

**Issue by sto228** [nextcloud/desktop#8555]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

## Summary:
After upgrading to Nextcloud Desktop Client version 3.17.0-20250805, uploads fail with the error message indicating that a 2KB file exceeds the available space in the folder which is reported as 0 KB available, even though the user quota is not reached and sufficient space is available.

### Steps to reproduce

Upgrade client to 3.17.0-20250805.
Make a change in the txt/script file in the folder which is under sync configuration
Let nextcloud-client to sync edited file 
Observe error: “Upload of 2 KB exceeds 0 B of space left in folder <folder_path> ”.

### Expected behavior

File should be synced successfully if the user and folder quotas are not exceeded.

### Which files are affected by this bug

All files in my synced folder which have been modified on the client side

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

30.0.13

### Nextcloud Desktop Client version

3.17.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
## Server side:
No specific records in the data/nextcloud.log in the respective time


## Client side: output from ~/.config/Nextcloud/logs/20250808_1108_nextcloud.log.0.gz

2025-08-08 11:09:03:144 [ info nextcloud.sync.propagator ./obj-x86_64-linux-gnu/src/libsync/nextcloudsync_autogen/EWIEGA46WW/../../../../../src/libsync/owncloudpropagator.h:213 ]:       Starting CSyncEnums::CSYNC_INSTRUCTION_ERROR propagation of "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina" by OCC::PropagateIgnoreJob(0x5789dd3888a0)
2025-08-08 11:09:03:144 [ warning nextcloud.sync.propagator ./src/libsync/owncloudpropagator.cpp:280 ]: Could not complete propagation of "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina" by OCC::PropagateIgnoreJob(0x5789dd3888a0) with status OCC::SyncFileItem::NormalError and error: "Upload of 2 KB exceeds 0 B of space left in folder remmina/remmina-connections."
2025-08-08 11:09:03:144 [ warning nextcloud.gui.activity ./src/gui/tray/usermodel.cpp:916 ]:    Item  "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina"  retrieved resulted in  "Upload of 2 KB exceeds 0 B of space left in folder remmina/remmina-connections."
2025-08-08 11:09:03:144 [ info nextcloud.gui.activity ./src/gui/tray/usermodel.cpp:872 ]:       Item  "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina"  retrieved resulted in error  "Upload of 2 KB exceeds 0 B of space left in folder remmina/remmina-connections."
2025-08-08 11:09:03:144 [ warning nextcloud.gui.activity ./src/gui/tray/activitylistmodel.cpp:580 ]:    Error successfully added to the notification list:  OCC::ActivityListModel::ErrorType::SyncError "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina" "Upload of 2 KB exceeds 0 B of space left in folder remmina/remmina-connections." OCC::SyncResult::Undefined OCC::SyncFileItem::NormalError
2025-08-08 11:09:03:145 [ warning sync.localdiscoverytracker ./src/libsync/localdiscoverytracker.cpp:70 ]:      inserted error item "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina"
2025-08-08 11:09:03:149 [ info nextcloud.sync.engine ./src/libsync/syncengine.cpp:924 ]:        Sync run took  609 ms
2025-08-08 11:09:03:149 [ warning sync.localdiscoverytracker ./src/libsync/localdiscoverytracker.cpp:84 ]:      sync failed, keeping last sync's local discovery path list
2025-08-08 11:09:03:149 [ info nextcloud.gui.folder ./src/gui/folder.cpp:1257 ]:        Client version 3.17.0-20250805.190040.9ccf474ad-1.0~jammy1  Qt 6.2.4  SSL  OpenSSL 3.0.2 15 Mar 2022
2025-08-08 11:09:03:149 [ warning nextcloud.gui.folder ./src/gui/folder.cpp:1264 ]:     SyncEngine finished with ERROR
2025-08-08 11:09:03:149 [ debug com.nextcloud.owncloudgui ./src/gui/owncloudgui.cpp:473 ]       [ OCC::ownCloudGui::slotShowTrayMessage ]:        Going to show notification with title: ' "Sync Activity" ' and message: ' "remmina/remmina-connections/group_rdp_umn-winjump---utools02w-(10-241-87-133)_10-241-87-147.remmina and 7 other files could not be synced due to errors. See the log for details." '
2025-08-08 11:09:03:150 [ info nextcloud.gui.folder ./src/gui/folder.cpp:426 ]: Folder "" sync result:  OCC::SyncResult::SyncRunning
2025-08-08 11:09:03:150 [ info nextcloud.gui.folder ./src/gui/folder.cpp:1293 ]:        the last 9 syncs failed
```

### Additional info

Workaround by downgrade to dpkg version 3.16.6-20250628. All dpkg installed from PPA stable(3.16.6-20250628) / beta(3.17.0-20250805) repositories.

**Comment by camilasan** [comment]
Thanks for the report, I will check it.
3.17.0 is not release yet, is this the release candidate that you tried?

**Comment by sto228** [comment]
Hi, I've installed packages from this PPA repository

https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client-beta

BR,
Josef

________________________________

**Comment by limatus** [comment]
Hello!

I have the same issue with RC3; Windows.

Its not uploading the files as expected by this error.

Thanks!

Edit: I've moved the files within the file structure up/down, which solved the issue. New files do not cause the issue any more. It might be related to RC1 or RC2, which I also worked with...

**Comment by Der-K-2000** [comment]
Here the same issue with `v3.17.0 rc3 (Windows)`

**Comment by camilasan** [comment]
It should be fixed with #8561 
if any of you could try the AppImage generated in the PR, that would be great.

**Comment by simpleace15** [comment]
@camilasan do you have the ability to create a exe for windows to test these changes?

**Comment by camilasan** [comment]
> [@camilasan](https://github.com/camilasan) do you have the ability to create a exe for windows to test these changes?

Please, back up your data and config folder before running it, this is not build on top of a stable branch:
https://cloud.nextcloud.com/s/oAJCCZ34rP4Kxg4

**Comment by Orteko** [comment]
Anyone still having this issue?

We have a client on v3.17.1 on Windows who had these exact symptoms, ended up reverting back to 3.16.6 to get files synced again.

**Comment by hamuchen** [comment]
Can someone reopen this issue? I have this issue with 3.17.1 on different Windows machines with different users. reverting back to 3.16.6 fixed the issue for me.

Maybe more info to reproduce: The machines have manual folder config and/or multiple users configured. Not only one user with one folder where everthing syncs.

Cheers,
hamu

**Comment by corben-svg** [comment]
Hi, the bug is not fixed, still have problem with upload to server from windows desktop app. 
0 b space left in any folder

**Comment by camilasan** [comment]
I will be working on this today, see if I can reproduce it. Will let you know later.

**Comment by camilasan** [comment]
The files that throw the error in the client, are always located in the root of the sync folder?

**Comment by hamuchen** [comment]
No, not always. I had problems syncing files in the root of the sync folder (eg. D:\sync dir\file.txt, while "sync dir" is my sync folder configured in the client), as well as files below (eg. D:\sync dir\folder\file.txt). One user came to me with the observation, that it wont sync within old folders. But I could not verify that.

**Comment by camilasan** [comment]
I couldn't reproduce the issue, I only have a theory.
If anyone could run the client with --logdebug and share the logs + name of the folders with the wrong quota, it could help.

**Comment by corben-svg** [comment]
>`The files that throw the error in the client, are always located in the root of the sync folder?`

No, I just checked it out. Files in directories of any level are not uploaded. There is only one mistake everywhere - there is not enough space.

**Comment by camilasan** [comment]
> > `The files that throw the error in the client, are always located in the root of the sync folder?`
> 
> No, I just checked it out. Files in directories of any level are not uploaded. There is only one mistake everywhere - there is not enough space.

There gotta be an exception that I am missing because I am running the client with private data on Linux and on Mac OS, and today I was working on Windows. It works. 
What quota is your server reporting? Do you have a lot of space or very little?

**Comment by camilasan** [comment]
Have anyone with the issue set any quota for the users?

**Comment by corben-svg** [comment]
> Have anyone with the issue set any quota for the users?

But the old version of the app works well, the problems start with 3.17 and 3.18. alpha

**Comment by corben-svg** [comment]
> Have anyone with the issue set any quota for the users?

Yes, I have a quota of 20 GB per user. 15 GB is available.

**Comment by camilasan** [comment]
> But the old version of the app works well, the problems start with 3.17 and 3.18. alpha

There was no quota checking before 3.17

**Comment by Orteko** [comment]
Out client had a quota set of 2GB, of which 960MB was used.

We did try various things to try and track down something common but couldn't come up with anything obvious.

First step was increasing the quota up to 5GB, which made no difference.

We ran an occ files:scan, which made no difference.

After investigating we found entire folders that didn't sync, so we thought it might just be those folders - but then we found random files in other spots that also didn't sync.

I believe all of the affected files were at least 3 levels deep in a folder hierarchy, We did try moving a folder back one level which didn't work, but moving the individual files to the root of the data did make them start to sync.

In one instance it seemed like renaming a file caused it to re-sync, but this didn't work for other files.

It's a bit of a tricky one, the only thing related seemed to be that the files were nested under a number of directories.

And to add to the confusion, another user using the same nextcloud server with the same desktop client version didn't seem to have any issues.

**Comment by camilasan** [comment]
Again, if you can run the client with --logdebug, wait for the errors to pop up and then create the debug archive, it might help.
You can upload the file here: https://cloud.nextcloud.com/s/kesfSXRZGe2bj3K (upload only link)

**Comment by camilasan** [comment]
is anyone with the issue using macOS?

**Comment by camilasan** [comment]
> And to add to the confusion, another user using the same nextcloud server with the same desktop client version didn't seem to have any issues.

are the one without the issue using virtual files on Windows?

**Comment by Orteko** [comment]
> > And to add to the confusion, another user using the same nextcloud server with the same desktop client version didn't seem to have any issues.
> 
> are the one without the issue using virtual files on Windows?

Both of them are using virtual files.

**Comment by hamuchen** [comment]
To answer a few of your questions:
- I have a huge instance, 12TB in total.
- The user quota does not make a difference, increasing it does not make a difference. If the user has 2GB or 2TB.
- I used files:scan, expired versions, cleared versions, cleared the trashbin, no difference.
- Uploading in browser works flawless, uploading with android too.
- I created a new user, gave them the same group to sync the same folder, has the same error.
- Had the error with shared folders or own folders.
- No virtual files, all normal/oldschool file sync.
- No macOS users, only Windows.

**Comment by camilasan** [comment]
> * I created a new user, gave them the same group to sync the same folder, has the same error.

and this user only synced data using the 3.17.1 version, right?

**Comment by hamuchen** [comment]
To elaborate: 
I could not upload files in a synced folder with my user and my installation. So I uninstalled nextcloud completly, removed everything in appdata, removed the *sync*.db-files rebootet, added a user with the same groups, installed 3.17.1, connected with the new user, added that folder manually, same error as before. 
Uninstalled again, removed appdata and *.db, rebooted, installed 3.16.6, connected with the original user, added that folder, synced flawlessly.

**Comment by hamuchen** [comment]
Maybe I will find the time to create the debug for you tomorrow.

**Comment by camilasan** [comment]
> * The user quota does not make a difference, increasing it does not make a difference. If the user has 2GB or 2TB.

Do the users have personal quotas? Do the folders they use have quota? Like a teamfolder?

**Comment by hamuchen** [comment]
Yes, users have quotas, But even changing it to unlimited did not change the error. The folders themselfs are simple folders under files which have been shared with a group. But even unshared folders (as stated before) have the same problem.
The installation is roughly 10 years old, always updated to the latest nextcloud-version.

**Comment by corben-svg** [comment]
Maybe just remove the quota check, as it was in previous versions, and everything worked correctly?

**Comment by ebogaard** [comment]
We're constantly having to give our users "wrong" advise: don't upgrade your client. All due to this issue.
I can't understand why this isn't a bigger issue: doesn't everybody assign quota's to every user?

The quota check does function correctly in the web interface, but gives the quota check error in the desktop client for all our users.

**Comment by corben-svg** [comment]
We are also waiting for a solution to this problem.

**Comment by Orteko** [comment]
Seems like it's a weird one.

We re-tested by syncing the affected user on a different PC with the broken client version and it worked successfully with no issues.

The original PC still has issues on that version however so it seems like it's some kind of broken local cache or something?

**Comment by ebogaard** [comment]
Yeah, I've been trying to reproduce this as well, as many users experience this issue (but not all). But I can't reproduce this issue locally.
Now I'm going to just let v17.x run for a while to see if something goes wrong somehow.

**Comment by camilasan** [comment]
I did create this build based on stable-3.17 and #8714: https://cloud.nextcloud.com/s/Npb5ajNK2tGkRr2
It contains a change and more logs, if you want to give it a try.

I couldn't find a way to reproduce it yet.

**Comment by Luto73** [comment]
I can confirm this bug using client 3.17.2daily (EndeavourOS).

**Comment by camilasan** [comment]
> I did create this build based on stable-3.17 and [#8714](https://github.com/nextcloud/desktop/pull/8714): https://cloud.nextcloud.com/s/Npb5ajNK2tGkRr2
> It contains a change and more logs, if you want to give it a try.

did anyone gave it a try?
the changes (https://github.com/nextcloud/desktop/pull/8714) in this build are not in master or any release.

**Comment by ebogaard** [comment]
I finally experienced the issue, then installed the custom build provided by @camilasan and the issue remained.
I found the log, but how can I send it securely/privately, as it could contain personal info.

**Comment by corben-svg** [comment]
I have checked this version. The error persists. An attempt to synchronize my local files to the server ends with an error "Upload of ... B exceeds 0 b of space left in folder ....". I have 15 GB of 20 GB of my quota available in my account.

**Comment by nilsding** [comment]
hmm... could anyone affected by this try to look at the network requests from the web UI while browsing a folder where the quota check fails?  (right-click on page -> *Inspect* -> *Network* tab)

I'd like to know what kind of values the `<d:quota-available-bytes>` attributes are set to in a `PROPFIND` response -- just to make sure the server doesn't provide us with a `0` value already.

**Comment by hamuchen** [comment]
The upload does not fail via Browser or Android App, only the Windows App fails.

stats has following values:
`{
    "message": "ok",
    "data": {
        "free": 2584407983511,
        "used": 1813638527589,
        "quota": 4398046511100,
        "total": 4398046511100,
        "relative": 41.24,
        "owner": "hamu",
        "ownerDisplayName": "hamu",
        "mountType": "",
        "mountPoint": ""
    }
}`
When uploading a file, your parameter is this:
`
<d:quota-available-bytes>2.58440798353E+12</d:quota-available-bytes>
`

Cheers
hamu

**Comment by nilsding** [comment]
@hamuchen thank you so much for checking!

I think the client fails to parse the value of that attribute — I need to verify if that’s the case indeed.  But as I can’t explain it otherwise I guess this is the root cause of that issue.

**Comment by hamuchen** [comment]
@nilsding as you closed this as completed, is there a client to try if it is really fixed? Thanks.

Cheers
hamu

**Comment by corben-svg** [comment]
I just installed version 4.0.0-rc2 Windows from the beta update channel. The problem with checking the quota persists, the files are not uploaded to the server

**Comment by nilsding** [comment]
the rc2 was released before this change got merged

We'll include this in 4.0.0, to test the change before the final 4.0 release you will need to wait until tomorrow for the new daily build to appear.

**Comment by corben-svg** [comment]
I have installed a new release (windows 4.0.0). The quota verification problem persists. Uploading files to the server is not working.

**Comment by corben-svg** [comment]
Reopen please fix

**Comment by corben-svg** [comment]
I just installed the new version 4.0.1 for Windows. The quota verification error persists. The problem has not been solved. Please reopen issue @camilasan @nilsding 
Error: "Upload of 1 kb exceeds 0 B of space left in folder ...."

**Comment by corben-svg** [comment]
For information, updated to version 4.0.4, the error persists, files are not synchronized. @camilasan

**Comment by corben-svg** [comment]
Please reopen issue

**Comment by hamuchen** [comment]
The error is gone on my end with 4.0.4. Maybe its a different issue on your end?

Cheers,
hamu

**Comment by FireCulex** [comment]
<img width="1147" height="881" alt="Image" src="https://github.com/user-attachments/assets/698a8ff1-3a5d-4e0d-84d4-4a34a42d3245" />
