### ISSUE TITLE
Uploding e2e encrypted files seems to take forever/fails

### ISSUE THREAD

**Issue by rugk** [nextcloud/desktop#890]
I have less than 500kB files to sync (in two files) for testing. However, as far as I see they never really uploaded.
Likely also related to the issues on the Android side: https://github.com/nextcloud/android/issues/3291

### Expected behaviour
Sync.

### Actual behaviour
It seems to retry syncing these little files and always seems to fail:

Currently:
![image](https://user-images.githubusercontent.com/11966684/48982580-d0bc2100-f0e4-11e8-8768-3451e4566768.png)

In Nautilus I do see by their icons that it only tries to sync the (to-be) e2e encrypted folder.

Before (a try some days ago) also like this:
![sync](https://user-images.githubusercontent.com/11966684/48982599-0d881800-f0e5-11e8-9311-111ede22e745.png)

(Note the progress bar is not moving here – it can stay like this for minutes…)

Note it often does not even count the files (two files) correctly.

### Steps to reproduce
0. e2e setup, setup on Android due to https://github.com/nextcloud/desktop/issues/560
1. Created encrypted folder on Android.
2. Synced on desktop. (Everything worked so far.)
3. Put files into it.

### Client configuration
Client version: 2.5.0git https://github.com/nextcloud/desktop/commit/371001c9ffea5e99abe971fcb155af64f25b024b

Operating system: Fedora 29

OS language: de_DE

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.11.1, OpenSSL 1.1.1 FIPS 11 Sep 2018

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client:
`/usr/bin/nextcloud`

### Server configuration
Operating system: Debian-based

Web server: nginx

Database: mysql

PHP version: 7

Nextcloud version: 14

Storage backend (external storage): no

### Logs

(put into details tags)

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

<details>

```

[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::GetFolderEncryptStatusJob::finished 	GetFolderEncryptStatus of QUrl("https://sub.domain.example:4444/subdir/remote.php/webdav/END-TO-END/CRYPTO-PATH") finished with status QNetworkReply::NetworkError(NoError) ""
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/END-TO-END/CRYPTO-PATH" has X-Request-ID "9d14144c-2135-43ef-83f7-26cfad1389ed"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://sub.domain.example/nextcloud" + "END-TO-END/CRYPTO-PATH-without-leading-slash" "OCC::PropagateUploadEncrypted"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::GetFolderEncryptStatusJob::finished 	GetFolderEncryptStatus of QUrl("https://sub.domain.example:4444/subdir/remote.php/webdav/END-TO-END/CRYPTO-PATH") finished with status QNetworkReply::NetworkError(NoError) ""
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/END-TO-END/CRYPTO-PATH" has X-Request-ID "22e19db0-6fcd-4fcd-be6d-ca22ae12e316"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://sub.domain.example/nextcloud" + "END-TO-END/CRYPTO-PATH-without-leading-slash" "OCC::PropagateUploadEncrypted"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/") FINISHED WITH STATUS "OK"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::LsColJob::finished 	LSCOL of QUrl("https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/END-TO-END/CRYPTO-PATH") FINISHED WITH STATUS "OK"
[OCC::LockEncryptFolderApiJob::start 	locking the folder with id "124028" as encrypted
[OCC::AccessManager::createRequest 	4 "" "https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json" has X-Request-ID "abeb2fa7-b3f1-4c11-8e2a-290d04d5474e"
[OCC::AbstractNetworkJob::start 	OCC::LockEncryptFolderApiJob created for "https://sub.domain.example/nextcloud" + "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028" "OCC::PropagateUploadEncrypted"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::LsColJob::finished 	LSCOL of QUrl("https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/END-TO-END/CRYPTO-PATH") FINISHED WITH STATUS "OK"
[OCC::LockEncryptFolderApiJob::start 	locking the folder with id "124028" as encrypted
[OCC::AccessManager::createRequest 	4 "" "https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json" has X-Request-ID "63389dd1-b789-4b87-bd09-94dc8d1d2e4d"
[OCC::AbstractNetworkJob::start 	OCC::LockEncryptFolderApiJob created for "https://sub.domain.example/nextcloud" + "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028" "OCC::PropagateUploadEncrypted"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(ContentAccessDenied) "Error transferring https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json - server replied: " QVariant(int, 403)
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(ContentAccessDenied)
[OCC::WebFlowCredentials::stillValid 	"Error transferring https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json - server replied: "
[OCC::LockEncryptFolderApiJob::finished 	error locking file "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028" "Error transferring https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json - server replied: " 403
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(ContentAccessDenied) "Error transferring https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json - server replied: " QVariant(int, 403)
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(ContentAccessDenied)
[OCC::WebFlowCredentials::stillValid 	"Error transferring https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json - server replied: "
[OCC::LockEncryptFolderApiJob::finished 	error locking file "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028" "Error transferring https://sub.domain.example:4444/subdir/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/124028?format=json - server replied: " 403
[OCC::AccessManager::createRequest 	2 "" "https://sub.domain.example:4444/subdir/ocs/v2.php/apps/notifications/api/v2/notifications?format=json" has X-Request-ID "47c45c35-c721-43ff-b818-b2bfdcea508b"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://sub.domain.example/nextcloud" + "ocs/v2.php/apps/notifications/api/v2/notifications" "OCC::ServerNotificationHandler"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://sub.domain.example:4444/subdir/ocs/v2.php/apps/notifications/api/v2/notifications?format=json") FINISHED WITH STATUS "OK"
[OCC::JsonApiJob::finished 	Nothing changed so nothing to retrieve - status code:  304
[OCC::ServerNotificationHandler::slotNotificationsReceived 	Status code  304  Not Modified - No new notifications.
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/" has X-Request-ID "fe26dbb2-5f3f-4f05-8418-7bbba8c67522"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://sub.domain.example/nextcloud" + "/" "OCC::QuotaInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://sub.domain.example:4444/subdir/remote.php/dav/files/<username>/") FINISHED WITH STATUS "OK"

```

</details>

2. Web server error log:
grepping for `end_to_end_encryption` found nothing

3. Server logfile: nextcloud log (data/nextcloud.log):

<details>

```
{"reqId":"KYMqOqIeJsjRGFUlb774","level":0,"time":"2018-11-20T21:55:53+01:00","remoteAddr":"<IP2-REMOVED>","user":"admin","app":"no
app in context","method":"GET","url":"\/nextcloud\/index.phps","message":"No cache entry found for \/appdata_ocl8foq5dpr7\/end_to_end_encryption (storage: local::\/path-to\/data-dir\/nextcloud\
/, internalPath: appdata_ocl8foq5dpr7\/end_to_end_encryption)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"KYMqOqIeJsjRGFUlb774","level":0,"time":"2018-11-20T21:55:53+01:00","remoteAddr":"<IP2-REMOVED>","user":"admin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.ph
ps","message":"No cache entry found for \/appdata_ocl8foq5dpr7\/end_to_end_encryption\/private-keys (storage: local::\/path-to\/data-dir\/nextcloud\/, internalPath: appdata_ocl8foq5dpr7\/end_to
_end_encryption\/private-keys)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"KYMqOqIeJsjRGFUlb774","level":0,"time":"2018-11-20T21:55:54+01:00","remoteAddr":"<IP2-REMOVED>","user":"admin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.ph
ps","message":"No cache entry found for \/appdata_ocl8foq5dpr7\/end_to_end_encryption\/public-keys (storage: local::\/path-to\/data-dir\/nextcloud\/, internalPath: appdata_ocl8foq5dpr7\/end_to_
end_encryption\/public-keys)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"KYMqOqIeJsjRGFUlb774","level":0,"time":"2018-11-20T21:55:55+01:00","remoteAddr":"<IP2-REMOVED>","user":"admin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.ph
ps","message":"No cache entry found for \/appdata_ocl8foq5dpr7\/avatar\/admin\/avatar.jpg (storage: local::\/path-to\/data-dir\/nextcloud\/, internalPath: appdata_ocl8foq5dpr7\/avatar\/admin\/a
vatar.jpg)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"9srd5xo6I0OBdBuYHZu1","level":3,"time":"2018-11-20T21:56:03+01:00","remoteAddr":"93.193.74.198","user":"--","app":"PHP","method":"GET","url":"\/nextcloud\/index.phpider\/","message
":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"GuzzleHttp\/6.2.1 curl\/7.47.0 PHP\/7.0.32-0ubuntu0.16.04.1","version"
:"14.0.3.0"}
{"reqId":"5omzxrVFoKIVGo1G61pU","level":3,"time":"2018-11-20T21:57:32+01:00","remoteAddr":"<IP2-REMOVED>","user":"--","app":"PHP","method":"GET","url":"\/nextcloud\/status.php","message":"Ze
nd OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.0git (Nextcloud)","version":"14.0.3.0"}
{"reqId":"ob6u2VN0Dkgu9Gk0bkSA","level":3,"time":"2018-11-20T21:57:44+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"PHP","method":"POST","url":"\/nextcloud\/ocs\/v2.php\/apps\/end
_to_end_encryption\/api\/v1\/public-key?format=json","message":"openssl_csr_sign(): cannot get CSR from parameter 1 at \/www\/apps\/end_to_end_encryption\/lib\/SignatureHandler.php#60","user
Agent":"Mozilla\/5.0 (Linux) mirall\/2.5.0git (Nextcloud)","version":"14.0.3.0"}
{"reqId":"ob6u2VN0Dkgu9Gk0bkSA","level":3,"time":"2018-11-20T21:57:44+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"end_to_end_encryption","method":"POST","url":"\/nextcloud\/ocs\
/v2.php\/apps\/end_to_end_encryption\/api\/v1\/public-key?format=json","message":"Can't create public key: could not sign the CSR, please make sure to submit a valid CSR","userAgent":"Mozill
a\/5.0 (Linux) mirall\/2.5.0git (Nextcloud)","version":"14.0.3.0"}
{"reqId":"jHVJxgGHZmF7CePXL5cj","level":3,"time":"2018-11-20T21:57:52+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"PHP","method":"GET","url":"\/nextcloud\/ocs\/v2.php\/apps\/noti
fications\/api\/v2\/notifications","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla\/5.0 (X11; Fedora;
Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"Pi1bOYabtW4anDZr4HBU","level":3,"time":"2018-11-20T21:59:54+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"PHP","method":"PROPFIND","url":"\/nextcloud\/remote.php\/caldav
\/calendars\/<username>\/fbf70b57-2fd3-4948-9c13-4a2177f2c6cb\/","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Evo
lution\/3.30.2","version":"14.0.3.0"}
{"reqId":"ppzVq88pRqPZCZjDYLzx","level":3,"time":"2018-11-20T22:01:24+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"PHP","method":"GET","url":"\/nextcloud\/ocs\/v1.php\/cloud\/use
r?format=json","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.0git (Nextclou
d)","version":"14.0.3.0"}
{"reqId":"61NeSpMDKDfMcpVCMYAo","level":3,"time":"2018-11-20T22:01:30+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"PHP","method":"POST","url":"\/nextcloud\/ocs\/v2.php\/apps\/end
_to_end_encryption\/api\/v1\/public-key?format=json","message":"openssl_csr_sign(): cannot get CSR from parameter 1 at \/www\/apps\/end_to_end_encryption\/lib\/SignatureHandler.php#60","user
Agent":"Mozilla\/5.0 (Linux) mirall\/2.5.0git (Nextcloud)","version":"14.0.3.0"}
{"reqId":"61NeSpMDKDfMcpVCMYAo","level":3,"time":"2018-11-20T22:01:30+01:00","remoteAddr":"<IP2-REMOVED>","user":"<username>","app":"end_to_end_encryption","method":"POST","url":"\/nextcloud\/ocs\
/v2.php\/apps\/end_to_end_encryption\/api\/v1\/public-key?format=json","message":"Can't create public key: could not sign the CSR, please make sure to submit a valid CSR","userAgent":"Mozill
a\/5.0 (Linux) mirall\/2.5.0git (Nextcloud)","version":"14.0.3.0"}
{"reqId":"JFfPheDVpZd2RZJhjf5x","level":3,"time":"2018-11-20T22:03:09+01:00","remoteAddr":"<IP-REMOVED>","user":"<username>","app":"PHP","method":"GET","url":"\/nextcloud\/ocs\/v1.php\/cloud\/use
rs\/<username>?format=json","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\
/3.3.2","version":"14.0.3.0"}
```

</details>

Searching in the web UI logs (for "encryption"), I get many of these:
![image](https://user-images.githubusercontent.com/11966684/48982565-918dd000-f0e4-11e8-8923-08d0b55fbc51.png)

…many of these:
![image](https://user-images.githubusercontent.com/11966684/48982573-a79b9080-f0e4-11e8-9786-a91a6022d5b6.png)

…and nothing special anymore:
![image](https://user-images.githubusercontent.com/11966684/48982575-bd10ba80-f0e4-11e8-8869-229f1745a23e.png)

**Comment by rugk** [comment]
Any news here what I can do to troubleshoot/debug this, or is this "expected"??

**Comment by rugk** [comment]
Testing with a new user and although the setup works and it partially even syncs, it also seems to fail at some point: https://github.com/nextcloud/android/issues/3291#issuecomment-445461899

**Comment by theoDiefenthal** [comment]
+1, same issue here.

**Comment by Baeda73** [comment]
+1, files put in an encrypted folder do not upload, blocking client forever. happens on iOS and macOS client. e2e not useable at all.
deletion of file reanimate client

**Comment by rugk** [comment]
Did I also already mention it actually blocks **any file upload**, even if you have multiple users connected in your desktop client and only one has this issue?

**Comment by kristog** [comment]
I have the same problem here, with the linux 2.5.1 AppImage and on windows.
I noticed that if I copy files one by one in the encrypted folder (waiting the first upload to finish before copying a new file) it works. I tested with files up to 50Mb. If I copy more than one file at time, the it will get stuck on uploading the second file (tested with 2 small files).

**Comment by SnejPro** [comment]
Same issue with 2.5.1 on windows.
Download and decryption of encrypted files works.
Upload and encryption does not work.

When i set a directory as encrypted on windows, the upload of files in this directory does not work on Android.

**Comment by marbetschar** [comment]
Same issue here on macOS. Is there any known workaround?

**Comment by rugk** [comment]
IMHO it is quite troubling that **no one from Nextcloud** commented on this issue… Is this expected or what? What can we do? etc.…

E2e crypto is really not well-developed in Nextcloud. I don't like to say that, but in the current state is just absolutely unusable.

**Comment by marbetschar** [comment]
@rugk same feelings here. I'm currently testing Nextcloud with the goal to eventually completely switch from other Cloud providers and the E2E feature seemed like a huge selling point. Unfortunately it simply does not work.

I understand new things need time to mature and it's quite early days for E2E within Nextcloud. But at least some sort of workaround or at least feedback would be .... nice.

**Comment by spackmat** [comment]
Had e2ee never get to work due to this problem on different NextCloud instances on different servers and users with different computers. Everywhere the same: when the desktop client tries to add a file to an encrypted folder, the folder breaks. Meaning that also the android client cannot upload new files after that.

Today, I tested v2.6.1-rc1 very hopeful, but still doesn't work. And no feedback. And e2ee is on the market sind several major versions of NextCloud, so I would expect it to at least work at all.

**Comment by 0x47** [comment]
I suspect that no one really uses the E2E encryption feature because it is still in the alpha stage (since a long time). Sadly it seems that because of that the developers think there is no demand for E2EE and virtually stopped working on it. Or maybe there really is too little demand.

**Comment by marbetschar** [comment]
@0x47 regarding the amount of issues targeted against E2E and given the activity there (at least initially) there is quite a high demand. But: "Nextcloud + E2E" is waaaaaaaaay better than "Nextcloud" - but it does also works the way it ever has, so I can wait till ready.

Nevertheless, its sad to see there is no official communication/activity/whatsoever around this feature.

**Comment by SnejPro** [comment]
I also think that the demand is high. There are companies like Boxcryptor who sell software for encrypting files stored in cloud storages. But i'd like to see this feature implemented in NC natively. But as @0x47 said: the current E2E-feature is completly unusable.

**Comment by 0x47** [comment]
@marbetschar I am not sure what you mean by "

> but it does also works the way it ever has

but for me the E2EE has never worked for the desktop client. So from my point of view the developers are too busy/lazy to essentially copy/paste the somewhat working Android E2E code to this desktop client. Anyway, I have so many other issues with this desktop client that I have to use the OwnCloud client most of the time (crashing when using HTTP2, broken sync when using umlauts in file names, crashing due to unknown reasons) - sorry for the off-topic.

**Comment by marbetschar** [comment]
@0x47 I meant the fact, that Nextcloud always worked without E2EE. And it continous to do so. That said, there is no urgency of getting it done. Neither for Nextcloud developers nor for Nextcloud users - especially if Nextcloud developers get paid for other features.

I don't want to say I'm supporting this prioritization, but I'm not a Nextcloud developer. Overall its disappointing how the whole E2EE stuff went so far - at least communication wise.

**Comment by 0x47** [comment]
Thank for the clarification, it is a valid point. For me personally, coming from Seafile with working encryption (granted, not with the best concept), the features is a must-have mid- to long-term. For me, it is the single only feature that makes it better than Seafile. I guess I was too excited about this and switched too early.

**Comment by marbetschar** [comment]
> ... I guess I was too excited about this and switched too early.

IMHO that's exactly the problem. Happened to me as well. Nextcloud said the feature is ready - and as problems occured, Nextcloud went completely silent. One might argue they still provide the impression of readiness, calling it an "Enterprise-grade Encryption Solution": https://nextcloud.com/endtoend/

The sad truth is E2EE is far from ready - and calling this feature an "Enterprise-grade Encryption Solution" is .... well, is too far of a stretch.

**E2EE, at this stage, never should have been released to the public in the first place.**

**Comment by KopfKrieg** [comment]
If you only use the Android app E2EE works fine. It's the desktop client that's broken. They created a new RFC that should fix the whole encryption process but it's not yet implemented. Also, E2EE is not compatible with Nextcloud 17. So, yeah, E2EE in it's current state, is more or less broken. I really hope that gets fixed soon.

**OT:**
> (crashing when using HTTP2, broken sync when using umlauts in file names, crashing due to unknown reasons)
Are you using MySQL as database? My server uses HTTP2, I've got many Umlauts and special characters in my files (stored in german, french, russian and greek), and the client never crashes here. I've only heard MySQL might be the problem in this case (I'm using PostgreSQL, but MariaDB should work too).

**Comment by rugk** [comment]
> They created a new RFC that should fix the whole encryption process

That sounds interesting, do you have a link?

**Comment by KopfKrieg** [comment]
More or less, I had a few links pointing to all open issues but I can't find them now. That's the only one I could find: https://github.com/nextcloud/end_to_end_encryption_rfc/issues/34

Unfortunately, the issue doesn't include any details. I know I've created a issue on GitHub talking about it, but it got closed. The end results was that a new version of the RFC has to be implemented and all files/folders have to be re-encrypted.

**Comment by 0x47** [comment]
> Are you using MySQL as database? My server uses HTTP2, I've got many Umlauts and special characters in my files (stored in german, french, russian and greek), and the client never crashes here. I've only heard MySQL might be the problem in this case (I'm using PostgreSQL, but MariaDB should work too).

Let's not take the OT too far, as it is another big issue beyond the scope of this thread. I use MariaDB and the issues are described here:
- Supposedly HTTP2: #1182 
- Still crashing for me with HTTP2 disabled (hence _supposedly_)
- Crashing for other strange reasons: #1205 

Fact is: none of the issues are happening with the OwnClient client - so I doubt the DB is the reason.

**Comment by er-vin** [comment]
I can't seem to reproduce the initially reported behavior with current master. I'll take the liberty to close this one, but please reopen it or open a new one if that shows up again with upcoming 2.7 releases.

**Comment by adimol** [comment]
I'm experience the same issue on Fedora 32 AppImage version 3.0.2. Nextcloud server version 20.0.1 (also same with 20.0.0) - using docker.

The issue recreates reliably for me, and it did so many times. Create an empty encrypted (e2ee) dir, then add like 50 or more files to it. Syncing gets stuck. If I do the same without e2ee folders, it works okay.

E2ee is not production ready if a client app cannot sync e2ee. It's far beyond usable if I cannot do this basic thing.

**Comment by elman22** [comment]
Same here with NC 20.0.1 and client 3.0.2 on Manjaro.

When I create encrypted folder with 10 files, maybe 3 are uploaded and then whole process gets stuck and doesn't move for hours. When I cancel sync, 3 uploaded files appear on cloud and are synced to other clients. When I restart sync, few other files are uploaded and process freezes again.

So I agree, this is not usable in production. :disappointed:

**Comment by BirdInFire** [comment]
05/12/2021 and this don't work at all on desktop error 503 when upload and 404 when download E2E is a "BUG" not a "FEATURE"

**Comment by adimol** [comment]
Perhaps this ticket should be reopened (unless there are new tickets created about the same issue), since other people are still experiencing uploading problems with e2ee.

I've stopped using e2ee because my situation is different now (I have my own HW infrastructure and currently I'm the only user), but in any other situations I would be very keen to have e2ee working.
