### ISSUE TITLE
macOS: macdeployqt.py script broken

### ISSUE THREAD

**Issue by ppaeps** [nextcloud/desktop#913]
Trying to build a0d6f5fb6 on macOS 10.14.1 with Qt 5.11.2 installed using homebrew produces a nextcloud.app bundle that is incorrectly linked.

This is probably a similar problem the author of #626 was describing.

The `macosdeployqt.py` script spews output like:

```
-- Deploying (Qt) dependencies and fixing library paths...
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtCore.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtGui.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtWidgets.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/opt/qt/lib/QtMacExtras.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/opt/qt/lib/QtXml.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/opt/qt/lib/QtConcurrent.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtNetwork.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtQml.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtQuick.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtWebChannel.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtPositioning.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtPrintSupport.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/Cellar/qt/5.11.2_1/lib/QtQuickWidgets.framework/Versions/5/Helpers: No such file or directory
cp: /usr/local/opt/qt/lib/QtWebEngineWidgets.framework/Versions/5/Helpers: No such file or directory
[...]
ln: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/QtWebEngineCore: File exists
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_resources.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/icudtl.dat: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/ar.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/en-US.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/lt.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/tr.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/te.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/lv.pak: Permission denied
cp: /Users/philip/tmp/nextcloud-desktop/install/nextcloud.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Resources/qtwebengine_locales/mr.pak: Permission denied
```

(Unrelated aside: I don't understand why it wants to find stuff under `/usr/local/Cellar`.  That path does not appear in my configuration.  It exists, but there is no Helpers directory there.)

My cmake command is:
```
cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DNO_SHIBBOLETH=1 -DQTKEYCHAIN_LIBRARY=$HOME/tmp/nextcloud-desktop/install/lib/libqt5keychain.dylib -DQTKEYCHAIN_INCLUDE_DIR=$HOME/tmp/nextcloud-desktop/install/include/qt5keychain -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/ -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl@1.1/lib
```

I've experimented with using Qt's own `macosdeployqt` utility.  That doesn't produce a working bundle either.  It moves libssl, libcrypto and libqt5keychain to Frameworks and doesn't update the binaries.  The linkage of the Qt libraries is correct though.  After manually adjusting the linkage of libnextcloudsync/libocsync/nextcloud/nextcloudcmd and moving libssl and libcrypto, things work.

I think using the Qt macosdeployqt voodoo is probably the way forward, rather than the Python script but I can't figure out how to teach CMake to run it only once.  And we'd probably still need some additional voodoo to adjust the linkage of libnextcloudsync/libocsync.

Aside: how come the daily builds don't run into this problem?

**Comment by skobba** [comment]
Having the same problem here with macOS 10.14.2 and Qt 5.12.0 (installed with brew). Getting lots of "Permission denied" and "File exists". The /usr/local/Cellar/qt* comes with the brew installation of qt (/usr/local/opt/qt -> /usr/local/Cellar/qt/5.12.0). The nextcloud.app is only working on my dev machine at this point. Not able to sign the app either, due to invalid symlinks. On my test machine it starts after installing qt (with brew), but displays a blank screen where the login screen should appear.

**Comment by ppaeps** [comment]
I did a little more testing when I was playing with this earlier this month.

If you use Qt's own `macosdeployqt` utility (and hack around the linkage manually with `otool` and `install_name_tool`), you can actually produce a nextcloud.app that works and that can be signed.

I think the way forward is to ditch the Python script and wrap Qt's own `macosdeployqt` in a shell script that fixes the linkage.  If I find some spare cycles, I'll try to do exactly that and submit a patch.

**Comment by skobba** [comment]
I got a "macdeployqt" that came with the brew installation, and no "macosdeployqt" (same thing I presume). I played around with "otool" on the app and frameworks and saw some wrong refs. Did not get to the "install_name_tool" part. Burning oil before xmas here, but would be happy to work with you to get a working deploy script in your next spare cycle! And of course the Nextcloud team, please :)

**Comment by hiiamok** [comment]
@ppaeps I think the daily builds don't run into this problem, because they are using a much older Qt version. The script might work for this version, since Qt changed quite a lot.

I fixed it in using my own script instead of the available python script.

**Comment by yunlhan** [comment]
> I fixed it in using my own script instead of the available python script.

@hiiamok do you mind sharing what changes you have made regarding the python script? So far I have only changed all the occurrences of `Qt-5.6.2` in `macdeployqt.py` file to `Qt-5.10.1` which is the version I use, but still there are complaints about nonexistent helper files and warnings like `cannot resolve ... not fixed!`.

Thanks.

**Comment by hiiamok** [comment]
@hiiamok Well I actually am not using the python script at all. I wrote a bash script which does things how I want them to be.

**Comment by yunlhan** [comment]
> @hiiamok Well I actually am not using the python script at all. I wrote a bash script which does things how I want them to be.

Do you mind sharing the bash script you wrote?

**Comment by vansante** [comment]
I ran into the same problem and patched the python script with the following patch:
```patch
diff --git a/admin/osx/macdeployqt.py b/admin/osx/macdeployqt.py
index 2571b8eb9..0ed4d8b86 100755
--- a/admin/osx/macdeployqt.py
+++ b/admin/osx/macdeployqt.py
@@ -32,7 +32,7 @@ FRAMEWORK_SEARCH_PATH=[
     os.path.join(os.environ['HOME'], 'Library/Frameworks')
 ]
 
-LIBRARY_SEARCH_PATH=['/usr/local/lib', '/usr/local/Qt-5.12.5/lib', '.']
+LIBRARY_SEARCH_PATH=[os.path.join(os.environ['QT_DIR'], 'lib'),'/usr/local/lib', '/usr/local/Qt-5.12.5/lib', '.']
 
 QT_PLUGINS = [
     'sqldrivers/libqsqlite.dylib',
@@ -45,7 +45,7 @@ QT_PLUGINS = [
 ]
 
 QT_PLUGINS_SEARCH_PATH=[
-#    os.path.join(os.environ['QTDIR'], 'plugins'),
+    os.path.join(os.environ['QT_DIR'], 'plugins'),
 #    '/usr/local/Cellar/qt/5.2.1/plugins',
     '/usr/local/Qt-5.12.5/plugins',
 ]
```
I then set the `QT_DIR` environment variable to the correct path and everything worked.

**Comment by FlexW** [comment]
I think that issue does not apply anymore. The building works fine. Feel free to reopen the issue if think different.
